### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#1]
Creating this as a reminder for myself (in case nobody has done this in the next 20h) and as a todo-check for the community in general

**Comment by fybx** [comment]
@alba4k, can you add hyprlang as a dependency to the PKGBUILD, please?

![image](https://github.com/hyprwm/hyprlock/assets/41127439/be2803d3-de0b-4bbb-a06a-f56faa96676c)

**Comment by alba4k** [comment]
The problem is that hyprlang-git still shows up as 0.3.2 (the maintainer would need to run makepkg and update the pkgver)

This will fix itself as soon as hyprlang in the repos is updated to 0.4.0

the problem here isn't that hyprlang isnt added as a dependency, it's that _it is_, and that I specified that its version needs to be at least 0.4.0

this issue will fix itself in some time, in the meantime, should I just remove the check? I assume this also affects the hypridle-git package?
