### ISSUE TITLE
Multiple characters input for each key press after switching TTY

### ISSUE THREAD

**Issue by kendellfab** [hyprwm/hyprlock#100]
Sometimes I need to switch between TTYs. If my screen is locked when I switch back to my graphical TTY, each key press enters multiple characters in the input field, which in essence inputs the incorrect password and I'm no longer able to unlock. I've noticed that the number of characters input (for each key press) increases each time I switch between TTYs.

**Comment by fufexan** [comment]
Duplicate of https://github.com/hyprwm/hyprlock/issues/66? Are you on the latest commit?

**Comment by kendellfab** [comment]
It looks like I need to improve my searching game.

I'm currently building it through the aur hyprlock package. Knowing there is a fix in place, I can update accordingly.
