### ISSUE TITLE
Wide nerd fonts get cut off in label unless characters follow after

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/hyprlock#103]
If I add say the Hyprland logo from Nerd fonts to a labels text with nothing else it will get cut off on the right as it needs a space adding. I can't see a way of adding a space after the icon as the usual `"` does not work as hyprlock prints the `"` character too.
The only way around it is to put text after the icon like I have done below.

```
label {
    text =  Hyprland session locked
    color = rgb(255, 255, 255)
    font_family = GoMono Nerd Font
    font_size = 24
    position = 0, 0
    halign = center
    valign = bottom
}
```

If you remove the text and just leave the logo it will get it's right hand side cut off as some Nerd fonts require a space inserting after the icon as they are wide.

**Comment by vaxerski** [comment]
I think this would be a pango issue... unless there is some prop I am unaware of.

https://github.com/hyprwm/hyprlock/blob/main/src/renderer/AsyncResourceGatherer.cpp#L233-L234

**Comment by vaxerski** [comment]
hyprlang doesn't support that. You can make it an output of a command, though.

**Comment by justinesmithies** [comment]
> hyprlang doesn't support that. You can make it an output of a command, though.

Perfect and thank you, I got it working now.

```
label {
    text = cmd[] echo ' '
    color = rgb(255, 255, 255)
    font_family = GoMono Nerd Font
    font_size = 24
    position = 0, 0
    halign = center
    valign = bottom
}
```
