### ISSUE TITLE
Pressing enter without any password makes the entire screen red. 

### ISSUE THREAD

**Issue by cuanim** [hyprwm/hyprlock#107]
Hi, hyprlock works fine normally but if I click enter without entering any password, the entire screen becomes red and no more input is accepted.
For troubleshooting I removed hyprlock.conf but it didn't stop.

**Comment by zDyanTB** [comment]
Just to add 

[here](https://pastebin.com/6qEMPiYq) It's the log using `hyprlock -v`

It seems that the system is still running, only the scream turns red. I can unlock the system and move the mouse

**Comment by pdf** [comment]
I can't reproduce by entering an empty password, but can reproduce randomly when exiting hyprlock by grace period, so I guess there's some race somewhere.

The log seems to indicate that hyprlock exited normally though, so perhaps this is a Hyprland bug?

[hyprlock.log](https://gist.github.com/pdf/7009508a674af0c5de346d185ebc68df#file-hyprlock-log)

**Comment by zDyanTB** [comment]
> The log seems to indicate that hyprlock exited normally though, so perhaps this is a Hyprland bug?

That same bug happened to me when I was playing on FS and the swaylock triggered, I did something and the screen turned red. Maybe its hyprland
