### ISSUE TITLE
Background screenshot on monitor with rotated orientation

### ISSUE THREAD

**Issue by Dsverre** [hyprwm/hyprlock#111]
In my setup I have a monitor which is rotated 90 degrees.

When I use:
```
background {
    monitor =
    path = screenshot
....
....
}
```
hyprlock does not "respect" the orientation and shows a wrongly rotated screenshot. 
Is there a way to define this in the configuration file or does it have to/can it be added?

**Comment by vaxerski** [comment]
can you take a screenshot / picture of how it looks?

**Comment by RadicalityIncident** [comment]
Same effect here. Took some phone camera photos of the screen unlocked and locked and I disabled blur so it was more obvious what was happening. 
![LockUnlocked](https://github.com/hyprwm/hyprlock/assets/43446766/ca26cfe7-4504-411a-a1c3-951e1791c78d)
![LockRotate](https://github.com/hyprwm/hyprlock/assets/43446766/4a35cce8-7fc8-4ddb-8f54-1c7a1a2cdc7f)

**Comment by vaxerski** [comment]
lul

**Comment by vaxerski** [comment]
worth noting also requires https://github.com/hyprwm/Hyprland/commit/cc94123fa7d45e816327b4b8c8592589313f4718 to work properly
