### ISSUE TITLE
Lock surfaces not being created for new monitors (red screen after unplugging and replugging a display)

### ISSUE THREAD

**Issue by liraz747** [hyprwm/hyprlock#117]
![20240302_013306](https://github.com/hyprwm/hyprlock/assets/84682255/fda4b118-1724-43e9-b27d-96e7881e4400)

When turning my monitor off and on while hyprlock is active, I'm present with a red screen, this is happening because hyprland is detecting the monitor as a new one when disconnected and connected again and hyprlock is not creating a lock surface for the monitor after being added -

In the log provided in the screenshot, the part before I turn my screen on and off is everything up to the third "framebuffer created" messages

As you can see, initially, hyprlock configures a surface for the monitor (in the line before the framebuffer created message)

After I turn off and turn on the display (which is detected as unplugging and plugging it) - after the framebuffer created messages, you can see that it detects the display, but doesn't create a lock surface on it, causing a red screen
![20240302_003711](https://github.com/hyprwm/hyprlock/assets/84682255/f83a7df2-4846-4c59-a8e1-c298f8d5a8f6)

**Comment by tobimai** [comment]
Same issue when you use dmps to disable and then re-enable the screen

**Comment by vaxerski** [comment]
are you on git

**Comment by liraz747** [comment]
> are you on git

Nope, just tried it now
With the git version the issue is sort of gone, when I turn the monitor off and back on, I can see the lock screen, but the scaling is wrong

(Although... that version is completely unusable for me as I can't login at all and it keeps saying authentication failed :P, but I suppose that's a different issue already)

**Comment by vaxerski** [comment]
auth failed probably because you didn't `sudo cmake --install build` to install the pam file. Something I asked @alba4k to add a workaround for before @fufexan prematurely merged his MR.

**Comment by liraz747** [comment]
![20240302_172840](https://github.com/hyprwm/hyprlock/assets/84682255/8af78858-b55f-4749-bd23-2bccb30c7f18)
It just starts to sort of break after turning the display on and off again

**Comment by vaxerski** [comment]
that looks fun

**Comment by tobimai** [comment]
Using git works for me without any obvious issues. But I have 1x scaling on all screens

**Comment by Y0ngg4n** [comment]
Same issue here. But i have it every time.
