### ISSUE TITLE
Request: Shadows and labels text blurred outline

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/hyprlock#121]
The problem is, when using `screenshot` as background it is random, and ~white text on bright background looks... uh

I suppose it won't be too difficult for input-field widget, but what about pango labels? Is it even possible?

**Comment by vaxerski** [comment]
it is

**Comment by bvr-yr** [comment]
yeah i see, this [OBS Plugin](https://github.com/norihiro/obs-text-pthread) for example

**Comment by justinesmithies** [comment]
Shadows on labels would be a fantastic addition especially if you could set the shadow colour too.
It would save me duplicating labels one for text and one fake shadows with a slight offset.

**Comment by vaxerski** [comment]
done in a4dc596cb8b4e2f65247bd5f884ab9dbae100f1d

![20240305_20h27m10s](https://github.com/hyprwm/hyprlock/assets/43317083/697fa1a9-7c00-46dd-bc57-faaaba32bc68)

**Comment by vaskark** [comment]
I'm using updated hyprlock (git) and shadows are not working for me. But I'm on Ubuntu 23.10 and am only on Hyprland 0.24.1.

**Comment by vaxerski** [comment]
:skull:
