### ISSUE TITLE
Last update makes my authentication fail

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/hyprlock#122]
I am using the latest git version via the AUR on Arch Linux. Yesterday Hyprlock was working fine as in I could unlock my session but as of today authentication fails and I cannot get back in unless I reboot.
In the log I just see:

```
[LOG] Authenticating
[LOG] Authentication failed: Authentication failed
```
I know my password is correct and has not changed as I can obviously login to my system.

**Comment by bvr-yr** [comment]
are u also missing **/etc/pam.d/hyprlock** like in https://github.com/hyprwm/hyprlock/issues/118#issuecomment-1974778216 ?

if not, can u share content of **/etc/pam.d/login** ?

**Comment by justinesmithies** [comment]
Ok I see I'm missing `/etc/pam.d/hyprlock` looks like it's an issue with the AUR package `hyprlock-git`

My `/etc/pam.d/login` is as follows:

```
╭─justine@justine-laptop ~ 
╰> cat /etc/pam.d/login
#%PAM-1.0

auth       requisite    pam_nologin.so
auth       include      system-local-login
account    include      system-local-login
session    include      system-local-login
password   include      system-local-login
```

**Comment by bvr-yr** [comment]
that's strange cause `PKGBUILD` installs it
if you use yay, try cleanbuild it

**Comment by justinesmithies** [comment]
I'm using `paru` but I tried uninstalling `hyprlock-git` and reinstalling but still there is no `/etc/pam.d/hyprlock` ??

**Comment by justinesmithies** [comment]
Ok I've resolved my issue. For some reason I had to uninstall `hyprlock-git` then delete the folder and it's contents of `~/.cache/paru/clone/hyprlock-git` and then reinstalled and as if by magic the missing file was there and everything is back working again.
Thanks for the assistance.

**Comment by vaxerski** [comment]
paru is kinda cringe with rebuilding git packages from what I've seen. yay allows you to `cleanBuild`.

**Comment by mylinuxforwork** [comment]
Is the cleanbuild also required when using the AUR hyprlock package and not hyprlock-git?

**Comment by vaxerski** [comment]
hyprlock doesnt have the feature yet, only git

but when it drops, uhh probably not? I havent read their pkgbuild.

At any rate this bug wont happen again I added a workaround

**Comment by mylinuxforwork** [comment]
Thanks.
