### ISSUE TITLE
[BUG] Label is not updating without input-field

### ISSUE THREAD

**Issue by AdamchukAndrii** [hyprwm/hyprlock#134]
If input field is hidden - the label is not updating

My config

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    # dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    # outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    placeholder_text = Password # Text rendered in the input box when it's empty.
    hide_input = false
    # rounding = -1 # -1 means complete rounding (circle/oval)
    position = 0, -50
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = Noto Sans
    position = 0, 16
    halign = center
    valign = center
}

The clock stuck at the time of locking and changes seconds only when input is visible
system:
Arch
hyprlock installed with yay

**Comment by leon-erd** [comment]
For me the label not updating happens when I have external monitors attached and has nothing to do with the input field being visible or not. When I type something sometimes the labels get updated once or twice. Most of the time they start glitching.

**Comment by zakk4223** [comment]
I have three monitors and similar config for a clock label.

I notice that the time only updates on one of the displays. The others only update when I type.
I can't figure out if there's a pattern to which monitor updates.

**Comment by Andy3153** [comment]
Seconding this. Having the same issue. Running hyprland-git from AUR

**Comment by NoisyFlake** [comment]
Same here. Got three monitors always attached, but two are just displaying an image. The middle has all the labels and input fields, and the time only gets updated when typing.
