### ISSUE TITLE
Bug: `shadow_color` > 0 modifies whole color output

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/hyprlock#136]
![pinky](https://github.com/hyprwm/hyprlock/assets/130279855/a0196562-e597-4919-8675-cfbdc4a43250)

```ini
background {
    color = 0xff212121
}

label { #1
    color = 0xFFD4BE98
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(255,0,0)
    shadow_boost = 1.2
}

label { #2
    color = 0xFFD4BE98
    shadow_passes = 1
    shadow_size = 3
    shadow_color = rgb(0,0,255)
    shadow_boost = 1.2
}
```
same with `screenshot` and `.png`

**Comment by bvr-yr** [comment]
oh and maybe
```bash
hyprctl monitors -j | jaq '.[].currentFormat'
"XRGB8888"
```
can help

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/hyprlock/assets/43317083/4f3b9675-d0b8-4765-992c-4ac3d5e83100)

**Comment by vaxerski** [comment]
ah yes, I should've watched more captain disillusion.

Alpha premultiplication, gets me every time.
