### ISSUE TITLE
[REQ] Using a monitor's description for monitor value

### ISSUE THREAD

**Issue by matt1432** [hyprwm/hyprlock#137]
If I try to do this:
```
input-field {
  monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D
```

it won't actually put the input-field on that monitor.

This exact monitor value works on Hyprland

**Comment by vaxerski** [comment]
ye thats because this is not hyprland and its not impl'd yet xd

**Comment by matt1432** [comment]
fair enough lol, consider this a feature request then!
