### ISSUE TITLE
feat: allow hitting enter with empty password

### ISSUE THREAD

**Issue by herrwusel** [hyprwm/hyprlock#138]
With my pam set up, I use a hardware dongle to log into my account. Pressing enter was enough on swaylock to request authentication via dongle. So I would like to hit enter when hyprlock is active to request the hardware authentication module.

**Comment by hans-chrstn** [comment]
also having the same problem as im always used to pressing enter on lockscreen

**Comment by hans-chrstn** [comment]
fixed it by running an overlay through flakes. i seem to be running it on an older version. however, it now hangs whenever i close the lid of my laptop or when hypridle starts the timeout
