### ISSUE TITLE
[BUG] The process remains for a long time after unlocking

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#149]
`hyprlock` doesn't return for a while, even after unlocking (5 seconds?)

this issue ha pretty much always been there.

**Comment by PaideiaDilemma** [comment]
Yeah. But at that point everything is unlocked. So I am not sure if it is really a problem.
The main thread waits for the poll thread to bail out when that happens.

We could probably solve it by using ppoll and a signal to terminate it

**Comment by alba4k** [comment]
Not a big issue, sure, but annoying when trying to test

or, when using `pidof hyprlock || hyprlock` as lock command
