### ISSUE TITLE
cannot remove border radius of input

### ISSUE THREAD

**Issue by thomasabishop** [hyprwm/hyprlock#151]
I can't find any docs explaining how to remove the default border radius or adjust it. Have tried `outline_radius` and a few other variations but no dice. Is this possible?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#input-field

`rounding`

**Comment by thomasabishop** [comment]
What is the value for no radius. I have tried `0`, `1`, `none` to no avail. The docs state that the default is `-1` but no other possible value. Thanks.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/hyprlock/assets/43317083/67614e4b-f863-483b-b4c9-3448a3549569)

`rounding = 0` works for me. Make sure you're on -git.

**Comment by thomasabishop** [comment]
Thanks @vaxerski. Yeah think I need to use -git release.
