### ISSUE TITLE
hyprlock: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/hyprlock#153]
Since `Hyprlang` now uses `libhyprlang.so.2: /usr/lib/libhyprlang.so.2` I get the above error as `s0.1` no longer exists.

The error `hyprlock: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory`

I'm using the latest git versions of `Hyprlang` and `Hyprlock`

**Comment by justinesmithies** [comment]
I'm closing this as removing `hyprlock-git` from the paru cache and reinstalling fixed things re the recent so change.

**Comment by vaxerski** [comment]
release was API-compatible so a recompile is sufficient
