### ISSUE TITLE
Unlock command.

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/hyprlock#16]
There should be an unlock command to avoid red screen of death.
What I mean to say is in `swaylock`
if I do `killall -q -s SIGUSR1 swaylock` it unlocks it without giving the red screen of death.
I can add that to idle's `unlock_cmd` and then `loginctl unlock-session` should unlock it.

Makes it easier to unlock the device if connected to kdeconnect.
would be nice if something like `hyprlock unlock` is introduced or `killall -q -s <SIGNAL> hyprlock`

**Comment by niksingh710** [comment]
To be done.
- [ ] `inner_color` alpha value not working.
- [ ] option to align password input text to center. 
- [ ] addition of a way to unlock (so red screen of death)
- [ ] pam and source issues to be resolved.

**Comment by vaxerski** [comment]
pam is in a different issue iirc

**Comment by niksingh710** [comment]
> pam is in a different issue iirc

yeah, just added in the checkbox

**Comment by alba4k** [comment]
tbh instead of `hyprlock unlock` something that I can see being nice would be `hyprctl lock` and `hyprctl unlock`

It supports hyprpaper already, why limit it to that

**Comment by RoootTheFox** [comment]
wouldn't it make sense to just have it be an argument of `hyprlock`? afaik hyprlock doesn't require Hyprland, so some users may want to use hyprlock but not Hyprland, so for those people it'd be better to have it inside of the hyprlock binary.

**Comment by alba4k** [comment]
right, that does make sense, my bad

**Comment by niksingh710** [comment]
`hyprlock unlock` and alisa `hyprctl unlock -> hyprlock unlock`

**Comment by vaxerski** [comment]
SIGUSR1 is a simpler choice.

**Comment by alba4k** [comment]
Yeah that'd be nice
