### ISSUE TITLE
[REQ] Radial widget

### ISSUE THREAD

**Issue by qweered** [hyprwm/hyprlock#168]
Similar to https://github.com/mortie/swaylock-effects

**Comment by ItsDrike** [comment]
isn't this just what you get with `input-field:hide_input = true`? Or do you mean something else?

This is what i do:
```
input-field {
  size = 300, 250
  outline_thickness = 30
  outer_color = rgba(129, 162, 190, 85)
  inner_color = rgb(29, 31, 33)
  font_color = rgb(100, 100, 100)

  hide_input = true
  fade_on_empty = false
  placeholder_text = # Leave the text empty

  position = 0, 0
  halign = center
  valign = center
}
```

Which looks like this:
![image](https://github.com/hyprwm/hyprlock/assets/20902250/b9cbfec4-c34e-4a16-b257-4d4ff40a5b6b)

You even get the random segements highlighting as you type each character on the circle, just like in swaylock.

**Comment by qweered** [comment]
> isn't this just what you get with `input-field:hide_input = true`? Or do you mean something else?

Oh that's very nice! Does hyprlock have there ui states for error, checking password, etc?

**Comment by ItsDrike** [comment]
> Oh that's very nice! Does hyprlock have there ui states for error, checking password, etc?

You can use `fail_text`, `fail_transition`, `fail_color` and `check_color`. Quick example:

```
input-field {
  size = 300, 250
  rounding = -1
  outline_thickness = 30
  outer_color = rgba(129, 162, 190, 85)
  inner_color = rgb(29, 31, 33)
  font_color = rgb(100, 100, 100)

  check_color = rgb(204, -136, 34)  # override outer_color while checking the pw (could take a while sometimes - pam lockouts)
  fail_color = rgb(204, 34, 34)  # override outer_color and fail message color if auth failed
  fail_transition = 500 # transition time in ms between normal outer_color and fail_color
  fail_text = <span size='14pt' foreground='##999'><i>Logged <span foreground='##FFA500'>$ATTEMPTS</span> failure(s): <span foreground='##ff2222'>$FAIL</span></i></span>

  hide_input = true
  fade_on_empty = false
  placeholder_text = ‍# There is a zero-width joiner character here (U+200D) since fail_text doesn't work with this empty

  position = 0, 0
  halign = center
  valign = center
}
```

Though this is all documented in the wiki, which you should probably read.

I assume this can be closed now.
