### ISSUE TITLE
pam_conversation not being handled properly

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/hyprlock#170]
I have been wishing for this program for a while now and was happy to discover it. It doesn't work on my setup where I use u2f authentication to login, which is supported by PAM, so I read through the code to see what is up, and I noticed that the pam_conversation part is not really handled well. Apparently the current solution is to spam PAM with the password until it unlock instead of having a proper conversation.

Actually, there already exists a default function called misc_conv to use as pam_conversation. To use it, we just need to specify STDIN_FILENO and STDOUT_FILENO in the thread and send it application data through a pipe.

This however requires to also change the way we display the conversation. Because the input field may not be used exclusively for the password anymore.

To figure this out, I already procrastinated a lot to read about PAM, so I'll be glad to make use of this knowledge in a PR. However, I don't really know modern C++ but rather pure C, so I may need assistance to add the "++" to my code.
It would also be nice to receive some guidance on how to utilize the input field. And how to echo messages from PAM if wanted.

**Comment by vaxerski** [comment]
feel free to make a MR I review those anyways

**Comment by PaideiaDilemma** [comment]
I naively implemented conv function by reading through the pam documentation as well and by checking how other applications do it.

Currently when the message type is `PAM_PROMPT_XXXX`, we just give pam the password. The message types that are not implemented are `PAM_RADIO_TYPE` and `PAM_BINARY_PROMPT`. Of course the pam configuration could prompt us for something other than the main password (e.g. 2fa). In that case we would need to keep the `handle` and get some more input from the user. That is the hard part. But piping the user input into a filedescriptor to use it with misc_conv is probably not the best approach as it is not that complicated to handle it in our own conv. (See https://github.com/linux-pam/linux-pam/blob/master/libpam_misc/misc_conv.c#L379)

But I think it shouldn't be too hard to use the placeholder text as the prompt message and get more input from the use via the existing input method.

**Comment by Mikilio** [comment]
Firstly, thanks for being on board.

When doing authentications with PAM it can occur that there will be multiple prompts and answers. This is especially true with 2FA. Since the whole `pam_conversation` needs to occur on the single call of `pam_start` this means we need to implement a way for the `pam_conversation` to block and wait for user interaction. All this is already perfectly implemented in misc_conv, and it is also already included in the project.

Could you help me understand what advantage there is to implement our own `pam_conversation`?

As for the input method, I will implement it as you suggested but, I have the suspicion that it's going to look rather ugly visually. So maybe it's time to think about an additional widget that specifically shows the message that tells the user what PAM is expecting as input.

**Comment by Mikilio** [comment]
I have given it some thought and looked specifically at [login](https://github.com/util-linux/util-linux/blob/master/login-utils/login.c) and [greetd](https://sr.ht/~kennylevinsen/greetd/) which are both a big example of each approach. It probably doesn't matter too much but, since I personally enjoy hyprland for its flexibility and "rice-ability" it's probably smarter to take the greetd approach, which to summarize is:

-  make a data structure/ object for a conversation handler that has methods for each msg_style, takes in a msg and returns a response.
- the handler owns a UNIX socket, so it can have arbitrary conversations over it with GUI elements
- pass the handler to the pam_conversation via app_ptr

**Comment by Mikilio** [comment]
Would be nice if @PaideiaDilemma could drop some comments until next weekend. I don't usually code C++, so I appreciate any advice.
