### ISSUE TITLE
[REQ] Unlock hyprlock from terminal

### ISSUE THREAD

**Issue by Amir1453** [hyprwm/hyprlock#176]
Hello, since at the moment `hyprlock` crashes regulary it makes it quite hard to use. The ability to switch to a tty and then unlock `hyprlock` would be very useful. I tried using `pkill` but that just results in the red screen. Maybe a `killall` flag to unlock the lock screen would be easier to make.

**Comment by PaideiaDilemma** [comment]
Already exists. Use SIGUSR1. So for example `pkill -USR1 hyprlock`.

Why does hyprlock crash for you? An existing issue or something else?

**Comment by Amir1453** [comment]
Alright, thank you. Maybe documenting this or adding it as `hyprlock --unlock` would be useful to other people.

I mostly needed this feature for the other common bugs that were quickly fixed. For now hyprlock sometimes doesn't let me type anything after waking from a hibernation, but I suppose I should open that as a separate issue.

**Comment by Amir1453** [comment]
Sure, forgot to close the issue.

**Comment by izmyname** [comment]
> Already exists. Use SIGUSR1. So for example `pkill -USR1 hyprlock`.
> 
> Why does hyprlock crash for you? An existing issue or something else?

USR1 doesn't work for me, for some reason. I use hyprlock with hypridle. The problem occur quite rarely, but if it does - only reboot helps.
