### ISSUE TITLE
Input typing indicator widget

### ISSUE THREAD

**Issue by CIAvash** [hyprwm/hyprlock#18]
While there is an `input-field` widget, it can reveal the number of characters in the password.

So, it would be nice to have some kind of typing indicator to show the user that `hyprlock` is getting the input.

**Comment by vaxerski** [comment]
suggestions for visualizing?

**Comment by CIAvash** [comment]
Maybe not a good idea, but how about combining all the examples I mentioned? 🤔

Something like this: When a key is entered, a prompt is shown and everything else is blurred, the prompt can be a (random or fixed) set of underscores like xsecurelock or maybe empty circles(or some other shape?) and when keys are pressed, a prompt character from the set is randomly chosen and the color of underscores or the fill color of circles are randomly changed.

**Comment by vaxerski** [comment]
I have a better idea.

**Comment by vaxerski** [comment]
6ff808cebf4db80f69b786637c3a3b21e0dc0cdd hows that

**Comment by CIAvash** [comment]
Nice and very efficient!
