### ISSUE TITLE
[REQ] Support specifying font-size for `placeholder_text`/`fail_text`

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/hyprlock#181]
Currently, it seems that there's no way to set the font-size of placeholder_text / fail_text in `input-field`. Instead, it seems to just be based off of the height of the input-field specified in `size`.

This might be a good choice for people who don't use `hide_input`, however most people who have `hide_input = false` will likely want to use a pretty big height in the `size`. That then leads to the text being really big, which doesn't look good.

It'd be nice to have a way to override this behavior and manually specify a font-size for this text, leaving the height-based calculation only as a default fallback.

**Comment by bvr-yr** [comment]
https://docs.gtk.org/Pango/pango_markup.html#the-span-attributes

**Comment by ItsDrike** [comment]
Fair, but why do labels have a `font_size` attribute then? I suppose it's just for convenience, perhaps the same convenience would be nice to have here too?

**Comment by vaxerski** [comment]
no, pango markup
