### ISSUE TITLE
[REQ] Turn screen off after if idle for certain duration

### ISSUE THREAD

**Issue by KAGEYAM4** [hyprwm/hyprlock#183]
Edit3 - feel free to close the issue, as implementing this will lead to code redundancy as idling-timer is already implemented in hypridle. 

------

Should this be officially supported inside Hyprlock? Or using `listener` inside hypridle is preffered?

Using hypridle this is possible by adding another listener and using conditional ->
```
listener {
    timeout = 60 
    on-timeout = pgrep hyprlock && hyprctl dispatch dpms off
    on-resume =  hyprctl dispatch dmps on
}
```

Sources->
https://github.com/hyprwm/hypridle/issues/16
https://github.com/swaywm/swayidle/issues/159

- ~~Edit- Sometime, `hyprlock` process dosen't die, and the command `pgrep hyprlock && hyprctl dispatch dpms off` turns off the screen even though lockScreen is not showing.~~
- ~~Edit2 - if hyprlock is active, and i move the cursor, the idle timeout resets to 0, and if idle timeout reaches 60, a new hyprlock instance starts up. This way one can end up with n number of hyprlock instances. Solution - ` lock_cmd = prep hyprlock || hyprlock `~~ -> This needs to be documentated.

**Comment by andresilva** [comment]
https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/

At the end of this page there's a full example of integration with hyprlock and dealing with dpms in Hyprland.
