### ISSUE TITLE
`$TIME` of does not update if `input-field` is hidden

### ISSUE THREAD

**Issue by abhinandanudupa** [hyprwm/hyprlock#187]
From my observation I find that the time from `label { text = $TIME}` does not update itself if the `input-filed`'s `fade_on_empty = true` is set to `true`. It updates to the current time once I start typing the password. The problem disappears if we toggle `fade_on_empty` to false. 

If it matters, I have two labels.

Version: 0.1.0-2 (`hyprlock` and not `hyprlock-git`)
OS: Arch
Hyprland: 0.1.0-2 (`hyprland` and not `hyprland-git`)

**Comment by vaxerski** [comment]
yea 0.1.0 is very outdated, this has been fixed in git
