### ISSUE TITLE
Uses deprecated method to obtain username (doesn't work in some cases)

### ISSUE THREAD

**Issue by kcirick** [hyprwm/hyprlock#203]
I tried using hyprlock but couldn't unlock (authentication error). After looking at the log file, I see the entries:

`[ERR] Error in formatString, username null. Errno:` 

Invesigating further, this is where the issue lies:
https://github.com/hyprwm/hyprlock/blob/2ae79757d5e5c48de2f4284992a6bfa265853a2d/src/renderer/widgets/IWidget.cpp#L85

Indeed, getlogin() on my machine returns (null). I found the following which seems to indicate this is a deprecated way to obtain a login name:
https://stackoverflow.com/a/4785195

Using `getpwuid(getuid())` I confirm it returns the correct username. Here is the swaylock implementation:
https://github.com/swaywm/swaylock/blob/f9ce3f193bc2f035790372b550547686075f4923/pam.c#L74

I think hyprlock should use this implementation?

**Comment by kcirick** [comment]
Attaching a patch that makes it work for my system in hyprlock release version 0.2.0:

[hyprlock-0.2.0-username_fix-1.patch](https://github.com/hyprwm/hyprlock/files/14636920/hyprlock-0.2.0-username_fix-1.patch)

**Comment by vaxerski** [comment]
was supposed to be fixed in #104 but that got abandoned. Feel free to make a MR superseding that one

**Comment by kcirick** [comment]
Looked at that pull, but IMO there's no need to do anything fancy like that. I was also unsure what the outstanding conflict was on that pull.

Forgive me for being a n00b at git, I'll have to learn how to do PR/MR. Do I make a new Pull request?

**Comment by vaxerski** [comment]
make a branch, commit your diff there, come back to this repo, click pull requests, new, and the rest is intuitive

**Comment by PartyWumpus** [comment]
#204 has been merged, this issue should probably be closed?
