### ISSUE TITLE
[REQ] Make hyprlock ignore monitor's scaling value in monitor.conf

### ISSUE THREAD

**Issue by KyoukaHeiwa** [hyprwm/hyprlock#207]
[LOG] Configuring surface for logical [Vector2D: x: 1500, y: 1000] and pixel [Vector2D: x: 1500, y: 1000]
This is what I get with my monitor set to a scale of 2 and I'd rather prefer the zoomed out look when scaling is set to 1, giving me this:
[LOG] Configuring surface for logical [Vector2D: x: 3000, y: 2000] and pixel [Vector2D: x: 3000, y: 2000]
If there is a way, please let me know, thanks!

**Comment by vaxerski** [comment]
that's a hyprland bug that has been fixed eons ago, update
