### ISSUE TITLE
[REQ] Ignore grace period when system suspends

### ISSUE THREAD

**Issue by deivi98** [hyprwm/hyprlock#208]
Hi there,

Is there any way to ignore grace period when system suspends?

I like to have grace period for a couple minutes while I am back to my laptop. However if grace period is big enough (e.g 5 min), even if you close your laptop's lid (system suspends) and open it again, grace period persists.

This is not a bug, but I would like to change it though. To me, makes sense Hyprlock always ask for authentication after system resumes.

Love this project, great stuff.

**Comment by vaxerski** [comment]
I don't think this is doable as hyprlock has no idea when system suspends. However, if you use hypridle, you can launch it with `--immediate` when suspending and it will ignore the grace period.

**Comment by deivi98** [comment]
Thanks! It'll work for me
