### ISSUE TITLE
[REQ] add check if pam module already exists

### ISSUE THREAD

**Issue by DiskyToy** [hyprwm/hyprlock#209]
Problem:
I do not want to use the default `login` chain, so I edited my `/etc/pam.d/hyprlock` to meet my needs.
When updating or reinstalling `hyprlock`, the file gets overwritten with its default values.

Possible solution:
Add a check (on install) if the file exists, else create it.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprlock/files/14696957/patch.txt)
my bad, fixed.

**Comment by vaxerski** [comment]
this has been reverted in d9a6229434fba475ea42b634ee2f03919236798d

however you can now set your own pam path, so now just make another file and specify it in the config
