### ISSUE TITLE
[BUG]: Resource background: invalid (out of memory)

### ISSUE THREAD

**Issue by DataHearth** [hyprwm/hyprlock#221]
Hello there!

I'm configuring `hyprlock` on NixOS with `hyprland` configured through `home-manager`'s module. 
Upon configuring, I tried to set a background image (PNG as specified in the documentation), but `hyprlock` seems to have a problem loading it. As you can see in the logs (provided at the bottom), it cannot load the image for some reasons returns an error `invalid (out of memory)` without any detailed explanation. I've tried the verbose mode, the error is exactly the same. 
I'm running it with the provided nix flake and its attached `homeManagerModules`. 

Commit : `230f8aadb5123dd7388143aa4f2a5a881a9c0a41`
Configuration: https://gist.github.com/DataHearth/4b6ebf9f4368d993ea25a1d5c7f5a70d
Logs: https://gist.github.com/DataHearth/2e12159e30c5c3400e1a59b5c6489bc3

Might be a bug ?

Thanks for any help!

Edit: Also happens with the latest tag `v0.2.0`

**Comment by vaxerski** [comment]
does it work with a different png?

**Comment by Amir1453** [comment]
Pretty sure this happens when the image resolution (thus the size) is bigger than a certain threshold.

**Comment by vaxerski** [comment]
yea sounds reasonable, this is an error from cairo after all, not us

**Comment by DataHearth** [comment]
@vaxerski Hey! Yup, I've tried 2 different images. Same each time.

**Comment by khaneliman** [comment]
I'm getting this error with a 114KB image... lol

**Comment by DataHearth** [comment]
It was indeed the problem! IDK why I didn't check the file payload to check if it was really a PNG... Thanks for tips and solution @khaneliman

**Comment by musicfunfan** [comment]
I still the same problem on archlinux. I use the pckage from the arch repo. And i get the error out of memory on the background image option. On any photo i try big or small.

**Comment by khaneliman** [comment]
> I still the same problem on archlinux. I use the pckage from the arch repo. And i get the error out of memory on the background image option. On any photo i try big or small.

Is it a -git version that tracks latest commits or is it tracking a previous release?

**Comment by musicfunfan** [comment]
There is also a git package on AUR. But its older i think. I did try it. But its not working. 
```bash
aur/hyprlock-git 0.2.0.r20.g2448774d-1 (+18 1.66) 
    Hyprland's GPU-accelerated screen locking utility
```

**Comment by musicfunfan** [comment]
I thing archrepo is one version behind this is may be the problem. So the only option is to build it ?
