### ISSUE TITLE
Make Ctrl+u clear password

### ISSUE THREAD

**Issue by noahgitsham** [hyprwm/hyprlock#222]
As it does in the terminal password entry.

_@alba4k  in https://github.com/hyprwm/hyprlock/issues/19#issuecomment-1955216958_ also suggested Ctrl+Backspace to do the same, which I wouldn't personally use, as this is not a behaviour found in terminals, though it seems reasonable to me.

I would make a PR, though it looks like the current input system can't handle key combinations, and I'm unsure how that would be best implemented.

Thanks

**Comment by vaxerski** [comment]
you can read current mod state I guess

**Comment by alba4k** [comment]
why ctrl u and not, idk, ctrl d?

**Comment by KAGEYAM4** [comment]
> I would make a PR, though it looks like the current input system can't handle key combinations, and I'm unsure how that would be best implemented.

not sure it would help, but on password prompt, `Ctrl+u` does seem to get registered ( can be seen by color box appering, also if you continue to enter correct password, it will be incorrect ).

**Comment by noahgitsham** [comment]
> `Ctrl+u` does seem to get registered
It currently ignores the modifier key, typing a 'u' instead.
