### ISSUE TITLE
Hyprlock not responding after suspending

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/hyprlock#229]
When i suspend the laptop for a period of time, once i wake it up, i type the passwd but it seems like hyprlock doesnt react to it, its like frozen, sometimes it may take 15 seconds to start reacting to keyboard imput, but other times, i just need to suspend it again, and re-wake the laptop in order to start writing the passwd. Idk what may be the problem, some1 help

**Comment by PaideiaDilemma** [comment]
Douplicate of #101
