### ISSUE TITLE
[Quetion] Transparent image as backround. 

### ISSUE THREAD

**Issue by musicfunfan** [hyprwm/hyprlock#233]
This is not an issue. I just want to know if its possible to have a transparent image (with alpha channel) as lock screen? This way, i can have my desktop in the background and also in the same time i can have a title in the middle of the screen that will say something like "Locked" or something like that. 

If this is possible it will be nice with some dimming and maybe some blur to the background.

**Comment by vaxerski** [comment]
yes you can but your actual desktop will just shine through

**Comment by musicfunfan** [comment]
So i create a png with alpha channel and is working... Now how can i blur the background aka (My Desktop) ? 

Is this is possible ?

**Comment by musicfunfan** [comment]
I found ``blur_passes`` But i want to blur the Background not the Text... 

🤔.

**Comment by bvr-yr** [comment]
that will not work, as a workaround you can toggle empty special workspace with enabled blur (on Hyprland)

**Comment by musicfunfan** [comment]
So i use ``swaylock-effects-git``  now. Its works fine for what i do. I have it lock after 15 min and show clock and the backround is behind the clock is nice. 

I use a script for wallpaper and this script saves to a file the path of the current wallpaper and i have another script that pass this string to swaylock so. 

The code of all this is in my [GitLab repo](https://gitlab.com/musicfunfan/my_scripts_ultimate). 

So i will close this issue because for me at list i have a solution.
