### ISSUE TITLE
[BUG] Crash on Nixos using home-manager module

### ISSUE THREAD

**Issue by BenCarmichael01** [hyprwm/hyprlock#239]
Using hyprlock installed directly from the home manager module, it crashes on startup (red screen) with the below error:

```
[TRACE] [sc] DMABUF format DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions    
DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions
DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions    
DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions    
DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions    
DRI driver not from this Mesa build ('24.0.3' vs '23.3.5')
failed to bind extensions    
```

However when overriding the hyprlock package to V0.2.0 in nixpkgs-unstable by setting `programs.hyprlock.package = pkgs.hyprlock`, there is no crash and hyprlock works normally. 
I can't seem to bisect this issue as building from source doesn't seem to work at all for me, even on v0.2.0. Seems unrelated though. 

I saw #85 but since I'm on Nixos i'm not sure how this build vs runtime mismatch could happen.
Any ideas?

**Comment by fufexan** [comment]
The mesa in your system's nixpkgs vs the mesa in hyprlock's nixpkgs is different, thus it doesn't work.

I'll update the nixpkgs version in this flake and it should then work again.
