### ISSUE TITLE
lock and hibernate

### ISSUE THREAD

**Issue by mohammedbilalns** [hyprwm/hyprlock#240]
Is there a way to lock and hibernate? I tried `hyprlock && systemctl hibernate` but hibernation only occurs after unlocking.

**Comment by deepaknegilachu** [comment]
# lock system before suspend (lid close, systemctl supend and loginctl suspend)
general {
  before_sleep_cmd = pgrep hyprlock || hyprlock
}
# lock after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = hyprlock & dbus-send --print-reply --dest=org.mpris.MediaPlayer2.cmus /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
}
# suspend after 1 minute further .
listener {
    timeout = 360
    on-timeout = loginctl suspend || systemctl suspend
}

**Comment by mohammedbilalns** [comment]
"Thanks, it fixed it. I was using HyperLock without HyperIdle before."

**Comment by mohammedbilalns** [comment]
How can I manually lock and hibernate together  by running a script?

**Comment by zefr0x** [comment]
> I tried `hyprlock && systemctl hibernate`

This will wait for `hyprlock` to finish before running `systemctl hibernate`. You should use `hyprlock & systemctl hibernate`
