### ISSUE TITLE
Suspend starts during locking animation and finishes after resuming

### ISSUE THREAD

**Issue by 31JSON** [hyprwm/hyprlock#241]
I've noticed that when issuing `systemctl suspend` either via hyperidle or manually, suspend consistently takes over about halfway through the locking animation, which leaves the desktop partially visible. Upon resume, the desktop is again partially visible as the animation is finishing. Is there a way to prevent this from happening?

Arch Linux
linux 6.7.9.arch1-1
hyprland 0.37.1-2
hyprlock 0.2.0-2
GPU: AMD RX 580

**Comment by vaxerski** [comment]
disable the animation, lol
