### ISSUE TITLE
Ignore enter keyboboard wvwnt while the input field is hidden

### ISSUE THREAD

**Issue by SquareWinter68** [hyprwm/hyprlock#242]
Glossing over the cpp source this should be an easy fix, by just not responding to the enter keyboard event wile the input field is hidden. Alternatively hitting enter could bring up the input field. The way it works now is, that by hitting enter authentication starts even though the input field was hidden, and this freezes it up until the authentication fails. It is a minor issue with a presumably easy fix.

**Comment by vaxerski** [comment]
on purpose. With fingerprint readers, hw keys etc you dont enter a password. Can be configurable tho, feel free to mr

**Comment by SquareWinter68** [comment]
Thanks for clarifying, might just do it as soon as I get the chance, cheers and extremely good work with Hyprland i might add .
