### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by hans-chrstn** [hyprwm/hyprlock#243]
Using the image widget example from the [wiki](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#image):  

[ERR] Config has errors:
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 22: config option <image:monitor> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 23: config option <image:path> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 24: config option <image:size> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 25: config option <image:rounding> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 26: config option <image:border_size> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 27: config option <image:border_color> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 29: config option <image:position> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 30: config option <image:halign> does not exist.
Config error in file /nix/store/5m8mh9gzp7d5pvhfa7i0cv4gd4mx4l7j-hm_config/hyprlock.conf at line 31: config option <image:valign> does not exist.
Proceeding ignoring faulty entries

**Comment by zefr0x** [comment]
This option has not been released yet.

Please refer to your current version's wiki. For example: https://wiki.hyprland.org/0.37.0/hypr-ecosystem/hyprlock/

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/hyprlock/assets/43317083/6f9aea9d-5631-4514-ae17-62b421a30064)
rtfm moment

**Comment by hans-chrstn** [comment]
ah, mb. i didn't know there were separate branches on the wiki on the top left
