### ISSUE TITLE
Error parsing image widget in config file

### ISSUE THREAD

**Issue by JassonCordones** [hyprwm/hyprlock#246]
I'm trying to config hyperlock on my machine and everything appears to be right except for the image widget and the input-field widget swap_font color option. 

## Output:
> $ hyprlock
> [ERR] Config has errors:
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 6: config option <image:monitor> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 7: config option <image:path> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 8: config option <image:size> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 9: config option <image:rounding> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 10: config option <image:border_size> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 11: config option <image:border_color> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 12: config option <image:rotate> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 14: config option <image:position> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 15: config option <image:halign> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 16: config option <image:valign> does not exist.
> Config error in file /home/user/.config/hypr/hyprlock.conf at line 58: config option <input-field:swap_font_color> does not exist.
> Proceeding ignoring faulty entries

## Config file

general {
hide_cursor = false
}

image {
monitor =
path = /home/user/Pictures/pfp/images.png
size = 150 #lesser side if not 1:1 ratio
rounding = -1 #negative values mean circle
border_size = 4
border_color = rgb(221, 221, 221)
rotate = 0 # degrees, counter-clockwise
position = 0, 200
halign = center
valign = center
}

background {
monitor =
path = /home/user/Pictures/interlude_5.png   # only png supported for now
color = rgba(25, 20, 20, 1.0)

#all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
blur_passes = 0 #0 disables blurring
blur_size = 7
noise = 0.0117
contrast = 0.8916
brightness = 0.8172
vibrancy = 0.1696
vibrancy_darkness = 0.0
}

input-field {
monitor =
size = 200, 35
outline_thickness = 2
dots_size = 0.2 #Scale of input-field height, 0.2 - 0.8
dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
dots_center = false
dots_rounding = -1 #-1 default circle, -2 follow input-field rounding
outer_color = rgb(151515)
inner_color = rgb(255, 255, 255)
font_color = rgb(10, 10, 10)
fade_on_empty = true
fade_timeout = 1000 #Milliseconds before fade_on_empty is triggered.
placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
hide_input = false
rounding = 15 #-1 means complete rounding (circle/oval)
check_color = rgb(204, 136, 34)
fail_color = rgb(204, 34, 34) #if authentication failed, changes outer_color and fail message color
fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
fail_transition = 300 #transition time in ms between normal outer_color and fail_color
capslock_color = -1
numlock_color = -1
bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
invert_numlock = false #change color if numlock is off
swap_font_color = true #see below

position = 0, -20
halign = center
valign = center
}

label {
monitor =
text = Hi there, $USER
color = rgba(200, 200, 200, 1.0)
font_size = 25
font_family = Noto Sans

position = 0, 80
halign = center
valign = center
}

**Comment by Ligthiago** [comment]
See https://github.com/hyprwm/hyprlock/issues/243
