### ISSUE TITLE
[Feature] Clear input shortcut

### ISSUE THREAD

**Issue by max-ishere** [hyprwm/hyprlock#252]
Swaylock uses <kbd>Ctrl</kbd> + <kbd>C</kbd> to clear the password field. Would be nice if Hyprlock did the same or had a config line for it. Special character sequences like <kbd>Ctrl</kbd> + <kbd>C</kbd> aren't accepted by the common utils like mkpasswd and GUIs anyway so I think its ok to use.

- [ ] Add C-u clear input shortcut to hyprwiki

**Comment by zspher** [comment]
`ctrl` + `u` works

**Comment by max-ishere** [comment]
I dont remember seeing that in the docs.

**Comment by max-ishere** [comment]
- [ ] Add `C-u` clear input shortcut to hyprwiki

And we can close this one.
