### ISSUE TITLE
[Feature] Support parallel unlocking with fingerprint and password

### ISSUE THREAD

**Issue by Jackaed** [hyprwm/hyprlock#258]
The only thing I've seen that supports this correctly so far is GDM, which runs 2 PAM sessions in parallel, one for fingerprint, one for password. This makes the whole "press enter to trigger the prompt" song and dance unnecessary.

I'm unsure of how this actually works in terms of implementation, but only that it is possible (since GDM can do it).

Would be very nice if Hyprlock could support it.

**Comment by PaideiaDilemma** [comment]
Running two pam conversations in parallel sound weird xD.

You could check out https://github.com/hyprwm/hyprlock/pull/205.
There is a guy who uses `pam-fprint-grosshack` to make it work.

**Comment by Jackaed** [comment]
`pam-fprint-grosshack` is called that for a reason - PAM is strictly a serial authentication mechanism.

The correct way of doing parallel authentication is through two PAM sessions.

**Comment by PaideiaDilemma** [comment]
Idk if there is a correct way of doing parallel authentication xD

You could get two pam sessions by running a script together with hyprlock that then sends `SIGUSR1` to unlock hyprlock I guess.

**Comment by discapes** [comment]
presenting ~/.local/bin/mylock
```sh
#!/bin/sh
set -euo pipefail
(
until fprintd-verify -f right-ring-finger; do
    echo "Failed to verify fingerprint at $(date)" | systemd-cat
done
echo "Unlocked at $(date)" | systemd-cat
pkill -USR1 hyprlock
) &
exec hyprlock
```

**Comment by Jackaed** [comment]
I mean as much as this kinda sucks as a way of doing things it does work lmao. I'm not exactly convinced it's secure though.

**Comment by Jackaed** [comment]
This kinda works ish? It's pretty prone to causing just a dangling `fprintd-verify`, say if you authenticate with a password instead, which will make your fingerprint sensor unusable until you kill that task. I wouldn't reccomend it.

**Comment by discapes** [comment]
@Jackaed good observation, I don't really use fprintd for anything else :smile:. To fix the dangling fprint-verify, remove the `exec` and add these two lines:
```bash
kill $(jobs -p)
pkill fprintd-verify
```

**Comment by Jackaed** [comment]
Oh I just realised, this code REALLY doesn't work, since fprintd-verify still returns on a no-match, just with different output.

**Comment by discapes** [comment]
That's why there's the until loop
https://linuxize.com/post/bash-until-loop/

**Comment by Jackaed** [comment]
No but that until loop still breaks if an incorrect finger is used, as fprint still returns with a non-zero exit code. You can fix it by adding `| grep "verify-match"` to the condition.

**Comment by discapes** [comment]
In bash, if the exit code is non-zero, it usually means a failure.
fprintd-verify also works like this and returns 0 for success, and 1 for failure.
```
❯ fprintd-verify -f right-ring-finger
Using device /net/reactivated/Fprint/Device/0
Listing enrolled fingers:
 - #0: right-ring-finger
Verify started!
Verifying: right-ring-finger
Verify result: verify-match (done)                                              /1.1s
❯ echo $?
0                                                                               /0.0s
❯ fprintd-verify -f right-ring-finger
Using device /net/reactivated/Fprint/Device/0
Listing enrolled fingers:
 - #0: right-ring-finger
Verify started!
Verifying: right-ring-finger
Verify result: verify-no-match (done)                                           /2.0s
❯ echo $?
1
```
The until loop works such that it runs the command until the exit code is 0.

**Comment by discapes** [comment]
You should've tested it

**Comment by Jackaed** [comment]
My fprintd doesn't behave this way - I get an exit code of 0 on a match or on a non-match. Not sure why this is different on my machine.

I'm on nixos with nixpkgs unstable, what system are you running?

**Comment by discapes** [comment]
Interesting if it behaves that way. I'm using fprintd-1.94.2-8.fc39.x86_64 from Fedora. Also, I'm aware the script is a bit of a hack and I'm not forcing anyone to use it. I still don't see any major problems though, since according to the rules of bash it is impossible to unlock the computer without fprintd-verify returning 0.

I'd like to know how it "behaves weirdly" with sleep, since usually sleeping is completely transparent to processes.

**Comment by Jackaed** [comment]
@discapes I think it's more or less working as intended now - I'm now using the script with the modifications for my distro (specifically adding the grep) and it seems to work fine with sleep. 

In terms of not making it wait for fingerprint, if you're using the fprintd-verify script you can remove the fprint pam module and it should allow you to enter a password and have it work correctly, or let you use your fingerprint and have that work correctly.

I still think this should be implemented inside of hyprlock, as this still is a bit of a hack and requires a decent amount of setup, but for now this is fine.

**Comment by niksingh710** [comment]
@Jackaed can you share the method you are using or the script?

**Comment by Jackaed** [comment]
Currently using what I've modified from what @discapes sent

```sh
#!/bin/sh
set -euo pipefail
if [ -f /tmp/locked ] ; then exit ; fi
touch /tmp/locked
(
until fprintd-verify | grep "verify-match"; do
    echo "Failed to verify fingerprint at $(date)"
done
echo "Unlocked at $(date)" | systemd-cat
pkill -USR1 hyprlock
) &
hyprlock
rm /tmp/locked
kill $(jobs -p)
pkill fprintd-verify
```

The `/tmp/locked` stuff is just to ensure that you don't end up with multiple instances of hyprlock going at a given time. Use this at your own risk, I'm not responsible for anything that happens as this being potentially insecure.

**Comment by niksingh710** [comment]
@Jackaed for me `pkill -USR1 hyprlock` is never getting executed i even tried it with `grep verify-no-match` to check if it unlocks even if the fingerprint is not verifying but no luck.
only getting it unlocked by password input.

**Comment by Jackaed** [comment]
sorry this is impossible for me to debug when it's not my own system. make sure that `pkill` works as intended and that your `fprintd-verify` gives the output required.

**Comment by b4shful** [comment]
Came across this issue and wanted to ask if the situation has changed at all? I've been using pam-fprint-grosshack and it's not all that reliable (sometimes it works, sometimes I have to press enter and then wait for JUST the right amount of time (but not too early, or not too late?!?!).

**Comment by winkelnp** [comment]
I found a workaround that seems to work for me on the equivalent swaylock issue: https://github.com/swaywm/swaylock/issues/61#issuecomment-965175390

you essentially add
```
auth    sufficient      pam_unix.so       try_first_pass likeauth nullok
auth    sufficient      pam_fprintd.so
```
to the top of your `/etc/pam.d/hyprlock` file
I'm not sure if this adds any security issues, but it works a charm for me so far…

**Comment by baykalokandemir** [comment]
> I found a workaround that seems to work for me on the equivalent swaylock issue: [swaywm/swaylock#61 (comment)](https://github.com/swaywm/swaylock/issues/61#issuecomment-965175390)
> 
> you essentially add
> 
> ```
> auth    sufficient      pam_unix.so       try_first_pass likeauth nullok
> auth    sufficient      pam_fprintd.so
> ```
> 
> to the top of your `/etc/pam.d/hyprlock` file I'm not sure if this adds any security issues, but it works a charm for me so far… (you do however need to disable `ignore-empty-input` in your `hyprlock.conf` and entering a wrong password just fails silently)

This seems to work, ish? Unless i enter a wrong password in advance, i can't seem to trigger it to unlock. Works fine after wrong password though.

**Comment by winkelnp** [comment]
> > I found a workaround that seems to work for me on the equivalent swaylock issue: [swaywm/swaylock#61 (comment)](https://github.com/swaywm/swaylock/issues/61#issuecomment-965175390)
> > you essentially add
> > ```
> > auth    sufficient      pam_unix.so       try_first_pass likeauth nullok
> > auth    sufficient      pam_fprintd.so
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the top of your `/etc/pam.d/hyprlock` file I'm not sure if this adds any security issues, but it works a charm for me so far… (you do however need to disable `ignore-empty-input` in your `hyprlock.conf` and entering a wrong password just fails silently)
> 
> This seems to work, ish? Unless i enter a wrong password in advance, i can't seem to trigger it to unlock. Works fine after wrong password though.

You still need to press enter (on empty input) to trigger pam

**Comment by b4shful** [comment]
@Jackaed yeah for sure - also I have a feeling that pam-fprint-grosshack may have grossed its last hack - or maybe not, but it did stop working completely on me today (some dbus error, could be a me problem, but pam_fprintd works fine). So it's definitely overdue.

**Comment by enesbala5** [comment]
I am new to the Linux space - is this really that difficult to implement to Hyprlock directly?

Why should the user have to configure something like this - which is basic UX. Half the time my fingerprint doesn't work. This is not a small "annoyance". It's actually unusable right now.

**Comment by PaideiaDilemma** [comment]
Fprintd provides a dbus API, which could be used by hyprlock. That would probably work a lot better than the pam module.

Besides dbus, AFAIK there are quite a few hassles implementing it.

But yeah fingerprint support on linux is bad. I think it can be blamed on PAM and windows only fp devices. The fp sensor on my laptop does not have a working fprint driver, so I will likely not dive into this.

**Comment by enesbala5** [comment]
Is there any alternative right now to Hyprlock - which can be used along Hyprland - that doesn't have this problem?

**Comment by enesbala5** [comment]
> > Is there any alternative right now to Hyprlock - which can be used along Hyprland - that doesn't have this problem?
> 
> If I understand the question correctly, https://github.com/SL-RU/swaylock-fprintd

Thank you for the response. I am on NixOS right now - so maybe will try this later.

At this point I'm willing to remove the lock screen all together. I'd rather that than have my laptop "freeze" anytime I try unlocking it.

**Comment by FearlessSpiff** [comment]
> Currently using what I've modified from what @discapes sent
> 
> ```shell
> #!/bin/sh
> set -euo pipefail
> if [ -f /tmp/locked ] ; then exit ; fi
> touch /tmp/locked
> (
> until fprintd-verify | grep "verify-match"; do
>     echo "Failed to verify fingerprint at $(date)" | systemd-cat
> done
> echo "Unlocked at $(date)" | systemd-cat
> pkill -USR1 hyprlock
> ) &
> hyprlock
> rm /tmp/locked
> kill $(jobs -p)
> pkill fprintd-verify
> ```
> 
> The `/tmp/locked` stuff is just to ensure that you don't end up with multiple instances of hyprlock going at a given time. Use this at your own risk, I'm not responsible for anything that happens as this being potentially insecure - although I'm comfortable enough with it to use it myself.

I am just reading this but have no way to test it yet. What happens when you unlock by password? This will then  just run until the next lock? And thus you need the lock file? I might not understand it correctly. :D

**Comment by el-Basketo** [comment]
I think I got password + fingerprint parallel unlocking to work without needing to modify Hyprlock.

The idea is so simple that I don't know if it is genius or if it introduces major security flaws... Please tell me what you think of it.

The idea is... Just add this widget to your `hyprlock.conf`!

``` shell
# parallel check of fingerprint
# will not generate any visuals on the lock screen
label {
    text = cmd[update:0:1] until fprintd-verify -f right-index-finger; do :; done; pkill -USR1 hyprlock
}
```

Inspired by the above shell script by discapes https://github.com/hyprwm/hyprlock/issues/258#issuecomment-2068004569, and the rest of this conversation.

This feels like a cleaner way to do it with our current means, please correct me if I'm completely going off the rails...

Also removes the need for spaghetti checks like https://github.com/hyprwm/hyprlock/issues/258#issuecomment-2081586569
(no offense, as we say in engineering, the best part is not part)

An improvement would be to leverage the `SIGUSR2` capabilities of hyprlock to display feedback from the fprint-verify command. I have a couple ideas on how to do it (replacing the noop `:` with useful commands), but I need that sanity check before jumping in :P

**Comment by PaideiaDilemma** [comment]
If anybody has time, please go and test @moggiesir's MR (#514).

**Comment by b4shful** [comment]
amazing work from @moggiesir - very excited to have this added and get rid of the workarounds 💖💗

# Some guidance on migrating
## Remove old stuff from the pam config file
**The new version (0.5.0) of Hyprlock adds parallel authentication, and there is no longer any need for pam_fprintd or pam-fprint-grosshack**

Many users are using various workarounds (see the above comments on this issue), so you might have `/etc/pam.d/hyprlock` files something like:
### Examples of the old workarounds
**_(Collapsed for readability, click headings to expand)_**
<details>

<summary>pam_fprintd (installed with fprintd)</summary>

`/etc/pam.d/hyprlock`
```
# PAM configuration file for hyprlock
# the 'login' configuration file (see /etc/pam.d/login)
auth	sufficient	pam_unix.so	try_first_pass likeauth nullok
auth	sufficient	pam_fprintd.so
auth	include 	login
```

</details>

<details>

 <summary>pam-fprint-grosshack</summary>

[(Source)](https://gitlab.com/mishakmak/pam-fprint-grosshack)

`/etc/pam.d/hyprlock`
```
# PAM configuration file for hyprlock
# the 'login' configuration file (see /etc/pam.d/login)
auth	sufficient	pam_fprintd_grosshack.so
auth	sufficient	pam_unix.so try_first_pass nullok
auth	include 	login
```

</details>


### Default hyprlock pam file (you can revert to this after upgrading to 0.5.0)
With this new parallel auth support, you can go back to using the default pam file.
<details>

<summary>hyprlock default pam file</summary>

`/etc/pam.d/hyprlock`
```
# PAM configuration file for hyprlock
# the 'login' configuration file (see /etc/pam.d/login)

auth        include     login
```

</details>

## Configure hyprlock
You will also need to configure Hyprlock to enable fingerprint support (it is disabled by default).
The new update adds three config settings to `hyprlock.conf`:

![image](https://github.com/user-attachments/assets/604435de-298a-4311-87f5-ca6dd9dbf533)

For more information, see the [Hyprlock wiki page](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock).

Note: you might need to wait some time for Hyprlock to be updated in your distro's repositories before you can get the new version

**Comment by Jackaed** [comment]
Thanks guys! This works incredibly well. Very glad that this has been implemented, this is now by far the best locking utility on linux.
