### ISSUE TITLE
Hyprland freezes if Hyprlock is started via Hyprland key binding

### ISSUE THREAD

**Issue by DevilsBestFriend** [hyprwm/hyprlock#259]
I use Arch btw. (If it has something to do with that)
If I start Hyprlock with a Terminal it resumes normally but if I use a Hyprland shortcut Hyprland freezes and I have to open and close a Window (Terminal) for Hyprland to resume normally.

**Comment by vaxerski** [comment]
never seen that. Try adding a `sleep 1 &&` before the hyprlock command?

**Comment by DevilsBestFriend** [comment]
Doesn't change anything. The problem is Hyprland does not recognize any open windows after resuming from Hyprlock

**Comment by vaxerski** [comment]
uhhh... are you perhaps running without a config?

I feel like you are and the lock just runs without a config aka. doesn't render anything. Type your password and hit enter

**Comment by Mr-Ples** [comment]
i have this script:
```
#!/bin/bash
playerctl -a pause
pkill -9 -f hyprlock
hyprlock --immediate --verbose >> ~/logs/hyprlock.log 2>&1
```

and i run it with a keybind: `bind = $mainMod, L, exec, ~/scripts/lock_and_mute.sh`

and it works fine, on arch btw

try using a script
