### ISSUE TITLE
hold backspace to delete text entered

### ISSUE THREAD

**Issue by kojq** [hyprwm/hyprlock#263]
option to hold backspace to delete text entered instead of pressing the backspace key each time.

also, seems like the `delete` key is considered a character when it does not need to be.

**Comment by nhosama** [comment]
> option to hold backspace to delete text entered instead of pressing the backspace key each time.

You can do `Esc`, `Ctrl + u` or `Ctrl + Backspace` though.

[https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#keyboard-shortcuts-and-actions](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#keyboard-shortcuts-and-actions)

**Comment by kojq** [comment]
That feature is not the same...

**Comment by nhosama** [comment]
Oh! I misunderstood then.
