### ISSUE TITLE
[Feature Request] timeout to screen off

### ISSUE THREAD

**Issue by IDontKnow2Code** [hyprwm/hyprlock#267]
Need a timeout to screenoff feature by adding a flag like --off \<Time\> 
Time = time in seconds to screen off

**Comment by fufexan** [comment]
This can be handled by `hypridle`.

**Comment by IDontKnow2Code** [comment]
Not when you lock manually.
It waits for whole time set for idle trigger + screen off.
we could bind it like this `bind = Alt, L, exec, (sleep 30 && hyprctl dispatch dpms off)& hyprlock` but the disadvantage in this method is that once you awake the screen and not unlock it, it would stay awake again till the whole idle trigger + screen off trigger to occur. Which is why I request this screenoff timer for hyprlock.

**Comment by IDontKnow2Code** [comment]
> hyprlock doesn't control your screen, though. All it could accomplish is doable with a simple bash script

Ok I understand, but why not? Xorg lockscreens does it (e.g betterlockscreen)

**Comment by vaxerski** [comment]
because Xorg lockscreens can control your screen. Wayland ones can't.

All hyprlock could do is execute `hyprctl dispatch dpms off` which is not very portable and at this point use bash

**Comment by IDontKnow2Code** [comment]
> because Xorg lockscreens can control your screen. Wayland ones can't.
> 
> All hyprlock could do is execute `hyprctl dispatch dpms off` which is not very portable and at this point use bash

Understood, Thank you for your response.
