### ISSUE TITLE
placeholder_text doesn't use font_color

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#27]
It instead seems to use the default. I'm not saying it should use font_color, as that would be too saturated and probably confusing. Maybe placeholder_color?

**Comment by alba4k** [comment]
maybe not placeholder_color as it's used for feedback too

secondary_color? message_color? no idea

**Comment by fufexan** [comment]
You can color it with pango's markup:
```html
<span foreground="#aabbcc" style="italic">Input Password...</span>
```

**Comment by alba4k** [comment]
That still doesnt change the color of stuff like "Authentication failed" 

Thanks tho!

**Comment by luyu-wu** [comment]
Created a pull request with a bit of code.
https://github.com/hyprwm/hyprlock/pull/35
I've named the variable placeholder_color, maybe feedback color could be another variable considering the fact that many people probably want different colors for negative feedback vs. reminder.
