### ISSUE TITLE
cursor interation

### ISSUE THREAD

**Issue by kojq** [hyprwm/hyprlock#272]
Cursor interaction is still possible with hyprland when option set to visible.

Simple example where I interact (zoom in) with the hyprlock README.md image during the Sample Text lock screen (zoomed in so my password chars aren't visible):

https://github.com/hyprwm/hyprlock/assets/106934605/918757f9-4a0b-4bcc-b1a6-a6b050edd4e2

**Comment by vaxerski** [comment]
> when option set to visible.

what?

This sounds like a hyprland issue

**Comment by kojq** [comment]
hyprwm/Hyprland/issues/5541
