### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by JasonGrace2282** [hyprwm/hyprlock#274]
When running `hyprlock` I get the following:
```bash
hyprlock: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory
```
Do I need to switch to git?

**Comment by fufexan** [comment]
Update hyprlang and recompile hyprlock.

**Comment by JasonGrace2282** [comment]
Guess in that case I should move this to the AUR page for `hyprlang`
