### ISSUE TITLE
error "/home/choppystorm/.cache/yay/hyprlock-git/PKGBUILD: line 30: nix/cmake.patch: No such file or directory"

### ISSUE THREAD

**Issue by choppystorm** [hyprwm/hyprlock#275]
I went to install hyprlock and i gives me this error. I tried installing manually and it works. Just thought i would put it here so this can be fixed or if there are any possible fixes. 

This issue occurs right after the prepare() step in the compiling 

Sorry if this is confusing this is my first issue.

edit: I am running arch if that matters for the issue

**Comment by fufexan** [comment]
I guess the PKGBUILD needs to be updated. I removed the patch since it's no longer needed.

**Comment by choppystorm** [comment]
i still get the exact same error when installing hyprlock-git with yay

**Comment by fufexan** [comment]
Check whether you still have old versions of hyprlang installed, and make sure to clear yay's cache or force rebuild.

**Comment by choppystorm** [comment]
its fixed thanks
