### ISSUE TITLE
Input won't show up on key press with MAJ modifier

### ISSUE THREAD

**Issue by Nindouja** [hyprwm/hyprlock#279]
I have hidden the input fields by defaut, so it should show up only when I start typing my password. the problem is my password starts with a capital letter and hyprlock does not register that key combination to start typing. So I have to first type another char, delete it and then type my password.

If it helps I'm on nixos 23.11 updtaed recently. My hyprland version is v0.32.3. And I a french keyboard with the "fr" kb_layout.

**Comment by fufexan** [comment]
Most likely a Hyprland issue. Try using the overlay provided by the flake to get the latest Hyprland.

**Comment by Nindouja** [comment]
Well it looks like it's not happening anymore, or it's just for smth like one minute after lock. I'm not really qure
