### ISSUE TITLE
hide_cursor default value

### ISSUE THREAD

**Issue by davc0n** [hyprwm/hyprlock#280]
Hello,

The default value of hide_cursor is false but the wiki says true.
ref. https://github.com/hyprwm/hyprlock/commit/868e85e36284f59cab620dfec00f20f135dff02a and https://github.com/hyprwm/hyprland-wiki/commit/1a4345c6e0fa890e8c46a4c78795c50d020ea8b6

Which one should be changed?

**Comment by vaxerski** [comment]
feel free to make a wiki mr
