### ISSUE TITLE
Possible trailing newline character from cmd output on label text

### ISSUE THREAD

**Issue by joelsleeba** [hyprwm/hyprlock#284]
Hi, love the project.

I was trying to center the label text. It appears that same text given directly using `text = Sampletext` and `text = cmd[update:1000] echo Sampletext` changes the position in both instances.

Here's the lockscreen when using `text=Joel`
![image](https://github.com/hyprwm/hyprlock/assets/54855387/b6d90e5a-1b6b-44aa-8767-8b150f375f75)

And here's the lockscreen when using `text=cmd[update:1000] echo $USER`
![image](https://github.com/hyprwm/hyprlock/assets/54855387/5887e989-46b2-4e82-94f4-5eadf82a403c)

Based on the spacing added in the second image I guess the trailing newline character from the shell output is the culprit.

**Comment by vaxerski** [comment]
likely

**Comment by bvr-yr** [comment]
exactly. nothing wrong with that, `echo` without `-n` flag outputs newline char

**Comment by joelsleeba** [comment]
Yes this works for `echo`. But for other commands I am currently piping through `head -c -1` to remove the trailing newline. 

I was under the impression that the trailing newline was not intentional. I will close the issue if otherwise

**Comment by davc0n** [comment]
@vaxerski Hi, what do you think about an option to trim commands output? Eventually I can make a PR

**Comment by bvr-yr** [comment]
I think you can always wrap cmd in
```bash
echo -n "$(cmd)"
```

**Comment by vaxerski** [comment]
I don't care, you can make it into a mr

**Comment by davc0n** [comment]
@joelsleeba @vaxerski I think you can close this.

**Comment by joelsleeba** [comment]
Thank you for the fix
