### ISSUE TITLE
path = screenshot, two monitors

### ISSUE THREAD

**Issue by bashprompt** [hyprwm/hyprlock#287]
Is there any way to use the screenshot option with dual monitors? My lock screen background is black when `path = screenshot`

**Comment by dotaxis** [comment]
https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#widgets

```
widget_name {
    monitor =
    # further options
}
```

> `monitor` can be left empty for “all monitors”

**Comment by vaxerski** [comment]
as above
