### ISSUE TITLE
hyprlock doesn't show anything

### ISSUE THREAD

**Issue by No0ne003** [hyprwm/hyprlock#288]
it's just show on terminal like this 
![image](https://github.com/hyprwm/hyprlock/assets/145666753/75ef59ef-e08e-4467-96af-b070911c4fb0)
and the screen freeze until I enter the password

**Comment by fdnt7** [comment]
Have you yet configured hyprlock in `~/.config/hypr/hyprlock.conf`? If not, this is the expected behaviour, as stated by the [docs](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#configuration)

**Comment by No0ne003** [comment]
it's work thanks
