### ISSUE TITLE
[REQ] Output of a script

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#29]
Basically, I was thinking: wouldn't it be nice to be able to have a command output being displayed?

something like

```
label {
    monitor =
    exec = uptime -p
    interval = 30
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}
```

To be clear, exactly what custom/script does in waybar

This would allow for basically everything to be displayed in hyprlock: uptime, time, CPU/memory usage, battery percentage, blah blah blah without the need for custom widgets

**Comment by mauricekraus** [comment]
and exec_once might also be nice (e.g. fetching a quote). If vaxry is interested, I just did some config stuff in one of the prs and could therefore come up with another one

**Comment by alba4k** [comment]
I mean, a way to get that would just be interval = once, thats how it works in waybar at least

but sure

**Comment by mauricekraus** [comment]
The term can be arbitrary, but hyprland already uses these fields.. but I do not have any strong feelings about it.

**Comment by alba4k** [comment]
I see, but then the case where both exec and exec_once are present should also be handled

**Comment by alba4k** [comment]
I see, but then the case where both exec and exec_once are present should also be handled

**Comment by mauricekraus** [comment]
From a label/widget perspective this does not make to much sense to have both at the same time present.

**Comment by vaxerski** [comment]
5370762eb3f27ecfdb9b4d1f82a9c91c21c88730

**Comment by vaxerski** [comment]
`text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"`

**Comment by vaxerski** [comment]
please note to never run commands that don't exit unless you wanna have a really bad time.
