### ISSUE TITLE
Can't unlock when using KVM switch

### ISSUE THREAD

**Issue by pauldmccallum** [hyprwm/hyprlock#291]
I am using a Dual-Monitor KVM, and if hyprlock kicks in and I'm not on my Hyprland box, I cannot use my keyboard to unlock my machine when I switch back to it. Mouse and keyboard are working because I am able to move my pointer and switch to another TTY console. If I try to SIGHUP the hyprlock process, I just get a red screen and have to restart Hyprland. I am not a bug tester, so please advise what debugging steps that I can use to provide you with whatever logs etc. that you would like to use to troubleshoot this. Thanks in advance.

**Comment by vaxerski** [comment]
#101
