### ISSUE TITLE
[Feature request] run command after too many attemps

### ISSUE THREAD

**Issue by PurpleWazard** [hyprwm/hyprlock#292]
a feature i would like to see is adding a max password attempt count and run a command if tried too many times.

example:

```
MaxAttempts = 3
MaxAttemptsCommand = "shutdown -h now"
#MaxAttemptsCommand = "reboot"
#MaxAttemptsCommand = "/path/to/lockdownmode.sh"
```
in this example if the password is tried 3 times and failed it would run shutdown 

this is desired because if your laptop is encrypted and requires a key on boot then your data will be safe if an attacker got you laptop.

**Comment by NoamLeshem** [comment]
this is possible with the text being able to execute command, for example:
in hyprlock.conf:
```yaml
label {
    monitor =
    text = cmd[update:1000] /path/to/lockdownmode.sh $ATTEMPTS
    ...
}
```
and in lockdownmode.sh you can run your own script.

**Comment by thekbbohara** [comment]
is there a way to increase max attempt or reset attempt after x amount of time, or is there and my config sucks, which is why i need to restart my pc

**Comment by PurpleWazard** [comment]
@thekbbohara tou just need a script that takes $attempts as an argument and and check if attempts is greater than your wanted number
