### ISSUE TITLE
[Error]Failed to update through paru

### ISSUE THREAD

**Issue by alphanhp** [hyprwm/hyprlock#296]
Just as title says, "yay -Syu" show me nothing to update, but paru tell me it's failed when update to newest git version. And this has happened nearly two or three weeks ago before i report it.

here are paru msg:

==> Starting prepare()...
/home/nhp/.cache/paru/clone/hyprlock-git/PKGBUILD: line 30: nix/cmake.patch: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'hyprlock-git-0.2.0.r20.g2448774d-1': 
error: packages failed to build: hyprlock-git-0.2.0.r20.g2448774d-1

**Comment by bvr-yr** [comment]
```bash
rm -rf /home/nhp/.cache/paru/clone/hyprlock-git
```

**Comment by bvr-yr** [comment]
oh wait.. wtf is that
> And this has happened nearly two or three weeks ago before i report it.
> git-0.2.0.r20.g2448774d-1

**Comment by vaxerski** [comment]
I don't maintain any packages
