### ISSUE TITLE
[Feature request] layer image overtop of input field

### ISSUE THREAD

**Issue by gitnatel** [hyprwm/hyprlock#297]
I am trying to use a configuration like this:

```
# BACKGROUND FOR FINGERPRINT ICON (input field to enable fade)
input-field {
    monitor =
    size = 60, 60
    outline_thickness = 4
    outer_color = $accent
    inner_color = $surface0
    check_color = $accent
    fail_color = $red
    capslock_color =$yellow
    fade_on_empty = false
    placeholder_text = 
    position = 140, -95
    halign = center
    valign = center
}

# FINGERPRINT ICON
image {
    monitor = 
    path = ~/.fingerprint
    size = 60
    border_size = 0

    position = 140, -95
    halign = center
    valign = center
}
```

The aim is to display a rounded input field (in order to enable the `check_color` argument. This allows the elements background colour to fade to the specified value once an input has been entered).

Overtop of this, I am trying to layer a PNG of a fingerprint icon, with no border or fill, overtop of it, so that this is displayed as a pseudo "placeholder text".

Either a feature where an image can be used directly as "placeholder text", or the ability to define layers for the rendering, would resolve this.

Thanks :)

**Comment by Vagahbond** [comment]
Hello, I believe the order in which you define the elements set the z-axis order for them.

**Comment by gitnatel** [comment]
Hi, Yeah this was one of the first things I tried, I actually added a duplicate of the 'image' field in-between every other field in my config, to see If it would affect z-axis at any point, but the behavior remained identical.

Thanks though

**Comment by gitnatel** [comment]
Thanks!
