### ISSUE TITLE
[Feature request] Randomized label widget

### ISSUE THREAD

**Issue by Jappie3** [hyprwm/hyprlock#298]
I would like to try to make a widget that's very much like a label, but has several possible strings as text value & displays one randomly on the lockscreen (something like the quotes on Hyprland). Does that sound like something you would merge?

If yes, does splitting the string of the `text` option on e.g. commas to get the all the possible strings sound like an acceptable solution? As far as I can tell, there is currently no way to create list / array options with hyprlang...

**Comment by vaxerski** [comment]
why not use cmd?

**Comment by Jappie3** [comment]
you, sir, are a genius
