### ISSUE TITLE
Add option to hide cursor

### ISSUE THREAD

**Issue by ZackMitkin** [hyprwm/hyprlock#3]
Would be nice if there was an option to automatically hide the cursor in the hyprlock config. 

I would think that this should be the default since the cursor isn't useful 

A workaround can be to just run this script:
```bash
hyprctl keyword general:cursor_inactive_timeout 1
hyprlock
hyprctl keyword general:cursor_inactive_timeout 0
```

**Comment by ZackMitkin** [comment]
> but like as in after a timeout or altogether? Altogether should be doable in a few lines.

I think altogether without timeout would make sense. I think swaylock does this by default too, but can't confirm since swaylock can't hide the cursor on hyprland for whatever reason.

**Comment by ZackMitkin** [comment]
@vaxerski 

I see you have added this as config option but the cursor is still visible until you move your mouse...

**Comment by vaxerski** [comment]
scam

**Comment by ZackMitkin** [comment]
I just tried to record it in obs, but it doesn't capture my cursor in hyprlock...

**Comment by ZackMitkin** [comment]
closing in favor of https://github.com/hyprwm/hyprlock/issues/67
