### ISSUE TITLE
[REQ] Custom images

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#30]
Something that could be liked my many in hyprlock would be being able to add random images (maybe even gifs?) to hyprlock.

This could easily simulate a user profile picture, or just be used to show a random logo (that isn't avaiable in nerd fonts) or stuff like that

OR yk, hyprland's logo in a corner. I'd probably do that (edit: oh nvm, it's in nerdfonts now lol)

**Comment by leon-erd** [comment]
Fixed by https://github.com/hyprwm/hyprlock/pull/191?

**Comment by alba4k** [comment]
pretty sure that's more closely related to https://github.com/hyprwm/hyprlock/issues/10 but I'll have to test when I get home

How versatile is this?

**Comment by bvr-yr** [comment]
i didn't linked this issue because of gifs, but if it won't happen, probably can be closed?

**Comment by alba4k** [comment]
GIFs were not the  main thing I was asking for anyway.

Yes, this is perfect tbh

![immagine](https://github.com/hyprwm/hyprlock/assets/84153269/253eb73d-f686-4e54-a57b-a42c7db50210)

**Comment by bvr-yr** [comment]
discord refuses to send me sms, probably because Belarus is banned? (lul)
@vaxerski what do?

**Comment by alba4k** [comment]
my bad, published while it wasn't done uploading

same image you probably saw on discord tho
