### ISSUE TITLE
Red screen and unresponsive on hyprlock start

### ISSUE THREAD

**Issue by JonathanMathBoi** [hyprwm/hyprlock#300]
When I start hyprlock in anyway (hypridle, hyprland binding, or from the terminal), both my monitors get a solid red screen. The cursor is still visible and movable, but the only keyboard input which does anything is Super + M to stop hyprland entirely and send me back to the tty.

I am currently using the latest git version of hyprlock, but the issue occurs on the v0.3.0 version as well. As for hyprland, I am using the latest git version as well.

**Comment by vaxerski** [comment]
is this a regression?

**Comment by JonathanMathBoi** [comment]
I just tried changing hyprland-git out for hyprland 0.39.1 (still using hyprlock-git) and the issue no longer occurred. It looks like this is a hyprland issue, so I will go open an issue there.
