### ISSUE TITLE
[Feature Request] Control screen brightness and/or volume in locked state

### ISSUE THREAD

**Issue by cyanonoob** [hyprwm/hyprlock#304]
Locking my screen at night and unlocking in the morning can lead to unreadable situations. It would be great if hyprlock would allow screen brightness control.

**Comment by vaxerski** [comment]
hyprlock can't do that. That's something you have to script yourself, e.g. with `brightnessctl`

**Comment by fufexan** [comment]
https://wiki.hyprland.org/Configuring/Binds/#bind-flags -> use `bindl`.

**Comment by cyanonoob** [comment]
Damn, and I thought I'd properly googled. Thanks @fufexan, fixed it in 2 seconds.
