### ISSUE TITLE
Still able to interact with Hyprland to some degree, then breaks password input.

### ISSUE THREAD

**Issue by techyporcupine** [hyprwm/hyprlock#308]
Hello, I just tried using Hyprlock, and I am liking it a lot so far, but one thing I immediately noticed was that I was still able to use any key binding that I have set up in Hyprland, even with Hyprlock launched. And after interacting with Hyprland in that way, you can then no longer interact with Hyprlock and put in a password. 

If any more information is needed I can provide it, thank you in advance.

**Comment by vaxerski** [comment]
what's your hyprland version? that sounds like a hyprland bug.

**Comment by techyporcupine** [comment]
I believe it would be the latest version in Git as of two days ago, when I last updated my flake on NixOS.

**Comment by vaxerski** [comment]
well, update first, then make sure the binds you're talking about aren't locked (bindl) because those work even when there is a lockscreen, hence, locked

pass yer config

**Comment by JassonCordones** [comment]
Don't know if this should be here or in a separate issue but right now I noticed something similar: I left my mouse cursor over a paused youtube video in firefox and locked the screen and the cursor was still the pointy finger. I left clicked and the video started playing behind the lock screen. 

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

Firefox 125.0.3 (64-bit)

**Comment by techyporcupine** [comment]
Still a problem even after updating. I am only using binde and bind...
I should add that I can see my cursor changing as I move it around, so it can somehow also see what is behind Hyprlock.

Here is my config:

```nix
  wayland.windowManager.hyprland = {
    settings = {
      # Configuration for monitors
      monitor = [
        # https://wiki.hyprland.org/Configuring/Monitors/
        "eDP-1,1920x1080@60,0x0,1"
        "HDMI-A-1,1920x1080@120,1920x0,1" # 1080 high refresh conf
        #"monitor=,preferred,auto,1" # Everything config
      ];
      # Commands to exec on launch
      exec-once = [
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
        "swaync & waybar & hyprpaper & hypridle & udiskie &"
        "wl-paste --watch cliphist store"
        "hyprctl setcursor Catppuccin-Mocha-Green-Cursors 24"
        "firefox"
      ];
      # Env vars to set on start
      env = [
        "WLR_NO_HARDWARE_CURSORS,1"
      ];
      # Input devices configuration
      input = {
        kb_layout = "us";
        kb_model = "latitude";
        follow_mouse = 1;
        touchpad = {
          natural_scroll = "no";
          disable_while_typing = false;
        };
        sensitivity = 0; # -1.0 - 1.0, 0 means no modification.
      };
      # Config under the general section
      general = {
        gaps_in = 6;
        gaps_out = 6;
        border_size = 2;
        "col.active_border" = "rgba(89dcebff) rgba(00ff99ee) 45deg";
        "col.inactive_border" = "rgba(595959aa)";
        layout = "dwindle";
      };
      # Decoration configuration
      decoration = {
        blur = {
          enabled = true;
          size = 8;
          passes = 1;
          new_optimizations = "on";
          ignore_opacity = true;
        };
        rounding = 10;
        inactive_opacity = .85;
        drop_shadow = "yes";
        shadow_range = 4;
        shadow_render_power = 3;
        "col.shadow" = "rgba(1a1a1aee)";
      };
      # Animations configuration
      animations = {
        # https://wiki.hyprland.org/Configuring/Animations/ 
        enabled = "yes";
        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 4, default"
        ];
      };
      # Configuration for the dwindle layout
      dwindle = {
        pseudotile = "yes";
        preserve_split = "yes";
      };
      gestures = {
        workspace_swipe = "yes";
      };
      misc = {
        disable_hyprland_logo = true;
        vfr = true;
      };
      "$mainMod" = "SUPER";
      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];
      binde = [
        ", XF86MonBrightnessUp, exec, brightnessctl -s s +5%"
        ", XF86MonBrightnessDown, exec, brightnessctl -s s 5%-"
        ", XF86AudioRaiseVolume, exec, amixer sset Master 5%+"
        ", XF86AudioLowerVolume, exec, amixer sset Master 5%-"   
      ];
      bind = [
        "$mainMod, C, killactive," 
        "$mainMod, M, exit, "
        "$mainMod, E, exec, nautilus"
        "$mainMod, W, togglefloating, "
        "$mainMod, R, exec, rofi -show drun"
        "$mainMod, J, togglesplit," # dwindle
        "$mainMod, N, exec, swaync-client -t -sw"
        "$mainMod, L, exec, swaylock -f --color 000000 --clock"
        "$mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"

        ", XF86AudioMute, exec, amixer sset Master 0"
        ", Print, exec, grimshot copy area"

        # Scroll through existing workspaces with mainMod + scroll
        "$mainMod, mouse_down, workspace, e+1"
        "$mainMod, mouse_up, workspace, e-1"
      ]
      ++ (
        # workspaces
        # binds $mod + [shift +] {1..10} to [move to] workspace {1..10}
        builtins.concatLists (builtins.genList (
            x: let
              ws = let
                c = (x + 1) / 10;
              in
                builtins.toString (x + 1 - (c * 10));
            in [
              "$mainMod, ${ws}, workspace, ${toString (x + 1)}"
              "$mainMod SHIFT, ${ws}, movetoworkspace, ${toString (x + 1)}"
            ]
          )
          10)
      );
    };
  };
}
```

**Comment by vaxerski** [comment]
I am on hyprland-git (0.40.0) and can't reproduce this at all.

**Comment by JassonCordones** [comment]
Here is a screen recording reproducing the bug I'm experiencing if this helps: 
https://github.com/hyprwm/hyprlock/assets/4875039/55b9212e-8982-44a1-aa54-b729ab4cec17

> hyprctl version
> Hyprland, built from branch main at commit a3309b51a254f142c535022615be6f76eb23fa9b  (shadow: fix small pixel gaps between border).
> Date: Sat May 4 15:30:03 2024
> Tag: v0.40.0-1-ga3309b51, commits: 4607
> 
> flags: (if any)

**Comment by techyporcupine** [comment]
I was also just able to reproduce that exact scenario. YouTube video in Firefox, keep mouse cursor above play button, lock session, click, and you can then hear the video play. 

I would be interested in knowing if you (@JassonCordones) are able to reproduce my issue with being able to do things such as switch workspaces while it is locked (I can notice because my mouse cursor will change what it looks like, such as being a pointer in Firefox, and then being a text input thingy in VSCode) , and then be unable to input your password.

**Comment by JassonCordones** [comment]
Yes, I was able to switch workspaces and launch dmenu or a terminal, but in all scenarios I was able to input password.

**Comment by acheong08** [comment]
I have the same behavior as @JassonCordones 
I was able to replicate this issue with `swaylock`. I could open terminals, stop music, etc. Likely a Hyprland problem

**Comment by rtgiskard** [comment]
With hyprland: v0.40.0, commits: 4606:

On hyprlock screen, hyprland keybindings is still responsible, which could be a serious security issue

**Comment by androw** [comment]
I can reproduce the issue on Arch with:
hyprland 0.40.0-1.1
hyprlock 0.3.0-1.1
If I launch hyprlock, I can still open new terminal in the Hyprland session for example.

**Comment by vaxerski** [comment]
thats a bug in hyprland thats fixed in git

**Comment by techyporcupine** [comment]
Can confirm, the issue is fixed after updating my Hyprland input. Thanks!!
