### ISSUE TITLE
Missing background image with JPEG image files 

### ISSUE THREAD

**Issue by rendam** [hyprwm/hyprlock#315]
When using the attached images as background hyprlock fails to load them and instead shows a gray or transparent background. The file size does not seem to be a problem, as PNG files with up to ~7MB are rendering fine.
First I thought it has something to do with the mismatch of screen resolution 3440x1440 and image pixels but resizing it in GIMP did not change a thing. Only until I lossy compressed the resized image did it render. 

My log and config:
[hyprlock.log](https://github.com/hyprwm/hyprlock/files/15217627/hyprlock.log)
```
source = ~/.cache/wal/colors-kitty.conf

# BACKGROUND
background {
    monitor =
    path = ~/.config/swww/wall.set
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font Mono
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-H:%M%p")"
    color = $foreground
    #color = rgba(255, 255, 255, 0.6)
    font_size = 120
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -300
    halign = center
    valign = top
}

# USER
label {
    monitor =
    text = Hi there, $USER
    color = $foreground
    #color = rgba(255, 255, 255, 0.6)
    font_size = 25
    font_family = JetBrains Mono Nerd Font Mono
    position = 0, -40
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.rdots/scripts/whatsong.sh)" 
    color = $foreground
    #color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = JetBrainsMono, Font Awesome 6 Free Solid
    position = 0, 50
    halign = center
    valign = bottom
}

```

the resized and compressed image (working)
![Phoenix_edit-min](https://github.com/hyprwm/hyprlock/assets/18057685/178216aa-2527-44c1-bfb8-86a0295db8f2)

the working one:
![colors-1](https://github.com/hyprwm/hyprlock/assets/18057685/706c8514-3a28-498d-9bb4-a9b8b8dfc2c4)

not working images
![woodpath](https://github.com/hyprwm/hyprlock/assets/18057685/2ccadc20-5537-42e6-b9d0-de6afb5a0c9a)
![Phoenix](https://github.com/hyprwm/hyprlock/assets/18057685/7741c121-184f-4035-91b7-cbbec81d12a9)

**Comment by SakuraBlossomTree** [comment]
I also tried to compress the JPEG image, it didn't work but when converting it to PNG it worked without needing to compress. Maybe change this in the wiki for now till someone finds a fix for this

**Comment by JoelAlphonso** [comment]
Same here can't seem to be able to use any JPEG images using the latest 0.3.0-1 release

**Comment by shilkazx** [comment]
Same here, convert jpg to png is a workaround. 
When using jpg, one monitor shows a black background, but another one show original content as background(I have two monitor).

**Comment by rwtallant13** [comment]
Same thing happening here. Converting to png is temporary solution.

**Comment by night-treader** [comment]
8k and non-standard ratio (i.e. not 16:9) png images work, so probably not a file size limit.
jpg all give the same OOM error.
My naive guess is an error with how hl uses cairo to process the jpg. Probably from using `cairo_image_surface_create_from_png` (lines 181, 262 in src/renderer/AsyncResourceGatherer.cpp) and feeding it a jpg.
See [this](https://stackoverflow.com/questions/77384048/cairo-image-surface-create-from-png-returns-out-of-memory-but-i-have-enough) post of a similar issue.
