### ISSUE TITLE
image widget relies on extension to detect image filetype

### ISSUE THREAD

**Issue by pschmitt** [hyprwm/hyprlock#317]
Hi,

I have the following in my hm config:

```nix
home.file = {
  ".face" = {
    source = builtins.fetchurl {
      url = "https://www.gravatar.com/avatar/8635e7a28259cb6da1c6a3c96c75b425.png?size=96";
      sha256 = "1kg0x188q1g2mph13cs3sm4ybj3wsliq2yjz5qcw4qs8ka77l78p";
    };
  };
};
```

which hyprlock fails to use:

```
[WARN] Extension: .png?size=96
[ERR] unrecognized image format of /home/pschmitt/.face
```

The culprit seems to be the filename my image symlink points to:

```shell
$ readlink -e ~/.face
/nix/store/48dbqrz32858bsszip1v53d1z6mw9qkx-8635e7a28259cb6da1c6a3c96c75b425.png?size=96
$ file /nix/store/48dbqrz32858bsszip1v53d1z6mw9qkx-8635e7a28259cb6da1c6a3c96c75b425.png?size=96
/nix/store/48dbqrz32858bsszip1v53d1z6mw9qkx-8635e7a28259cb6da1c6a3c96c75b425.png?size=96: PNG image data, 96 x 96, 8-bit/color RGBA, non-interlaced
```

**Comment by fufexan** [comment]
You can pass a `name` parameter to `fetchurl`, and so you can rename the image to `<something>.png`.
Or you can [do what I do](https://github.com/fufexan/dotfiles/blob/de37098e56974490ada1fc307f9656f461894845/home/specialisations.nix#L29-L39).

**Comment by pschmitt** [comment]
Neat, thanks for the tip.

I was nonetheless expecting the "magic" fallback to detect the format regardless.

**Comment by Aqa-Ib** [comment]
This is actually a regression between 0.3.0 and current commit c87af3aa1f6e6bd06cffaabcc400bd45e26d565a

**Comment by Aqa-Ib** [comment]
In my computer hyprlock can show images without extension fine.

I think that you could write:
`url = "https://www.gravatar.com/avatar/8635e7a28259cb6da1c6a3c96c75b425.png";`  that is, removing this part: `?size=96` of the link. I think it should work like that. Then you can resize the image in hyprlock.conf.

**Comment by bvr-yr** [comment]
this happens not because of filename, but because it's a symlink

> I was nonetheless expecting the "magic" fallback to detect the format regardless.

it works for normal files
