### ISSUE TITLE
[bug] Running two instances of hyprlock disables it

### ISSUE THREAD

**Issue by harshkhandeparkar** [hyprwm/hyprlock#322]
I use `hypridle` to run `hyprlock` after 60s of inactivity. If I manually start `hyprlock`, then after 60s, due to `hypridle` running `hyprlock`, the first `hyprlock` completely shuts down and unlocks the computer. Notably, the `hyprlock` process still stays on and doesn't allow locking the computer again until it is killed first.

### Steps to Reproduce
1. Open a terminal and run `sleep 10 && hyprlock`
2. Open another terminal and run `hyprlock`
3. The computer will get unlocked after 10s.

### Version Information
- Hyprlock `v0.3.0-1` from the `extra` repo.
- Idk what other information to provide, please let me know if you need any.

**Comment by vaxerski** [comment]
this is fixed in hyprland git and unrelated to hyprlock

**Comment by harshkhandeparkar** [comment]
Does the related hyprland commit also fix fullscreen windows appearing over hyprlock?

**Comment by vaxerski** [comment]
different iirc but its also fixed in git
