### ISSUE TITLE
All key work on system lock

### ISSUE THREAD

**Issue by mahaveergurjar** [hyprwm/hyprlock#323]
Please fix the issue all keys work when hyprlock I am not set bindl means I do not add the l flag but the key is working
This problem is on only hyprlock-git not in hyprlock
https://github.com/hyprwm/hyprlock/assets/57872034/97c09877-6a5d-4d1a-a109-53610085fa14

**Comment by vaxerski** [comment]
you mean keybinds? iirc that's fixed in hyprland-git. It has nothing to do with hyprlock

**Comment by mahaveergurjar** [comment]
Yes all keybinds work when system lock why

**Comment by mahaveergurjar** [comment]
I am add video please see video you can understand

**Comment by vaxerski** [comment]
switch to hyprland git, it's fixed there

**Comment by mahaveergurjar** [comment]
Ok

**Comment by mahaveergurjar** [comment]
Thanks now working
