### ISSUE TITLE
Windows not focus and not recognize input after unlocking from Hyprlock.

### ISSUE THREAD

**Issue by kito30** [hyprwm/hyprlock#327]
Description: After unlocking the screen, some of the apps for instance, Chrome, Firefox, VScode not recognize any input and and have to switch to different workspace and switch back in order to get the input back in working. I don't know if its hyprlock issues or Hyprland.
Step to reproduce: Lock screen with Vscode running in the background. Unlock, keyboarad input not working.
Version: AUR git.

**Comment by vaxerski** [comment]
thats a hyprland issue
