### ISSUE TITLE
hyprlock getting unlocked without invoking password if same key is pressed

### ISSUE THREAD

**Issue by JaKooLit** [hyprwm/hyprlock#329]
I have hyprlock keybind

CTRL ALT L to execute a script

script contains
hyprlock -q

after locking with either keybinds set, or via wlogout or a screen lock button, it does not matter wait a few seconds or a minute, or even longer. 

hyprlock will get unlocked by same keybinds CTRL ALT L

**Comment by vaxerski** [comment]
that's a bug in hyprland that's fixed in git
