### ISSUE TITLE
`label:text_align` does not exist

### ISSUE THREAD

**Issue by portalbyte** [hyprwm/hyprlock#331]
In my config, I have a `label` with the property `text_align = center`. According to the [docs](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#label), this property should exist. However, on launch, an error occurs:

```
[ERR] Config has errors:
Config error in file /home/portalbyte/.config/hypr/hyprlock.conf at line 19: config option <label:text_align> does not exist.
```

**Comment by inmymum** [comment]
I have also noticed this issue, it isn't just you. I just use the -q flag to hide output. After commenting out the line, the issue disappeared and causes no issues with actual rendering.

**Comment by davc0n** [comment]
@portalbyte @vaxerski I think you can close this.
