### ISSUE TITLE
Invisible lock when unlocking from a disabled screen.

### ISSUE THREAD

**Issue by svin24** [hyprwm/hyprlock#337]
Sorry for the edit, i miss typed and for some reason github automatically posted this. In any case:

I disable my laptop display on lid close as I use it with an external monitor sometimes.
```
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1.2"
```
however with hyprlock when I open my lid (re-enabling the display), I don't see any hyprlock prompt and I need to type my password on some invisible lock screen before I can interact with my computer.

### reproduction steps
1. make sure hyprlock is installed and works
2. ideally use a laptop or somehow disable and re-enable your only display
3. open your display to see a new empty workspace, you cannot interact with anything unless you type your password in some invisible prompt like you would normally.

### Additional info
tested on Hyprland-git with Hyprlock-git.

**Comment by vaxerski** [comment]
please use one of the templates next time

**Comment by svin24** [comment]
yes sorry about that, i don't know how this happened actually.
