### ISSUE TITLE
[REQ] Show failed attempts

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/hyprlock#34]
I'd love to see an option to show the amount of failed attempts, just like swaylock-effects has with the `-F` flag. This could probably be as simple as just creating a new variable like `$FAILED_ATTEMPTS`, holding this amount.

Though I do quite like the way swaylock does this, where it shows you the amount of failed attempts when you're entering the password, but if the password input is empty, it shows the date instead. Doing something like this would probably require a much more complex logic though, and I'm not sure it's viable to implement with the way things are now.

**Comment by vaxerski** [comment]
the problem with a variable is that for now labels only have "refresh every x ms" attached to them. So either we do every 1s (inefficient if you ask me) or add infra for on-demand refresh which is gonna be more work

**Comment by ItsDrike** [comment]
Building up the on-demand refresh system for variables could be pretty useful for a bunch of things, so it might be worth it. 

An example (totally unrelated to this issue, and major bikeshedding) would be how [`eww` does dynamic variables](https://elkowar.github.io/eww/configuration.html#adding-dynamic-content), where it's possible to set up different kind of variables, some just as simple constants, others as listeners to long running commands, setting the stdout of that command as the content of that variable each time it's flushed, or others that just do simple polling after some set interval.

This would probably then replace the current way commands are done (from #29), but it would gives us a much cleaner system to do this imo, especially if we'd want to show the same command output multiple times somewhere, without just calling it again. The support for long running commands could also be pretty useful, like with commands that listen to sockets for updates, i.e. for volume. I'm not sure how important this would be for a lock screen app, but it would certainly be neat.

If this is done, the failed attempts variable could then just be managed by hyprlock directly, or (yet another, probably overkill idea), hyprlock could be creating a socket, just like hyprland does, reporting each failed attempt event there, and leave setting the variables to those custom long running scripts, which could listen to it, and update the variable once that event is produced. That way, those scripts could also for example output the time at which those attempts were made, and a bunch of other things. Also, this socket could be useful for other things that hyprlock might want to be reporting.

All of this is very likely a major overkill way to do this, but it would be very versatile, and I'd love to see a lock screen with this kind of level of customization.

**Comment by ItsDrike** [comment]
Fixed in  #154
