### ISSUE TITLE
hyprlock does not block hyprland keybindings

### ISSUE THREAD

**Issue by carbolymer** [hyprwm/hyprlock#342]
hyprlock passes through keybindings to hyprland.
1. Have a keybinding in hyprland executing a command:
```
bind = SUPER,      z, exec, rofi -modi "window,run,drun" -fuzzy -hide-scrollbar -icon-theme Moka -normal-window -show drun
```
2. Run `hyprlock`
3. Press `SUPER-z`
4. Unlock `hyprlock`
5. `rofi` was executed and is visible

**Comment by Platotel3s** [comment]
Oke thx bro
