### ISSUE TITLE
Media keys to pass through to currently active media player.

### ISSUE THREAD

**Issue by lee-morgan** [hyprwm/hyprlock#343]
Hi,

It would be great if the keyboard media keys were passed through the lockscreen to the player, same with buttons on headphones and speakers.

Regards
Lee

**Comment by fufexan** [comment]
Hi Lee. The media keys are not handled by hyprlock, but by Hyprland. As an example of binds that work even when the screen is locked, here's my config (note the bind**l**):
```ini
bindl=, XF86AudioPlay, exec, playerctl play-pause
bindl=, XF86AudioPrev, exec, playerctl previous
bindl=, XF86AudioNext, exec, playerctl next
```

As for headphones/speakers buttons, those are not handled by Hyprland, but by the bluetooth daemon/dbus.

**Comment by fufexan** [comment]
`bindl` should work just fine. To rule out whether it's a hyprlock or Hyprland bug, can you also test whether they work on swaylock?
