### ISSUE TITLE
Rapid death and restart prevention doesn't work when not using hyprland

### ISSUE THREAD

**Issue by abextm** [hyprwm/hyprlock#346]
Hyprlock attempts to restart itself upon death, but only if it hasn't already restarted in the last 4 seconds. This doesn't work when not using hyprland because `/tmp/hypr/` does not exist, so it fails to write it's restart marker. [Relevant code](https://github.com/hyprwm/hyprlock/blob/ba4b08e5f5dacc38af083ef89f8c8c489a900068/src/core/hyprlock.cpp#L1111)

**Comment by vaxerski** [comment]
it won't anyways because it depends on hyprland, but yea I should also move it cuz /tmp/hypr is gone with 0.40
