### ISSUE TITLE
Lockscreen isn't updating correctly when monitor transform is changed

### ISSUE THREAD

**Issue by Rick-T** [hyprwm/hyprlock#348]
I''m using [iio-hyprland](https://github.com/ibrahimbayyinah/iio-hyprland) to automatically set the screen rotation of my 2-in-1 laptop (for tablet mode).

This leads to a problem with hyprlock when the device is physically rotated while it is locked. The hyprlock window doesn't update and then parts of the underlying windows are visible.

The problem is easily reproduced by updating the monitor transform after hyprlock has been called, e.g.

`(sleep 1 && hyprctl keyword monitor eDP-1,transform,1) & hyprlock`

**Comment by PaideiaDilemma** [comment]
@Rick-T can you check if this is fixed in 0.5.0?

**Comment by Rick-T** [comment]
I checked and it's working now. Thanks :)
