### ISSUE TITLE
Paused fullscreen video activates Hyprlock but overlays it

### ISSUE THREAD

**Issue by hektorinho** [hyprwm/hyprlock#354]
Hello,

When watching Youtube on my laptop I noticed if I pause the video while in fullscreen and walk away it triggers hyprlock. When I get back the video is overlaying hyprlock, I can still get in by typing my password and pressing enter but it doesn't seem like optimal behavior as there is no indication other than that I cant move my cursor or use keyboard that hyprlock is active.

Hyprlock 0.3.0
Hyprland 0.40.0

**Comment by vaxerski** [comment]
fixed in hyprland git
