### ISSUE TITLE
Hyprland shortcuts still work when screen is locked

### ISSUE THREAD

**Issue by Baldi-OG** [hyprwm/hyprlock#358]
Hi,

maybe I missed it somewhere but how do i disable hyprland shortcuts still working and for example opening the console in the background, while hyprlock is active? This honestly feels like a bug. When my laptop is locked i can still use the shortcuts an after unlocking using my password I can see that the shortcuts worked and I for example opened the console a few times.

**Comment by vaxerski** [comment]
fixed in hyprland git (bug in 0.40)
