### ISSUE TITLE
Shapes are unable to be drawn due to config errors

### ISSUE THREAD

**Issue by inmymum** [hyprwm/hyprlock#359]
I just recently found hyprlock and went to the wiki to figure out it's configuration. While messing with the shape option, I realized that shapes weren't actually being drawn on the screen. That's when I looked into the logs and found these errors

[ERR] Config has errors:
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 23: config option <label:text_align> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 34: config option <shape:monitor> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 35: config option <shape:size> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 36: config option <shape:color> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 37: config option <shape:rounding> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 38: config option <shape:border_size> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 39: config option <shape:border_color> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 40: config option <shape:rotate> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 41: config option <shape:xray> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 43: config option <shape:position> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 44: config option <shape:halign> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 45: config option <shape:valign> does not exist.
Config error in file /home/$USER/.config/hypr/hyprlock.conf at line 51: config option <label:text_align> does not exist.

Here is my config file:
general {
    disable_loading_bar = true
    no_fade_in = true
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor = eDP-1
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 0
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor = eDP-1
    text = $TIME
    text_align = center
    color = rgba(100, 175, 200, 1.0)
    font_size = 10
    font_family = Noto Sans
    rotate = 0
    position = 0, 6
    halign = center
    valign = center
}

shape {
    monitor =
    size = 300, 300
    color = rgba(10, 250, 200, 1.0)
    rounding = -1
    border_size = 8
    border_color = rgba(0, 207, 230, 1.0)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    position = 0, 80
    halign = left
    valign = left
}

label {
    monitor = eDP-1
    text = $USER
    text_align = center
    color = rgba(100,175,200,1.0)
    font_size = 10
    font_family = Noto Sans
    rotate = 0
    position = 2, -32
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(151515)
    inner_color = rgb(100, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    placeholder_text =  
    hide_input = false
    rounding = -1
    #check_color = rgb(204, 136, 34)
    check_color = rgb(100, 200, 200)
    fail_color = rgb(204, 34, 34)
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 
    invert_numlock = false
    swap_font_color = false 
    position = 0, -120
    halign = center
    valign = center
}

(spacing issue caused by github, not present in actual conf file)

**Comment by vaxerski** [comment]
wiki is always for hyprlock-git

**Comment by inmymum** [comment]
Whether or not it is for the git package, the wiki still doesn't specify that a certain feature isn't implemented in the stable package which is rather annoying for both us new users, and I would assume you as well considering you look at these bug reports. There is nothing listing the differences between the two packages on the wiki, so I had no clue it isn't actually an issue.

**Comment by vaxerski** [comment]
we can't really do that as the wiki is already versioned for hyprland. I believe there is a disclaimer on the wiki tho?

**Comment by inmymum** [comment]
Ok, thanks for the help clearing this up :D
