### ISSUE TITLE
Feature requests: on-click command for labels

### ISSUE THREAD

**Issue by NotAShelf** [hyprwm/hyprlock#36]
I'd like to be able to create power buttons and such, similar to gtklock. Since it seems a bit pointless to me to ask for a power menu (why would the lock program handle it?), I'd like to ask to be able to register commands similar to Hyprland's exec (i.e executed via `sh`) when a label is clicked.

**Comment by JassonCordones** [comment]
How is this achieved?

**Comment by g-regex** [comment]
I'm also curious about this. How can this be done? Was this issue closed because the feature already exists or because it was deemed unnecessary for some reason? If it doesn't exist, I would support reopening this feature request.
