### ISSUE TITLE
[Feature Request] Allow specifying grace period from the command line

### ISSUE THREAD

**Issue by hexclover** [hyprwm/hyprlock#360]
https://github.com/hyprwm/hyprlock/commit/6355216f483e8fbc1532f35e1cd17ff491efde1d has added the support for `general:grace` in the config. However, one may still want to specify the grace from the command itself for convenience.

For example, my use case is: I may want to set a grace period of say `5` for **automatic** idle locking, while also having the ability to *immediately* lock the system by **manually** pressing say `Meta+L`. In this case if said feature is supported, I only need to maintain a single config file and just add a `--grace` argument in the idle command.

P.S. I recognize the `source = ...` keyword can be used to reuse a common config file, but the command-line argument approach is arguably easier to use.

**Comment by Mr-Ples** [comment]
are you aware of the `--immediate` option?

**Comment by hexclover** [comment]
> are you aware of the `--immediate` option?
> 
> i use that when locking manually and have a grace period in the config for automatic locking

@Mr-Ples No I missed that option. I think that is as good as having a `--grace`. Thank you!
