### ISSUE TITLE
Missing package hyprutils from last PR

### ISSUE THREAD

**Issue by ArchVisions** [hyprwm/hyprlock#363]
Hello, I get this error during build: 
```
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:634 (message):
  The following required packages were not found:

   - hyprutils>=0.1.1
```
I am not entirely sure where this package is located. The easiest way to get around this is to do a git checkout the previous commit before c5b8ad0.

**Comment by fufexan** [comment]
https://github.com/hyprwm/hyprutils compile manually until an aur package is made.

**Comment by vaxerski** [comment]
as above
