### ISSUE TITLE
Datarace in CAsyncResourceGatherer

### ISSUE THREAD

**Issue by KasyanDiGris** [hyprwm/hyprlock#367]
Current implementation of `CAsyncResourceGatherer` is racy.

Data race between `preloadTargets` [modification](https://github.com/hyprwm/hyprlock/blob/main/src/renderer/AsyncResourceGatherer.cpp#L406) in `CAsyncResourceGatherer::asyncAssetSpinLock` and [accessing](https://github.com/hyprwm/hyprlock/blob/main/src/renderer/AsyncResourceGatherer.cpp#L215) in `CAsyncResourceGatherer::apply` leads to some widgets not shown. (It this case due to vector reallocation after push_back new element).

<details>

<summary>Hotfix:</summary>

```diff
diff --git a/src/renderer/AsyncResourceGatherer.cpp b/src/renderer/AsyncResourceGatherer.cpp
index f7f46ee..5f21650 100644
--- a/src/renderer/AsyncResourceGatherer.cpp
+++ b/src/renderer/AsyncResourceGatherer.cpp
@@ -211,6 +211,7 @@ void CAsyncResourceGatherer::gather() {
 }

 void CAsyncResourceGatherer::apply() {
+    std::lock_guard preloadTargetsLock{asyncLoopState.preloadTargetsMutex};

     for (auto& t : preloadTargets) {
         if (t.type == TARGET_IMAGE) {
@@ -400,6 +401,7 @@ void CAsyncResourceGatherer::asyncAssetSpinLock() {

         // process requests

+        std::lock_guard preloadTargetsLock{asyncLoopState.preloadTargetsMutex};
         asyncLoopState.busy = true;
         for (auto& r : requests) {
             if (r.type == TARGET_TEXT) {
diff --git a/src/renderer/AsyncResourceGatherer.hpp b/src/renderer/AsyncResourceGatherer.hpp
index 2fa81a8..01ffa1b 100644
--- a/src/renderer/AsyncResourceGatherer.hpp
+++ b/src/renderer/AsyncResourceGatherer.hpp
@@ -66,6 +66,8 @@ class CAsyncResourceGatherer {

         std::mutex                   assetsMutex;

+        std::mutex                   preloadTargetsMutex;
+
         std::vector<SPreloadRequest> requests;
         bool                         pending = false;
```

</details>

In other cases, for example, [accessing](https://github.com/hyprwm/hyprlock/blob/main/src/renderer/AsyncResourceGatherer.cpp#L86) non-atomic variable `asyncLoopState.busy` without additional synchronization leads to undefined behavior.

**Comment by KasyanDiGris** [comment]
UPD: thread sanitizer report https://pastebin.com/mtDmf04G

**Comment by vaxerski** [comment]
can you make a MR? :)

**Comment by KasyanDiGris** [comment]
> can you make a MR? :)

That hotfix is workaround. I can make refactoring of `CAsyncResourceGatherer`.

**Comment by vaxerski** [comment]
feel free
