### ISSUE TITLE
Multiple instances of `hyprlock` should not be allowed to start

### ISSUE THREAD

**Issue by b0ch3nski** [hyprwm/hyprlock#373]
Thanks for creating `hyprlock` :)

I'm running it with `sway` and `swayidle` as follows:
```
exec swayidle \
    timeout 600 'hyprlock --quiet' \
    timeout 15 'if pgrep --exact hyprlock; then swaymsg "output * power off"; fi' resume 'swaymsg "output * power on"' \
    lock 'hyprlock --quiet --immediate' \
    before-sleep 'hyprlock --quiet --immediate' \
    after-resume 'swaymsg "output * power on"'
```
The idea behind this config:
* After 5 min of inactivity, lock the screen
* After 15 sec of inactivity, check if lock screen is running - if so, turn off displays (save my OLEDs from burning...)
* If commanded to do so by `loginctl` or system suspend, lock the screen immediately

Now the fun part - `hyprlock` can be started multiple times (and does nothing when started after the first instance btw) and that indeed happens when I command the lock. After the 5 min of inactivity, another instance of `hyprlock` is created. Now, when I unlock the screen I still have some `hyprlock` instance running in the background which I don't see - but I could spot it because after 15 sec my screens are turned off :smile:

`hyprlock` should have a "_locking mechanism_" (pun intended) to allow running only one instance.

Related: #351

**Comment by vaxerski** [comment]
it should just exit if another lock is running tho

**Comment by b0ch3nski** [comment]
> it should just exit if another lock is running tho

@vaxerski I'm on v0.3.0 version and I can easily reproduce this even without `swayidle`:
```
$ hyprlock & hyprlock & hyprlock
... first lock starts, rest goes to the bg
$ pgrep hyprlock
... I see 2 pids here after unlocking
```

**Comment by fufexan** [comment]
Could be worked around with `pgrep hyprlock || hyprlock` until fixed.
