### ISSUE TITLE
Hyprlock kills hyprland session when power cycling monitor

### ISSUE THREAD

**Issue by SeekerOfAsh** [hyprwm/hyprlock#375]
## Brief summary of the problem:

Turning off one of my three monitors, waiting a few seconds and then turning said monitor back on, leads to hyprlock crashing and taking my hyprland session with it, which throws me back to my display manager.

Logging in with the monitor turned off and then turning it back on, bypasses the issue.

## Hardware description:

- CPU: R7 7800X3D
- GPU: AMD RX 7900 XTX
- Display: Main 5120x1440 120hz DP, secondary 2560x1440 75hz HDMI, third 1920x1080 60hz HDMI

## Distro info:

- Name: NixOS 24.11.20240613.e9ee548 (Vicuna) x86_64
- Kernel version: Linux 6.9.4
- Mesa version: 24.1.1
- Hyprland and hyprlock package: nixos-unstable

## How to reproduce the issue:

1. Lock system with all monitors active
2. Shutoff one of the monitors and wait a few seconds
3. Turn on said monitor
4. This should result in being booted back into the display manager

**Comment by vaxerski** [comment]
sounds like a hyprland issue, clients should not crash the compositor. Try hyprland-git.

**Comment by helto4real** [comment]
I have this issue, using git versions of all hypr* packages.
