### ISSUE TITLE
Shape doesn't exist apparently

### ISSUE THREAD

**Issue by Fincali197** [hyprwm/hyprlock#377]
![image](https://github.com/hyprwm/hyprlock/assets/130681919/1108e71d-c980-4c88-b2fd-f63619b18cff)
So basically I have this piece of code in my config:
```
shape {
    monitor =
    size = 1000, 1000
    color = rgba(255, 255, 255, 1.0)
    rounding = -1
    border_size = 8
    border_color = rgba(0, 207, 230, 1.0)
    rotate = 0
    xray = true # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, 80
    halign = center
    valign = center
}
```
And you can see the issue clearly on the screenshot: shapes are nonexistent as configuration options. I don't think shapes are in any way separated on the wiki, so I just assume they are supposed to work as a normal widget, but literally the example config doesn't function lol

**Comment by vaxerski** [comment]
only on git
