### ISSUE TITLE
Incorrect CMakeLists.txt installation instruction in source code?

### ISSUE THREAD

**Issue by hhhorb** [hyprwm/hyprlock#381]
https://github.com/hyprwm/hyprlock/blob/main/CMakeLists.txt Lines 87-90

```# Installation
install(TARGETS hyprlock)

install(FILES ${CMAKE_SOURCE_DIR}/pam/hyprlock DESTINATION ${CMAKE_INSTALL_FULL_SYSCONFDIR}/pam.d)
```

But I was trying to use debmake/debuild to create a Debian package and it fails with this source code (which is different)...

https://github.com/hyprwm/hyprlock/archive/refs/tags/v0.3.0.tar.gz Lines 83-90

```# Installation
install(TARGETS hyprlock)

install(CODE "
    if (NOT EXISTS \"${CMAKE_INSTALL_FULL_SYSCONFDIR}/pam.d/hyprlock\")
        install(FILES \"${CMAKE_SOURCE_DIR}/pam/hyprlock\" DESTINATION \"${CMAKE_INSTALL_FULL_SYSCONFDIR}/pam.d\")
    endif()
")
```

The build succeeds after patching the source to match /blob/main

**Comment by fufexan** [comment]
I doubt it is incorrect, as it works on most distributions. Backstory on how it came to be like that https://github.com/hyprwm/hyprlock/issues/220.

**Comment by hhhorb** [comment]
Yes, it works if I build and install as per the ReadMe, it just wouldn't let debuild build a Debian *.deb file. Closing this, then.
