### ISSUE TITLE
Pam entry

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/hyprlock#4]
Hyprlock does not seem to create a pam entry file.
In compare to swaylock as it does with the contents 

was planning to test if it will work with fingerprint (using fprint-grosshack)

Also on other note would it be possible to have path acceptance of `~/`?

**Comment by vaxerski** [comment]
dafoq is a pam entry file

> Also on other note would it be possible to have path acceptance of ~/?

for backgrounds? yeah planned alongside jpegs and webms

**Comment by niksingh710** [comment]
> dafoq is a pam entry file
`/etc/pam.d/` (Pluggable Authentication Modules)
I also don't know in depth but in short they perform authentication.
So swaylock has one and if I specify some other `.so` file it can authenticate.
```
#
# PAM configuration file for the swaylock screen locker. By default, it includes
# the 'login' configuration file (see /etc/pam.d/login)
#

auth      sufficient pam_fprintd.so
auth include login
```
i am not a good explainer but here as I added pam_fprintd.so then it allows swaylock to get authenticated using fingerprint.

**Comment by vaxerski** [comment]
I'll see, alr

**Comment by bvr-yr** [comment]
btw its better to set
```pam
auth include system-auth
```

i don't remember exactly what's the reason, probably related to autologin or absence of stuff like sddm or greetd. swaylock doesn't work without changing it, while [waylock](https://github.com/ifreund/waylock) ships `system-auth` by default

**Comment by kragebein** [comment]
My setup might have been fucked by IPA. But for some reason hyprlock wanted to authenticate as "su". And my "su" is 100% local and my normal setup is using system-auth. 

so had to add auth include system-auth into /etc/pam.d/su

Now it works.

**Comment by alba4k** [comment]
@bvr-yr wait does that mean creating that file will work?

**Comment by bvr-yr** [comment]
yes just as root
```sh
echo "auth include system-auth" > /etc/pam.d/hyprlock
```

**Comment by niksingh710** [comment]
> yes just as root
> 
> ```shell
> echo "auth include system-auth" > /etc/pam.d/hyprlock
> ```

added this tried to also add fprintd entry with gross hack seems like hyrlock does not support blank password input so it failed to log me in using fingerprint. :(

**Comment by bvr-yr** [comment]
i was talking about `login` vs `system-auth`, as former doesn't work in some cases
i don't use fingerprints so can't tell

**Comment by alba4k** [comment]
@vaxerski is there any reason why that was initially set to `su` and not `hyprlock`?

**Comment by vaxerski** [comment]
yeah

**Comment by alba4k** [comment]
...which is..?

**Comment by vaxerski** [comment]
a random snippet of pam online used su.

**Comment by vaxerski** [comment]
fwiw, changing it to hyprlock makes pam never auth

**Comment by alba4k** [comment]
You need to package a `/etc/pam.d/hyprlock` file with hyprlock, which is what this issue is asking for

this is what mine looks like (asks for password, if I press enter on an empty password, asks for fingerprint)
```
#
# PAM configuration file for the swaylock screen locker. By default, it includes
# the 'login' configuration file (see /etc/pam.d/login)
#

auth            sufficient      pam_unix.so try_first_pass likeauth nullok
auth            sufficient      pam_fprintd.so
auth            include         login
```

A decent default could just be (slightly based on swaylock's default

```
# PAM configuration file for hyprlock
# the 'login' configuration file (see /etc/pam.d/login)

auth            include         login
```

**Comment by alba4k** [comment]
Also I believe having hyprlock handle this by itself could help manage issues like #95 and #106 more easily

I can open a PR with such a change so you can review it, if you want

**Comment by vaxerski** [comment]
sure

**Comment by alba4k** [comment]
I think this can finally be closed

**Comment by bvr-yr** [comment]
i'v discovered what was wrong with `auth include login` and not `auth include system-auth`

it was `pam_autologin` module, as per [ArchWiki](https://wiki.archlinux.org/title/Pam_autologin)

just in case anyone else using it u should:
- either change **/etc/pam.d/hyprlock** to `auth include system-auth`
- or use <code>auth <b><i>sufficient</b></i> pam_autologin.so</code> instead of <code>auth <b><i>required</b></i> pam_autologin.so</code> in **/etc/pam.d/login**

**Comment by alba4k** [comment]
Sounds like a specific usecase tho, right?

**Comment by bvr-yr** [comment]
yeah, but i don't think autologin is that rare
also, update AUR package not to overwrite existing **/etc/pam.d/hyprlock**

**Comment by alba4k** [comment]
Yeah, sorry, doing that right now.

**Comment by alba4k** [comment]
@niksingh710 can this be closed?

**Comment by niksingh710** [comment]
> @niksingh710 can this be closed?

yes, as now pam file is created after hyprlock installation this issue is completed.

**Comment by littleblack111** [comment]
for howdy. it doesnt seem to work. tried auth        sufficient  pam_python.so        /lib/security/howdy/pam.py(from wiki).
or system-auth(which i added  auth        sufficient  pam_python.so        /lib/security/howdy/pam.py)
