### ISSUE TITLE
(Feature Request) Pass through certain keybindings defined in config

### ISSUE THREAD

**Issue by deshpandetanmay03** [hyprwm/hyprlock#415]
Hyprlock does not pause youtube/mpd so in the config we can create a list of keybindings that are allowed to pass through to hyprland through hyprlock

something like
```
general {
    pass_through = [
        SUPER, p
        SUPER, +
        ....
    ]
}
```
or
```
general {
    pass_through = SUPER, p
    pass_through = SUPER, +
    ....
}
```

**Comment by PaideiaDilemma** [comment]
This is not something that hyprlock could implement. However, hyprland supports keybindings that work when the screen is locked via `bindl`. See [bind-flags](https://wiki.hyprland.org/Configuring/Binds/#bind-flags)

**Comment by vaxerski** [comment]
as above

**Comment by danielwerg** [comment]
Run only when hyprlock is active:

```conf
bindl = $SUPER, A, exec, pgrep hyprlock && playerctl play-pause
```
