### ISSUE TITLE
[Weird Behaviour]: multiple hyprlock istances keep running

### ISSUE THREAD

**Issue by daniele821** [hyprwm/hyprlock#416]
If i run hyprlock, and then once it's running, i run an other instance of hyprlock (through a keybind with bindl, or on switch lid for example), then the first istance gets closed after i unlock the screen, but the other istances keep running in the background, without doing anything (ie, if i killall hyprlock, i don't get the red screen of death)

I can think of two ways of fixing this:
- not running hyprlock, if an other istance is already running
- kill all hyprlock instances running in the background once the screen is unlocked

But in both cases, someone may want to have multiple istances of hyprlock running for multiple displays. 

So, since solutions like keeping track of if  hyprlock is running for every display seems a very big complication for me,  maybe adding a flag like `--single-instance` could make sense instead?

**Comment by PaideiaDilemma** [comment]
I think the linked MR should fix this behavior :)
