### ISSUE TITLE
[REQ] Option to switch dpms off after set amount of time

### ISSUE THREAD

**Issue by 0bCdian** [hyprwm/hyprlock#42]
Right now hyprlock wakes the screens and stays like that even if hypridle has a timer to switch dpms off. It would be cool we could turn off the screen automatically after x amount of time even when hyprlock is active.

Things I've tried:

- [x] `hyprctl dispatch dpms off && hyprlock`  
- [x] Having a listener on hypridle that switches dpms off and another separate one sometime later that locks the screen (this results in the screen waking up).
- [x] `hyprlock && hyprctl dispatch dpms off`

**Comment by vaxerski** [comment]
something must be up with your config, cuz it works for me.

```
hyprlock & sleep 5 && hyprctl dispatch dpms off
```
?

**Comment by 0bCdian** [comment]
Thanks, I'm a dummy I was calling the commands wrong in the config. Sorry for the inconvenience :(
