### ISSUE TITLE
Grace cause fail auth

### ISSUE THREAD

**Issue by The-Lost-Light** [hyprwm/hyprlock#423]
When set grace>0 and unlock by it

It trigger several times
```
[LOG] In grace and cursor moved more than 5px, unlocking!
[LOG] Unlocking session
[ERR] Unlock already happend?
```
and its be count in faillock times

**Comment by PaideiaDilemma** [comment]
> and its be count in faillock times

You mean in terms of pam faillock or $ATTEMPTS?

**Comment by The-Lost-Light** [comment]
pam faillock (i can reset by  faillock --reset)

**Comment by The-Lost-Light** [comment]
yes, run 3 times hyprlock with grace unlock then it will completely locked

**Comment by PaideiaDilemma** [comment]
Should be fixed in the linked PR :)
You could try it out if you want.

**Comment by The-Lost-Light** [comment]
Thanks you, it work!
