### ISSUE TITLE
Transparent PNG image not being transparent

### ISSUE THREAD

**Issue by sa-akhavani** [hyprwm/hyprlock#429]
When I use hyprlock to draw a transparent png using the `image` module, it does not draw it transparent and it draws it with a white background.
What I want to achieve in the end is having a blurred screenshot of my desktop in the background. Then have a transparent png in the middle of it over the background.
It is interesting that the `background` module supports rendering the transparent png properly but I cannot use that because it is not possible to change the size of it. Size is only supported in the image module.

Hyprland version: v0.41.2
Hyprlock version: 0.4.0-1
OS: Arch Linux x86_64 - Linux 6.6.40-1-lts

This is my hyprlock config:
```
# background image will be a blurred screenshot
background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1
    blur_size = 3
    noise = 0.2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.5
    vibrancy_darkness = 0.5
}
# The transparent png (not working)
image {
    monitor =
    path = ~/transparent-pic.png
    size = 200
    rounding = 0
    border_size = 1
    border_color = rgb(221, 221, 221)
    rotate = 0
    reload_time = -1
    position = 0, 200
    halign = center
    valign = center
}
```

**Comment by PaideiaDilemma** [comment]
That is because currently when `border_size` is used, the image draws a solid rectangle in `border_color` below it.

if you set `border_size = 0` it should be transparent.

**Comment by sa-akhavani** [comment]
It worked with the `border_size = 0` option. Thanks!
