### ISSUE TITLE
Executing hyprlock triggers hypridle to think it has resumed

### ISSUE THREAD

**Issue by reidlabwastaken** [hyprwm/hyprlock#430]
When executing hyprlock from hypridle, it runs all the resume commands that came before it (ex. dimming screen, dpms off)
This is a hyprlock issue and the first bad commit is `69d37d2663bdd69a4d7891baf68acf4f81a5610a`

**Comment by PaideiaDilemma** [comment]
True but same with swaylock.
So it is probably a idle notify bug in hyprland.

**Comment by WantenMN** [comment]
Hi,

I encountered a similar problem with hyprlock and hypridle, where executing hyprlock would trigger hypridle to execute all previous resume commands, such as dimming the screen and turning off DPMS.

I found a possible solution that addresses this issue. You can check out my approach here: [Swaylock and Hyprlock Trigger Idle Resume Event Disrupting Screen Brightness](https://discourse.nixos.org/t/swaylock-and-hyprlock-trigger-idle-resume-event-disrupting-screen-brightness/49958).

This method involves adjusting the configurations for swayidle and hypridle to handle screen brightness and DPMS, ensuring that hyprlock does not incorrectly trigger resume events.

I hope this helps with your issue!
