### ISSUE TITLE
Hyprlock Crashes and Unlocks Device Upon Repeated Keybind Activation

### ISSUE THREAD

**Issue by Arqamz** [hyprwm/hyprlock#437]
### Hyprlock Crashes and Unlocks Device Upon Repeated Keybind Activation

**Description:**
When activating Hyprlock using the designated keybind, the screen locks as expected. However, if the keybind is pressed again while Hyprlock is active, the application crashes and the device becomes unlocked. This poses a significant security risk, as anyone aware of the keybind can bypass the lock and gain access to the computer.

**Steps to Reproduce:**
1. Press the keybind to activate Hyprlock.
2. While Hyprlock is active, press the keybind again.

**Expected Behavior:**
Hyprlock should ignore the keybind or remain locked.

**Actual Behavior:**
Hyprlock crashes, and the device unlocks.

**Attachments:**
- [Video demonstrating the issue](https://github.com/user-attachments/assets/81668ed0-f2bf-4f56-85f3-e62150bc4bf6)

**Comment by PaideiaDilemma** [comment]
Please post your hyprland and hyprlock versions. I am pretty sure this is about hyprland's handling of requesting a session lock, when a session lock is already present and has already been fixed.

**Comment by Arqamz** [comment]
Hyprlock 0.3.0-unstable-2024-04-24
Hyprland 0.41.2 

On NixOS installed through stable 24.05 nix pkgs.
