### ISSUE TITLE
Fullscreen Windows Not Covered by Hyprlock

### ISSUE THREAD

**Issue by Arqamz** [hyprwm/hyprlock#438]
### Fullscreen Windows Not Covered by Hyprlock

**Description:**
When a window is in fullscreen mode and Hyprlock is activated, the fullscreen window remains visible instead of Hyprlock overlaying it. This issue is reproducible with applications like VSCode and terminal but did not occur with Chrome for me. This behavior creates a potential security risk, as the contents of the fullscreen window are still visible while Hyprlock is supposedly active.

**Steps to Reproduce:**
1. Open an application (e.g., VSCode or terminal) in fullscreen mode on one monitor.
2. Activate Hyprlock.

**Expected Behavior:**
Hyprlock should overlay and lock the screen, covering all fullscreen applications.

**Actual Behavior:**
The fullscreen application remains visible, although Hyprlock is active on the other monitor that does not have a fullscreen application open.

**Attachments:**
- [Video demonstrating the issue](https://github.com/user-attachments/assets/74327fc8-08ea-4f24-9148-f6f7bd9b6c4e)
- In the video above when you suddenly see hyprlock appearing is when I press the keybind for going out of fullscreen mode. As soon as the app leaves fullscreen mode you can see hyprlock appears on that monitor aswell.

**Comment by Arqamz** [comment]
Please try reproducing it on a setup with 2 monitors so you can see the difference. It's not very clear in the video when I press the keybind for hyprlock (I could tell because my other monitor that is not being recorded would have hyprlock launched on it but monitor 1 would still be showing my fullscreen-ed application). 

Terminal used: Foot
Operating System: NIXOS

**Comment by Arqamz** [comment]
I'm on nixpkgs stable.

**Comment by Arqamz** [comment]
sorry lol. Also on nixpkgs 24.05 stable. SearchNixos says this is Version **0.41.2**

**Comment by vaxerski** [comment]
`hyprctl version`

**Comment by Arqamz** [comment]
![image](https://github.com/user-attachments/assets/b76a71eb-c71c-41af-8f7f-3f6d213ab8aa)

**Comment by vaxerski** [comment]
great, I love nix. Both issues you posted (this and #437) are bugs that were present in old hyprland versions. My guess is that you are _not_ on 0.41.2

**Comment by Arqamz** [comment]
> My guess is that you are _not_ on 0.41.2

I just installed and enabled it through pkgs, I'm not sure what version it is but the maintainer/the website says it's version 0.41.2. I'm also pretty sure my hl is the latest aquamarine version, because my env for setting the gpu broke today.

**Comment by vaxerski** [comment]
that is really odd then. Can't repro. @PaideiaDilemma can't either, right?

**Comment by PaideiaDilemma** [comment]
no i can't repro.
also not with NixOS 24.05's versions of hyprland and hyprlock

**Comment by PaideiaDilemma** [comment]
> I just installed and enabled it through pkgs, I'm not sure what version it is but the maintainer/the website says it's version 0.41.2. I'm also pretty sure my hl is the latest aquamarine version, because my env for setting the gpu broke today.

If you are on LATEST NixOs 24.05, you are on tag 0.41.2, so no aquamarine. Your nixos configuration seems like you build your config with whatever version of nixpkgs you have locally.

Please post output of `nixos-version`.

**Comment by fufexan** [comment]
> ![image](https://private-user-images.githubusercontent.com/114855665/351361561-b76a71eb-c71c-41af-8f7f-3f6d213ab8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTczODgsIm5iZiI6MTcyMTc1NzA4OCwicGF0aCI6Ii8xMTQ4NTU2NjUvMzUxMzYxNTYxLWI3NmE3MWViLWM3MWMtNDFhZi04ZjdmLTNmNmQyMTNhYjhhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxNzUxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2QyZTc3YThiYjc1ZDc4ZjM2MzViMWFiZTUxZWMzNTc0NTY1YTk2MzA0ZTRhZDY0ODBmNjAxZDhiNTdjZTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QVC5vR-zWxrFaY_8aVnWqbGqqKDHoKR1s272fgD3BIE)

There is no way this is from either Nixpkgs or from the flake. They both provide info in `hyprctl version`. How have you compiled hyprland?

**Comment by Arqamz** [comment]
It's hardly been a few weeks since I've installed nixos.

`nixos-version
24.05.1503.752c634c09ce (Uakari)`

`nix --version
nix (Nix) 2.18.2`

You can have a look at my configuration files. Its all really standard I dont use home-manager or flakes [https://github.com/Arqamz/dotfiles-nixos-hyprland/tree/main/nixos](nixos-configuration)

**Comment by PaideiaDilemma** [comment]
According to your nixos-version, you are on hyprland commit `f15513309b24790099d42974274eb23f66f7c985` (See [here](https://github.com/NixOS/nixpkgs/blob/752c634c09ceb50c45e751f8791cb45cb3d46c9e/pkgs/applications/window-managers/hyprwm/hyprland/default.nix#L62C12-L62C52)), which is from May 5.

please update your channel and rebuild your config.

**Comment by PaideiaDilemma** [comment]
Can we close this and #437?

Both of these issues are present in old versions of Hyprland, when it initially switched to it's own implementation of `ext-session-lock-v1`.
