### ISSUE TITLE
Improve default behaviour with no config file

### ISSUE THREAD

**Issue by tristanbeedell** [hyprwm/hyprlock#450]
### Description

Currently, if you have not made a config file, hyprlock exits immediately with an error
```
[CRITICAL] ConfigManager threw: Could not find config in HOME, XDG_CONFIG_HOME, XDG_CONFIG_DIRS or /etc/hypr.
```

I think it would be preferable log a warning and continue, as it is a little confusing if you have this set up for example with hypridle and it isn't doing anything.

**Comment by vaxerski** [comment]
hyprlock with no config is more confusing than anything, as it will not render anything

**Comment by fufexan** [comment]
@tristanbeedell can you try with c7fa502?
