### ISSUE TITLE
Hyprlock does not start NixOS: EGL_EXT_platform_base not supported

### ISSUE THREAD

**Issue by DariusChit** [hyprwm/hyprlock#454]
### Regression?

Yes

### Hyprlock Info and Version

version: c7fa5026c074dc1670a6665cdfece41d920d35b1
<details> <summary>Hyprlock config</summary>

```sh
background {
  monitor=
  blur_passes=4
  brightness=0.817200
  contrast=0.891600
  noise=0.011700
  path=screenshot
  vibrancy=0.169600
  vibrancy_darkness=0.000000
}

general {
  grace=3
  hide_cursor=true
  no_fade_in=false
}

input-field {
  monitor=
  size=250, 60
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  fade_on_empty=false
  font_color=rgb(200, 200, 200)
  halign=center
  hide_input=false
  inner_color=rgba(0, 0, 0, 0.5)
  outer_color=rgba(0, 0, 0, 0)
  outline_thickness=2
  placeholder_text=<i><span foreground="##cdd6f4">󰌆 </span></i>

  position=0, -120
  valign=center
}

label {
  monitor=
  color=rgba(205, 214, 244, 1)
  font_family=JetBrains Mono Nerd Font Mono ExtraBold
  font_size=120
  halign=center
  position=0, -300
  text=cmd[update:1000] echo "$(date +"%H:%M")"

  valign=top
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4141e6755022edc19cd37cd7ad077a93b3bae5bd  ().
Date: 2024-08-02
Tag: , commits: 4141e6755022edc19cd37cd7ad077a93b3bae5bd

flags: (if any)


System Information:
System name: Linux
Node name: LeMachine
Release: 6.10.2
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul 27 09:40:36 UTC 2024


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600] [1002:7480] (rev c1) (prog-if 00 [VGA controller])
c5:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240731.9f918d6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:


```

</details>

### Description

Does not start at all.
Only output: `[CRITICAL] Hyprlock threw: EGL_EXT_platform_base not supported`

### How to reproduce

run `hyprlock`

### Crash reports, logs, images, videos

`hyprlock -v` == `[CRITICAL] Hyprlock threw: EGL_EXT_platform_base not supported`

hypridle logs: https://gist.github.com/DariusChit/7795fea6c9bc0e164663f53c70719b72

Nothing interesting in hyprland logs.

**Comment by vaxerski** [comment]
this is a problem with your kernel or mesa I am afraid. Please note kernel 6.10 has some major amdgpu issues and I'd recommend downgrading to 6.9.

**Comment by DariusChit** [comment]
> this is a problem with your kernel or mesa I am afraid. Please note kernel 6.10 has some major amdgpu issues and I'd recommend downgrading to 6.9.
> 
> 

Alright thanks

**Comment by DariusChit** [comment]
@vaxerski 
Hey the only thing that fixed this was downgrading from the git version to the latest release.

**Comment by vaxerski** [comment]
of hyprlock? bisect then

**Comment by DariusChit** [comment]
I've been testing it using `nix build`, using the hyprlock flake always produces the same error even from the release commit but the `nixpkgs` version works, so i'm going to investigate in when I have time.

**Comment by PaideiaDilemma** [comment]
Hey @DariusChit.
With nix you need to make sure the hyprlock flake's version of nixpkgs matches with your current system. Otherwise you will get mesa api version mismatches.
I usually do this by looking up die current nixpkgs version of my system and then I use `nix flake lock --override-input nixpkgs github:NixOS/nixpkgs\?ref=<hash>`

**Comment by DariusChit** [comment]
> nix flake lock --override-input nixpkgs github:NixOS/nixpkgs\?ref=<hash>

Thank you very much.
My nixpkgs inputs were out of sync in my config flake. It all works nicely now :+1:.
