### ISSUE TITLE
(RGBA) Borders are just slightly larger shapes with a full fill 

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [hyprwm/hyprlock#458]
### Regression?

No

### Hyprlock Info and Version

0.4.1
<details> <summary>Hyprlock config</summary>

```sh

shape {
    monitor =
    size = 360, 60
    color = rgba(17, 17, 17, 0.15)
    rounding = -1
    border_size = 8
    border_color = rgba(0, 207, 230, 0.5)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, 80
    halign = center
    valign = center
}

```

</details>****

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: joao-archlinux-lenovo
Release: 6.10.3-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


GPU information:
63:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

The above snippet of my config draws an oblong shape that is meant to have a translucent border and a translucent background. However, it seems like the border is not actually a border but a slightly scaled up version of the defined shape and hence, the both colours end up mixing. Hence, borders do not work when using rgba. 

### How to reproduce

Include the shape widget into your config and lock the screen.

**Comment by fybx** [comment]
bump

**Comment by PaideiaDilemma** [comment]
do we want gradient as well?

**Comment by fybx** [comment]
> do we want gradient as well?

it doesn't fit in with my tastes, but why stop innovation just for me ^^

**Comment by PaideiaDilemma** [comment]
Yeah same. personally i wouldn't use it.
My plan is just to port the border shader from hyprland to hyprlock. That shader works with gradients, so it would be easy to just add them to hyprlock as well.

**Comment by PaideiaDilemma** [comment]
@fybx wanna test my pr?
