### ISSUE TITLE
fail_text/fail_color are broken

### ISSUE THREAD

**Issue by wxifze** [hyprwm/hyprlock#468]
### Regression?

No

### Hyprlock Info and Version

hyprlock-0.4.1-1.fc40.src.rpm
<details> <summary>Hyprlock config</summary>

```sh
input-field {
	outline_thickness = 0
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: redacted
Release: 6.10.6-200.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev d2) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:

```

</details>

### Description

As per [documentation](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/):

> fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color

> When outline_thickness set to 0, the color of the inner box will be changed instead of the outer.

So when `outline_thickness` set to 0 and authentication fails, both the text an the box will the same color. It is impossible to set them to different colors.

But the box is colored "correctly" only for the first authentication failure. For all subsequent failures it is colored `check_color` for some reason.

And the icing on the cake: `swap_font_color` has no effect on `fail_text`.

### How to reproduce

1. Set `outline_thickness = 0`.
2. Fail authentication. **`fail_text` is unreadable.**
3. Fail authentication again. **`fail_text` is readable, but the box color is wrong.**
4. Repeat 1-3 with `swap_font_color = true`. **No difference.**

**Comment by PaideiaDilemma** [comment]
For now you can mitigate this by using pango markup to set the color of the fail text like this: `fail_text=<span foreground="black">$FAIL</span>`.

But it seems like the `swap_font_color` is actually broken and the behavior with `outline_thickness = 0` as well.
