### ISSUE TITLE
Add placeholder_font for input field.

### ISSUE THREAD

**Issue by Sounak008** [hyprwm/hyprlock#471]
### Description

Please add a placeholder text font changing option for the input field. It's hard-coded to be Sans. It would be really nice if you did so, then we can match our theme more nicely. 

Thank you 🙏

**Comment by fufexan** [comment]
You can change the font using [Pango Markup](https://docs.gtk.org/Pango/pango_markup.html#the-span-attributes).
Also, if you're using the same font theme-wide I'd suggest setting it as the default for `sans-serif` in fontconfig.

**Comment by Sounak008** [comment]
> You can change the font using [Pango Markup](https://docs.gtk.org/Pango/pango_markup.html#the-span-attributes). Also, if you're using the same font theme-wide I'd suggest setting it as the default for `sans-serif` in fontconfig.

Can you tell me more about fontconfig please? Where is the file located? Or am I misunderstanding something? How do I get fontconfig? And thanks about that pango markup thing.

**Comment by fufexan** [comment]
Fontconfig has multiple configuration files, either in the system directories or in your user's config directory. You should already have fontconfig as most GUI programs depend on it.

You can see more about it here https://wiki.archlinux.org/title/Font_configuration#Fontconfig_configuration.
