### ISSUE TITLE
using a symlink to an image doesnt work

### ISSUE THREAD

**Issue by dqrk0jeste** [hyprwm/hyprlock#472]
### Regression?

No

### Hyprlock Info and Version

<Enter your hyprlock version here>
<details> <summary>Hyprlock config</summary>

```sh
background {
  monitor =
  path = ~/image_sym
  blur_passes = 2
  contrast = 0.8916
  brightness = 0.8172
  vibrancy = 0.1696
  vibrancy_darkness = 0.0
}

general {
  ignore_empty_input = true
  no_fade_in = false
  grace = 0
  disable_loading_bar = false
}

input-field {
  monitor =
  size = 600, 60
  dots_size = 0.4
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgba(0, 0, 0, 0)
  font_color = rgb(205, 214, 244)
  fade_on_empty = false
  placeholder_text = 
  check_color = rgba(0, 0, 0, 0)
  fail_text = 
  fail_color = rgba(0, 0, 0, 0)
  hide_input = false
  position = 0, 200
  halign = center
  valign = bottom
}

# time
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
  color = rgba(216, 222, 233, 0.75)
  font_size = 130
  font_family = Poppins
  position = 0, 300
  halign = center
  valign = center
}

# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
  color = rgba(216, 222, 233, 0.5)
  font_size = 30
  font_family = Poppins
  position = 0, 200
  halign = center
  valign = center
}

# current song
label {
  monitor =
  text = cmd[update:1000] echo "$(~/scripts/song.sh)" 
  color = rgba(255, 255, 255, 0.7)
  font_size = 18
  font_family = Poppins
  position = 0, 60
  halign = center
  valign = bottom
}

```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [Iris Xe Graphics] [8086:46a8] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

i am using a symlink for syncing various backgrounds. when the symlink is simply named current_wallpaper with no extension, hyprlock just doesnt seem to pick up its filetype, which makes it fail with 
```sh
[ERR] unrecognized image format of <image_path>
```
it does work when an image name is specified without an extension, so this is just something to do with symlinks.

current workaround is to name the symlink current_wallpaper.png, which works, but now all my wallpapers have to be pngs.

### How to reproduce

have an image called `image` in home directory.
put this line as an image path in hyprlock.conf
```sh  
path = ~/image
```
it works
make a symlink by
```sh  
ln -s ~/image ~/image_sym
```
if you now use 
```sh  
path = ~/image_sym
``` 
as the path it will fail with 
```sh
[ERR] unrecognized image format of /home/you/image_sym
```
renaming the symlink to image_sym.png and changing it in hyprlock.conf fixes it, but at a cost of the actual image now needing to be a png.

**Comment by dqrk0jeste** [comment]
after a bit of digging, it fails in https://github.com/hyprwm/hyprlock/blob/main/src/renderer/AsyncResourceGatherer.cpp#L108 that is with this magic stuff. still dont really understand why only with symlinks.

**Comment by dqrk0jeste** [comment]
a but more digging in magic manuals, maybe its just needed to add a flag while opening the file
       MAGIC_SYMLINK   If the file queried is a symlink, follow it.

**Comment by vaxerski** [comment]
mrs welcome

**Comment by qxb3** [comment]
For some reason, this issue still persists, at least for me. Same repro.

`hyprlock version: hyprlock-git 0.5.0.r17.gcc7ffe73-1` (latest)

**Comment by dqrk0jeste** [comment]
I can't seem to find the fix i have provided in the latest commit, will take a better look and bisect it if needed.

**Comment by qxb3** [comment]
i take a bit of a look on the code and it seems that magic isn't being used now and the fix has been ditched somewhere. This issue should be reopened.

**Comment by nuexq** [comment]
it seem that it got broken again and the fix got ditched again.

**Comment by nuexq** [comment]
it seem that it got broken again and the fix got ditched again.
