### ISSUE TITLE
Add options to enable brightness shortcut

### ISSUE THREAD

**Issue by Frost-Phoenix** [hyprwm/hyprlock#479]
### Description

When using hyprlock on my laptop I thought I would be really nice to be able to change the screen brightness. The main benefit of this would be the possibility of locking the laptop and to "turn of" the screen, mainly to save on battery. 

Best wishes, Frost-Phoenix.

**Comment by fufexan** [comment]
You can add keybinds to change the brightness in Hyprland. These have to have the `l` flag so that they also work on screen lockers. See https://wiki.hyprland.org/Configuring/Binds/#bind-flags.

Other compositors should also have similar bind mechanisms.

**Comment by Frost-Phoenix** [comment]
Thanks, I didn't know about that. :)
