### ISSUE TITLE
[REQ] Grace Period 

### ISSUE THREAD

**Issue by wxllow** [hyprwm/hyprlock#48]
It would be great if there was a feature where hyprlock could be started with a grace period where the password wont be required if the user moves the mouse/uses the keyboard within `x` seconds. Something similar to the --grace argument in [swaylock-effects-improved](https://github.com/Xenfo/swaylock-effects-improved)

Ex.

```
hyprlock --grace 5
```

**Comment by pschmitt** [comment]
https://git.sr.ht/~emersion/chayang can do this (and only this) already.

**Comment by wxllow** [comment]
> https://git.sr.ht/~emersion/chayang can do this (and only this) already.

maybe im picky but i still think it'd be nicer to be have my lock screen shown while also allowing me to have a grace period

**Comment by wxllow** [comment]
but if it's out of scope, thats fair
