### ISSUE TITLE
Hyprlock always displays UTC time even in non-UTC timezones after the most recent tzdata update

### ISSUE THREAD

**Issue by odomingao** [hyprwm/hyprlock#484]
### Regression?

Yes

### Hyprlock Info and Version

<Enter your hyprlock version here>
<details> <summary>Hyprlock config</summary>

```sh
<Paste your hyprlock config here>
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

tzdata's latest update causes non-UTC timezones to display UTC time ($TIME). I'm not providing specific information to my system above because it should be irrelevant. Other projects like Waybar are also affected (see [here](https://github.com/Alexays/Waybar/issues/3584) ). This issue is fixed by downgrading tzdata but this isn't a good solution. Not sure if this is a Hyprlock/Waybar bug or a tzdata bug, but I figured that I should report regardless.

### How to reproduce

Be in a timezone that is not UTC, and update tzdata to 2024b-1

**Comment by vaxerski** [comment]
not a hyprlock issue, if anything, tzdata/stdlib issue
