### ISSUE TITLE
[Feature] directly use background of Hyprland

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/hyprlock#486]
### Description

Dear Developer,
I'm now trying to build something similar to MacOS dynamic lock screen using hyprwinwrap+mpv, I'm now having trouble in make mpv show on the background of lockscreen, so I'd like to ack if it's possible to make hyprwinwrap work on the lock screen? 

All the best

**Comment by vaxerski** [comment]
not possible

**Comment by gfhdhytghd** [comment]
I shove this by use coney us a fake lock screen
