### ISSUE TITLE
Realtime blurred desktop

### ISSUE THREAD

**Issue by BlueskyFR** [hyprwm/hyprlock#492]
Hi!

Is it possible to view the live desktop through the lockscreen ?
And is it possible to also blur it live/in realtime?

**Comment by vaxerski** [comment]
no

**Comment by BlueskyFR** [comment]
> no

Why?

**Comment by vaxerski** [comment]
cuz its not possible

**Comment by BlueskyFR** [comment]
> cuz its not possible

Even when using a backend like Picom or something like that it has built-in blurring?

Also I saw there is a configuration option in hyprlock.conf talking about a see-through/transparent shape, doesn't it do that?

Because AFAIK Hyprlock can take a screenshot of the screen at launch but I'd just like it to display a transparent window on top simply blocking keyboard input for instance 😁

**Comment by vaxerski** [comment]
not possible, again

**Comment by BlueskyFR** [comment]
> not possible, again

At this point you're not even answering anymore so I'll just drop it, never saw this type of behavior on GitHub yet.

**Comment by fufexan** [comment]
Technically the protocol does not even allow transparency.

**Comment by vaxerski** [comment]
> At this point you're not even answering anymore so I'll just drop it, never saw this type of behavior on GitHub yet.

and you don't take "not possible" as an answer. It's not allowed. It's not how lockscreens work. I don't see a point in writing a 2-page essay on why, especially since the knowledge is quite useless to you.

**Comment by BlueskyFR** [comment]
> > At this point you're not even answering anymore so I'll just drop it, never saw this type of behavior on GitHub yet.
> 
> and you don't take "not possible" as an answer. It's not allowed. It's not how lockscreens work. I don't see a point in writing a 2-page essay on why, especially since the knowledge is quite useless to you.

Well turns out I was legit interested in it, I'm not writing 2 paragraphs just to ask for another way to say "not possible" duh
