### ISSUE TITLE
allow $TIME for 12hr instead of only supporting 24hr

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/hyprlock#493]
### Description

Allowing that variable to be 12hr instead of just 24hr, can currently do that via date command

**Comment by vaxerski** [comment]
why would you want to use an inferior time format?

**Comment by littleblack111** [comment]
personal preference

**Comment by lisk77** [comment]
![7o31xn-3647212280](https://github.com/user-attachments/assets/f661eed3-cc97-463f-aab3-d7c1be5eb8df)
