### ISSUE TITLE
Hyprlock does not follow display scaling on Sway

### ISSUE THREAD

**Issue by nydragon** [hyprwm/hyprlock#498]
### Regression?

No

### Hyprlock Info and Version

v0.4.1
<details> <summary>Hyprlock config</summary>

```sh
background {
  blur_passes=3
  blur_size=8
  path=screenshot
}

general {
  hide_cursor=true
  no_fade_in=false
}

input-field {
  monitor=
  size=200, 50
  dots_center=true
  fade_on_empty=false
  font_color=rgb(202, 211, 245)
  inner_color=rgb(91, 96, 120)
  outer_color=rgb(24, 25, 38)
  outline_thickness=5
  placeholder_text=<span foreground="##cad3f5">Password...</span>
  position=0, -80
  shadow_passes=2
}

```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
sway 1.9
```

</details>

### Description

I set sway to scale my monitor *2, however, hyprlock is not respecting that and displaying only in the lower quarter of my monitor. This is the case as soon as any scaling is being used in sway.

### How to reproduce

Set sway to scale a display and use hyprlock.

### Crash reports, logs, images, videos

[logs.txt](https://github.com/user-attachments/files/17132109/logs.txt)

**Comment by nydragon** [comment]
Thanks for the quick response!

I get the following error tho:

```
╰─>$ nrun github:hyprwm/hyprlock/9393a3e94d837229714e28041427709756033f5a 
[CRITICAL] Hyprlock threw: EGL_EXT_platform_base not supported
```
also occurs on HEAD and v0.4.1

**Comment by PaideiaDilemma** [comment]
Using `nix run` will use the nixpkgs version that `flake.lock` in the hyprlock repo specifies.
That leads to mesa version mismatches with your system. You need to build it with the nixpkgs version you currently use on your system.

AFAIK easiest way to test it out is to clone hyprlock, then use `nix flake lock --override-input nixpkgs github:Nixos/nixpkgs/<your nixpkgs hash>` and then you can `nix run .`

**Comment by nydragon** [comment]
Seems to work perfectly, thanks a lot for your help!

Could it makes sense to add the run instruction to the readme ? `--override-input` can also be used on `nix run`, so `nix run github:hyprwm/hyprlock --override-input nixpkgs nixpkgs` (to use the system nixpkgs).

**Comment by PaideiaDilemma** [comment]
> Could it makes sense to add the run instruction to the readme ? --override-input can also be used on nix run, so nix run github:hyprwm/hyprlock --override-input nixpkgs nixpkgs (to use the system nixpkgs).

Idk if it fits in the README of hyprlock, since it is very nix specific.
But I actually did not know that `nix run` also accepts `--override-input`.
That is cool :)

**Comment by fufexan** [comment]
I'll add such info in the wiki, if I remember to. PRs are also welcome.
