### ISSUE TITLE
Crash when using $TIME

### ISSUE THREAD

**Issue by 2Belette** [hyprwm/hyprlock#519]
### Regression?

Yes

### Hyprlock Info and Version

hyprlock-0.4.1 @ FreeBSD

<details> <summary>Hyprlock config</summary>

```sh
label {
    monitor =
#    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 60
    font_family = Noto Sans
    position = -30, 0
    halign = right
    valign = top
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4520b30d498daca8079365bdb909a8dea38e8d55 portbld (?).
Date: Wed Oct  9 12:54:39 UTC 2024
Tag: v0.44.1, commits: ?
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: FreeBSD
Node name: xps
Release: 14.1-RELEASE-p5
Version: FreeBSD 14.1-RELEASE-p5 GENERIC


GPU information: 
vgapci0@pci0:0:2:0:	class=0x030000 rev=0x0c hdr=0x00 vendor=0x8086 device=0x46a6 subvendor=0x1028 subdevice=0x0af3
    vendor     = 'Intel Corporation'
    device     = 'Alder Lake-P GT2 [Iris Xe Graphics]'
    class      = display
    subclass   = VGA


os-release: NAME=FreeBSD
VERSION="14.1-RELEASE-p5"
VERSION_ID="14.1"
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 14.1-RELEASE-p5"
CPE_NAME="cpe:/o:freebsd:freebsd:14.1"
HOME_URL="https://FreeBSD.org/"
BUG_REPORT_URL="https://bugs.FreeBSD.org/"


plugins:
```

</details>

### Description

This is crashing hyprlock with no hint into logging nor verbose mode.
If I comment the line with $TIME and uncommenting the line above, everything is working well.
It was working before.

### How to reproduce

using $TIME

**Comment by PaideiaDilemma** [comment]
You probably did not set up your timezone.
I opened #527 to handle this a bit more gracefully.

**Comment by 2Belette** [comment]
Thanks !
@PaideiaDilemma do you mean to set timezone on hyprlock specifically or in my system ? (in my system it is setup; my /etc/localtime is set to /usr/share/zoneinfo/Europe/Paris)
