### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by PolarT-py** [hyprwm/hyprlock#521]
How can you add transition animations when you enter/exit hyprlock. Not sure if its supposed to be like this, but for me when I lock my screen theres this fading animation into hyprlock, but when i get out, it just exits without animation. Pretty sure I've seen people using hyprlock with animations on it

**Comment by Sasikuttan2163** [comment]
Can you check whether you have the variable general:no_fade_out set to true? That could be the reason why it's not fading out on exit

**Comment by aaron-randreth** [comment]
Your `XDG_CURRENT_DESKTOP` not being set to "Hyprland" could also be a reason. Mine was set to something else, so the fade in was working but not the fade out. I don't know why the fade out is disabled for other desktops ? I have tried it on `river` by keeping `XDG_CURRENT_DESKTOP` set to "Hyprland", and it seemed to work fine.

**Comment by PolarT-py** [comment]
![image](https://github.com/user-attachments/assets/23e9cfd1-2f13-4b7a-8e28-54ac59f94c8d)
Apparently my xdg current desktop is nothing??

Correct me if im wrong, i ran these commands to set my xdg current desktop to "Hyprland" and it still doesnt work
❯ export XDG_CURRENT_DESKTOP=Hyprland
❯ source ~/.zshrc

Here is the generald general section of my hyprlock config
general {
	no_fade_out = false
	ignore_empty_input = true
}

**Comment by vaxerski** [comment]
because it sets the environment in your terminal not hyprland. Launch hyprland from the tty, not whatever shitty login manager you use, or add this env to your hyprland config and restart

**Comment by PaideiaDilemma** [comment]
Regarding the fade out:
The reason for the fade out not working on other compositors is that you can only fade back (by just using opacity) after you unlocked, but then lock surfaces are no longer used. It actually fades to black in river and sway when you force `XDG_CURRENT_DESKTOP`. 

Maybe a bit of a rough edge, but currently as long as there is a lock screen surface, the workspace is rendered below the lock screen client in Hyprland to allow for simple and smooth fade in/out and async screenshot at startup. if there is no lock surface, it will draw the upsie screen.

I guess this situation could be improved a bit by just presenting the last frame below the lock screen client in Hyprland.
The alternatives for implementing fade in/out rely on screenshots before locking which would probably sacrifice a bit of smoothness.
Actually wanted to know what vaxerski thinks about this, so i am taking this opportunity. Any opinions?

**Comment by vaxerski** [comment]
> Actually wanted to know what vaxerski thinks about this, so i am taking this opportunity. Any opinions?

> The alternatives for implementing fade in/out rely on screenshots before locking which would probably sacrifice a bit of smoothness.

reasonable.

**Comment by PolarT-py** [comment]
oof turns out i just needed reboot

**Comment by aaron-randreth** [comment]
> oof turns out i just needed reboot
@PolarT-py Don't forget to close this if your problem is resolved ;)
