### ISSUE TITLE
make outer_color a border instead of drawing a filled box

### ISSUE THREAD

**Issue by fybx** [hyprwm/hyprlock#523]
### Description

as far as I'm aware of, there's no way to have a transparent inner_color field with a border. only way to achieve transparency is to make inner_color and outer_color fields transparent, but it still will get colored when status changes to fail & check.

i believe this issue could be resolved by simply making the outer_color draw the border around the field instead of drawing a filled, bigger one underneath it.

thanks for your time.

**Comment by PaideiaDilemma** [comment]
dupe of #458
