### ISSUE TITLE
Integrate Howdy Unlock

### ISSUE THREAD

**Issue by londeril** [hyprwm/hyprlock#533]
### Description

Hi :) 

Hyprlock is fantastic! I like it very much!

What would make it even more awesome would be if it would allow me to unlock with Howdy's Face-Unlock (much like the fprintd integration).

What would make it even more awesome would be the option to only allow Face-Unlock before the Machine suspends - I'd like to enter my password the first time after resume from suspend and then use face-unlock until I suspend my machine again. I think that would be a good compromise between security and ease of use. :)

**Comment by fufexan** [comment]
Howdy already works when pressing enter. Or do you want hyprlock to automatically start howdy?

**Comment by londeril** [comment]
yeah - sorry I saw the posts after I created this one... Howdy stable didn't work for me - howdy-beta-git works - but it out unlocks even if I cover my camera... will tinker some more - and close this :) 

thanks for the fast reply!

**Comment by alba4k** [comment]
@fufexan I mean an option to automatically start howdy, just like what we can currently do with hyprlock, would be nice
