### ISSUE TITLE
hide "running on tty unknown" message

### ISSUE THREAD

**Issue by biskyy** [hyprwm/hyprlock#540]
### Description

if hyprlock is run from terminal or on startup(exec-once) then a text will appear in the top left corner of the screen saying: "running on tty unknown". im not sure whether it's a bug or not so im posting this a feature request. 
my question is: can this text be disabled? i dont want to see it

hyprlock 0.5.0
hyprland 0.44.1
linux-zen 6.11.5

**Comment by vaxerski** [comment]
not hyprlock. Assuming you're on arch. Likely lock is taking too long to start and takes a screenshot of the "lock dead" screen, but the arch packagers have had broken assets under hyprland for months now (almost a year iirc?) and they refuse to fix them.
