### ISSUE TITLE
Fingerprint can block hyprlock startup resulting in the recovery screen flashing

### ISSUE THREAD

**Issue by PaideiaDilemma** [hyprwm/hyprlock#543]
### Regression?

No

### Hyprlock Info and Version

0.5.0, latest
<details> <summary>Hyprlock config</summary>

```sh
general {
    enable_fingerprint = true
}

background {
    monitor = #all
    color = rgba(0, 0, 255, 0.8)
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch  at commit 514e0ff509f3bf4c98515f08216ac2eeb8797517  ().
Date: 2024-11-03
Tag: , commits: 
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: desktop
Release: 6.11.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov  1 01:02:44 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c1) (prog-if 00 [VGA controller])
0e:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev cb) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241102.7ffd9ae"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=desktop
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
```

</details>

### Description

A user on discord reported the recovery/upsie screen flashing when `enable_fingerprint=1`.
It turned out that calling the `Claim` dbus method blocked for a few hundred milliseconds keeping hyprlock from drawing it's first frame.

Can be mitigated a bit by putting the call to `startVerify` in a timer, instead of doing it on startup. But it would likely still block the eventloop when it is actually called.
Or it could be fixed by moving the startup for the fingerprint stuff into a separate thread.

CC @moggiesir

### How to reproduce

having a framework 13 sensor???

**Comment by moggiesir** [comment]
There is an async version of the dbus method invoker that we could use instead so as to not block.
