### ISSUE TITLE
No input field and PAM error on NixOS

### ISSUE THREAD

**Issue by Computerdores** [hyprwm/hyprlock#545]
### Regression?

No

### Hyprlock Info and Version

hyprlock version: 0.5.0 / 0.3.0
<details> <summary>Hyprlock config</summary>

```sh
background = {
    blur_passes=3
    blur_size=8
    path=screenshot
}
general = {
    grace=300
    hide_cursor=true
    ignore_empty_input=true
    no_fade_in=false
}
input-field {
    size=200, 50
    halign=center
    outline_thickness=5
    placeholder_text=Password...
    position=0, -20
    valign=center
}
label {
    halign=center
    position=0, 80
    text=Test123, $USER
    valign=center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch v0.44.1-b at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: 2024-10-09
Tag: v0.44.1, commits: 4520b30d498daca8079365bdb909a8dea38e8d55
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: Linux
Node name: nixos-testbed
Release: 6.6.58
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 22 13:46:36 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 630 [8086:5912] (rev 04) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241029.30c9efe"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
```

</details>

### Description

Running hyprlock shows the lock screen with the configured label, however there is no input field. Furthermore giving any input (keyboard, mouse buttons, mouse movement) immediately dismisses the lock screen with no error.

If I change from the NixOS unstable packages (hyprlock 0.5.0) to the NixOS 24.05 packages (hyprlock version 0.3.0) then the behaviour stays the same, but the following errors show up:
```
[ERR] auth: Authentication failed for hyprlock
```

and in journalctl:
```
pam_unix(hyprlock:auth): conversation failed
pam_unix(hyprlock:auth): auth could not identify password for [jann]
```

I haven't used hyprlock before so besides 0.3.0 and 0.5.0 I don't know which versions are affected.

### How to reproduce

Using [this NixOS configuration](https://github.com/Computerdores/nix-hyprland-environment/tree/hyprlock-bug-unstable) (or the [NixOS 24.05 version](https://github.com/Computerdores/nix-hyprland-environment/tree/hyprlock-bug)):
- login as `jann` with password `1`
- run `Hyprland`
- press SUPER + Q to open terminal
- run `hyprlock`

### Crash reports, logs, images, videos

[logs for 25.05 packages (hyprlock 0.3.0)](https://gist.github.com/Computerdores/733d6c52169d9ca5ca93d91c78e54cc4)
[logs for unstable packages (hyprlock 0.5.0)](https://gist.github.com/Computerdores/c065b856a659c16a341e7caa09259f9d)

This is what the lock screen looks like:
![image](https://github.com/user-attachments/assets/5d84f36a-30eb-4b4b-8495-7bedde625f9a)

**Comment by fufexan** [comment]
The wiki says the `monitor` field can be left empty, not that it can be omitted. Not sure if this changes anything, but it's worth a try.

**Comment by Computerdores** [comment]
Not sure if there are other issues with omitting it, but it doesn't affect this bug according to my testing.

**Comment by fufexan** [comment]
Not sure then. Can you try using the flake?

**Comment by PaideiaDilemma** [comment]
uff

> Running hyprlock shows the lock screen with the configured label, however there is no input field. 

Yeah cause it is hidden because `input-field:hide_on_empty` is enabled per default.

> Furthermore giving any input (keyboard, mouse buttons, mouse movement) immediately dismisses the lock screen with no error.

You have `grace=300`!

Please just look into the wiki once before opening an issue.

The pam logs come from the fact that we just abort the conversation in case we do a grace unlock and `[ERR] auth: Authentication failed for hyprlock` is just shown whenever you enter the wrong password

**Comment by fufexan** [comment]
Thanks, I completely overlooked that. Closing.
