### ISSUE TITLE
Make Hyprlock work like SDDM

### ISSUE THREAD

**Issue by enessmr** [hyprwm/hyprlock#546]
### Description

If configured, it can replace SDDM.

Also take SDDM's ALL the features.

**Comment by fufexan** [comment]
Hyprlock is a lockscreen, not a display manager. It can't and never will be able to replace SDDM.

For limited purposes like autostarting Hyprland and auto-launching hyprlock as a "login screen", this works, sure.

**Comment by enessmr** [comment]
Thanks...

So I need to take ML4W's dotfiles then edit it a lot. (cause i cannot make that GUI text thingy)
I already configured Hyprland for it

**Comment by fufexan** [comment]
The best learning resource is creating your own configs that work for *you*. It will also be much easier to debug when things don't work.

Closing.

**Comment by enessmr** [comment]
But there IS a issue...

Also, you know? When Hyprlock DIES, it gives you a message that its died.
I got to rescue it in like 5 MINUTES!
So its MUCH more harder.

**Comment by fufexan** [comment]
Well it shouldn't die often. If you configure it (or your system) properly it should work fine.

**Comment by PaideiaDilemma** [comment]
The only conceivable way would be to use greetd-ipc and make hyprlock function as a greeter. Would not be easy though.

I think greetd uses an unprivileged user to run the greeter, which is nice, but also means that label commands will run as a different user.
 
One would roughly need to implement the following:
1. allow either session-lock-v1 or greetd ipc protocols
2. implement drawing either on sessionlock surfaces or on normal ones. (greeter would run within a basic wayland compositor. gtkgreet uses cage for example)
3. add a bunch of options to allow selecting the session and the user to login with. (passted via greetd-ipc)
4. add a way to disable widgets on either launch method.
5. ??

Combined with the amount of restructuring needed, it would probably come down to rewriting a bunch of stuff.
