### ISSUE TITLE
blurred background when color is used

### ISSUE THREAD

**Issue by barbiefan** [hyprwm/hyprlock#553]
### Description

Forgive my terminology, but:

Apply blur to background when color is used and alpha value is not 1.0

From my understanding composition is already done (because with alpha 0.5 I can see my desktop), so blur "shader" is not that farfetched to implement

When locked, I would like to see my live desktop but with a blur. Currently (correct me if I'm wrong) it is possible to have either transparent lockscreen or lockscreen with blurred screenshot, but not blurred transparent lockscreen

**Comment by PaideiaDilemma** [comment]
Two reasons why this is probably not going to be implemented:

1. Blurring works by applying operations on top of the frame to blur.
It's not like we can have a blur frame that we can just overlay on the desktop.
Blurring is frame by frame and not that fast, so blurring your entire desktop each frame is not a good idea in terms of efficiency and performance.
Blurring the color itself, which is what you suggested, would only dim the desktop. It would not blur it.

2. I would like to change a view things regarding Hyprland's session lock implementation. One of those things is not rendering the Desktop below, when there is a lock screen with lock screen surfaces. Then you would not be able to implement this at all.

**Comment by barbiefan** [comment]
1. I understand that blurring is computationally expensive, even so when blurring 4k screen for example. I'm not suggesting enabling blur for everyone as a default though.
Personally, I'm not that concerned with performance penalties. And it's not like I game when my lock is on.
I might be wrong but I think there are a lot of people who use terminal with blur, and opened alone it takes almost all of the screen. So a "this much" of people are already running into this "issue" (yeah, it would be another blur on top of what they are running, but still)

2. That's understandable.
However there is still an option to make it an option :D
Like there is still decoration:blur:new_optimizations

Dev time is invaluable though

**Comment by fufexan** [comment]
This is not allowed by the [protocol](https://wayland.app/protocols/ext-session-lock-v1#ext_session_lock_v1)
> The locked event indicates that the session is locked. This means that the compositor **must stop rendering** and providing input to normal clients. Instead the compositor must **blank all outputs with an opaque color** such that their normal content is fully hidden.

Not sure why Hyprland doesn't implement blanking all outputs, but it's not according to spec.

**Comment by barbiefan** [comment]
Oh I see!

I guess this functionality could be provided by less to spec, less secure, less-of-a-lock software in conjunction with window rules

Out of the question then

**Comment by PaideiaDilemma** [comment]
> Not sure why Hyprland doesn't implement blanking all outputs, but it's not in accordance with the spec

it does only when locked but no lock surface is present. Basically to not have to worry about fade-in/fade-out, as well as async screencopy.

But like i said, i want to remove that.
