### ISSUE TITLE
ability to log in without hitting Enter key 

### ISSUE THREAD

**Issue by victorballester7** [hyprwm/hyprlock#563]
### Description

It  would be nice to add an option that whenever the entered phrase matches the actual password, the log in process automatically starts, without having to click `Enter` key.

**Comment by fufexan** [comment]
PAM doesn't work like that. This would require checking the password on every keypress. However, PAM introduces a delay of a few seconds each time the password is wrong. This would make logging in a very painful experience.

**Comment by PaideiaDilemma** [comment]
However, an option like `general:autosubmit_at_length` would be possible.
But I also don't like that much, since you would leak your password length with that.
