### ISSUE TITLE
Incimpatible with swiping

### ISSUE THREAD

**Issue by freerig** [hyprwm/hyprlock#567]
### Regression?

No

### Hyprlock Info and Version

Hyprlock version 0.5.0

### Compositor Info and Version

<details><summary>Infos</summary>
<p>

Hyprland 0.45.0 built from branch  at commit b1003445953474b967464d4d0878955d37498647  ().
Date: 2024-11-22
Tag: , commits: 
built against aquamarine 0.5.0

flags set:
debug

System Information:
System name: Linux
Node name: home
Release: 6.6.62
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Nov 17 14:08:59 UTC 2024

</p>
</details> 

### Description

I have this in my hyprland config (Nix)
gestures = {
	workspace_swipe = true;
	workspace_swipe_touch = true;
	workspace_swipe_cancel_ratio = 0.1;
};

And when I swipe while hyprlock is enabled, I can swipe worspace

### How to reproduce

1. Buy a touchscreen
2. Add the config I mentioned earlier to hyprland (convert to hyprlang btw)
3. hyprlock
4. Swipe from edges
5. Unlock
6. See that you changed workspace

**Comment by vaxerski** [comment]
that's a hyprland issue
