### ISSUE TITLE
Setting blur_passes to non zero number zooms in wallpaper

### ISSUE THREAD

**Issue by matteo4375** [hyprwm/hyprlock#58]
blur_passes = 0
![2024-02-21T18:38:08,977239003-05:00](https://github.com/hyprwm/hyprlock/assets/160355435/79a904c8-952f-4f82-b248-cfaa8b896afe)
blur_passes = 1
![2024-02-21T18:38:43,054187699-05:00](https://github.com/hyprwm/hyprlock/assets/160355435/f71fc6f2-c859-4ce2-a2da-a3dc951fc633)
blur_passes = 2
![2024-02-21T18:39:39,139087766-05:00](https://github.com/hyprwm/hyprlock/assets/160355435/634626f5-b22c-47f8-be01-f756ce95fbdd)

```
background {
    monitor =
    path = $HOME/.config/hypr/wallpaper.png

     # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 1 # 0 disables blurring
    blur_size = 0
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}
```

**Comment by vaxerski** [comment]
right texture size mismach
