### ISSUE TITLE
Hyprlock 0.6.0 breaks outer_color when specified as a decimal

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/hyprlock#593]
### Regression?

Yes

### Hyprlock Info and Version

Hyprlock version 0.6.0
<details> <summary>Hyprlock config</summary>

```sh
input-field {
  size = 300, 250
  rounding = -1
  outline_thickness = 30
  outer_color = rgba(129, 162, 190, 85)
  inner_color = rgb(29, 31, 33)
  font_color = rgb(100, 100, 100)

  check_color = rgb(204, 136, 34)  # override outer_color while checking the pw (could take a while sometimes - pam lockouts)
  fail_color = rgb(204, 34, 34)  # override outer_color and fail message color if auth failed
  fail_transition = 500 # transition time in ms between normal outer_color and fail_color
  fail_text = # Leave this empty (amt of attempts and fail reason shown with labels)

  hide_input = true
  fade_on_empty = false
  placeholder_text = # Leave this empty

  position = 0, 0
  halign = center
  valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: voyager
Release: 6.12.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000


GPU information: 
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c4) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

For some reason, specifying the `outer_color` using `rgba` with decimal color channel values doesn't seem to work, leading to the outer color being invisible.

This became an issue after updating from hyprlock 0.5.0 to 0.6.0.

I also tried doing: `outer_color = rgba(129, 162, 190, 0.85)` instead of the `85` for alpha, but this still didn't work. However, using the hex  code: `outer_color = rgba(81a2bed8)` renders the circle properly. 

Note: This also applies to `check_color` & `fail_color`.

This might be a hyprlang issue rather than a hyprlock one, however, I'm not certain, I'm reporting it here as that's where I observed it.

### How to reproduce

Set `outer_color` in the `input-field` to an rgba value that uses decimal numbers to specify the individual color channels.

### Crash reports, logs, images, videos

When outer color is specified using decimal values:
![image](https://github.com/user-attachments/assets/7a30ed78-6f06-4b63-b3b8-db986a88c8b1)

When outer color is specified using a hex value:
![image](https://github.com/user-attachments/assets/7c83a095-a47e-408c-9664-e75c4ef9778e)

**Comment by gj-asai** [comment]
I see the same issue with `check_color`, `fail_color`, `capslock_color` and `numlock_color`. Maybe that's also what's causing #594?
`inner_color` and `font_color` seem to work correctly

**Comment by ItsDrike** [comment]
> I see the same issue with check_color, fail_color, capslock_color and numlock_color. Maybe that's also what's causing https://github.com/hyprwm/hyprlock/issues/594?

I did mention that `fail_color` & `check_color` also cause this. But `capslock_color` & `numlock_color` are a good shout, also with `bothlock_color` too.

> Maybe that's also what's causing https://github.com/hyprwm/hyprlock/issues/594?

Definitely not. This issue has to do with numlock & capslock colors taking precedence over fail_color & check_color. Also, that issue occurs in 0.5.0 too, this one is 0.6.0 only.

**Comment by PaideiaDilemma** [comment]
@ItsDrike regressor is https://github.com/hyprwm/hyprlock/commit/578246b9967dec77c56993dc55ca192d35ba9bb7
Works when removing spaces from the args e.g. `rgba(129,162,190, 85)`.
