### ISSUE TITLE
Hyprlock 0.5.0+ breaks check_color & fail_color

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/hyprlock#594]
### Regression?

Yes

### Hyprlock Info and Version

<Enter your hyprlock version here>
<details> <summary>Hyprlock config</summary>

```sh
# Use a swaylock-like circle, lighting up random segments as you type
input-field {
  size = 300, 250
  rounding = -1
  outline_thickness = 30
  outer_color = rgba(33ccffee)
  inner_color = rgb(29, 31, 33)
  font_color = rgb(100, 100, 100)

  check_color = rgb(204, 136, 34)  # override outer_color while checking the pw (could take a while sometimes - pam lockouts)
  fail_color = rgb(204, 34, 34)  # override outer_color and fail message color if auth failed
  fail_transition = 500 # transition time in ms between normal outer_color and fail_color
  fail_text = # Leave this empty (amt of attempts and fail reason shown with labels)

  hide_input = true
  fade_on_empty = false
  placeholder_text = # Leave this empty

  position = 0, 0
  halign = center
  valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: voyager
Release: 6.12.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000


GPU information: 
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c4) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Since hyprlock 0.5.0 the check_color & fail_color doesn't seem to be working. Last version where this did work for me was hyprlock 0.4.1 (since this version doesn't yet have `hyprlock --version`, all I can mention is that it was the officially packaged for arch linux: 0.4.1-1, but it should just be the one officially tagged on git as 0.4.1).

It seems that regardless of what color is specified for either `check_color` or `fail_color` variables, they have no effect and the outer color isn't changed while checking / on failure.

> [!NOTE]
> When I discussed this on discord with another person, they weren't able to reproduce this on 0.6.0, so I'm not entirely sure why this is happening on my machine.

### How to reproduce

Post-regression (with bug):

1. Install hyprlock as officially packaged for Arch
2. Use the attached hyprlock config 
3. Enter a wrong password
4. Observe no change in the outer color during both checking & failure

Pre-regression (no bug):

1. Install downgrade tool, to allow installing older versions of officially packaged arch packages
2. Run `sudo downgrade hyprlock` & pick version 0.4.1-1.
3. Use the attached hyprlock config
4. Enter a wrong password
5. Observe outer color changing both during checking & failure, as it should

### Crash reports, logs, images, videos

Pre-regression (with hyprlock 0.4.1-1):

https://github.com/user-attachments/assets/5beb3deb-6ea4-4817-acf4-f75cb55c553f

Post-regression (with hyprlock 0.6.0):

https://github.com/user-attachments/assets/6f99419e-deeb-4005-86bf-e5a4747a4b6e

**Comment by ItsDrike** [comment]
Upon doing some diff inspection, I found this hunk:

![image](https://github.com/user-attachments/assets/a8f641f9-96ac-4a17-88af-c9554cf9a003)

Numlock is the culprit, when it's on, the check/fail color doesn't take precedence, when it's off, it does actually work, that's also why the other person couldn't repro this (lol).

**Comment by PaideiaDilemma** [comment]
> Checking & failure colors should definitely take precedence over the numlock/capslock colors. The if statement for this should be moved above the one for check & fail colors.

I think you are right.

Its possible that i broke that because i did not realize that that was how it should work.

Anyways, this is not really a bug, but just a edge case that i did not thing about.
I will clean this up.
