### ISSUE TITLE
Deleting characters doesn't work

### ISSUE THREAD

**Issue by kamack38** [hyprwm/hyprlock#6]
After an unsuccessful login, the input field isn't cleared (if this is an unexpected behaviour) and pressing backspace doesn't remove characters in the input field

**Comment by vaxerski** [comment]
repro steps? stacktrace?

**Comment by vaxerski** [comment]
some fixes and cleanups in 013dfadee7bc3c9af7379e9cfe86cd542c90d72e

**Comment by alba4k** [comment]
I believe this issue is fixed? Although it would still be nice to have some feedback for when a given input is wrong

**Comment by vaxerski** [comment]
9074ff702d4dfcddcde49d38eb57eb4ad9ac3870
