### ISSUE TITLE
hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprlock

### ISSUE THREAD

**Issue by ravxen** [hyprwm/hyprlock#605]
### Regression?

No

### Hyprlock Info and Version

hyprlock 0.6.0
<details> <summary>Hyprlock config</summary>

```sh
Not needed since it's not a config issue
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
yprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: arch
Release: 6.12.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0) (prog-if 00 [VGA controller])
0e:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Granite Ridge [Radeon Graphics] [1002:13c0] (rev cb) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

When trying to update the system the update fails with "installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprlock"

### How to reproduce

Try to update your system with hyprutils < 0.3.0-1 and hyprlock 0.6.0 installed

**Comment by coinhere** [comment]
Getting the same error.
It seems due to hyprutils ABI update.

The hyprland(0.46.2-1) has the same error, Now it fixed in [0.46.2-2](https://gitlab.archlinux.org/archlinux/packaging/packages/hyprland/-/commit/f3039450a6772137ca8da3769dd3a83ec984d76e)

**Comment by harshv5094** [comment]
I'm also getting the same error

![image](https://github.com/user-attachments/assets/29cf383c-eb51-4fba-b384-e4ceb9c21633)

**Comment by patroldo** [comment]
Hi
Have the same error
```
[yurii@archlinux ~]$ sudo pacman -S hyprlock
resolving dependencies...
warning: cannot resolve "libhyprutils.so=1-64", a dependency of "hyprlock"
:: The following package cannot be upgraded due to unresolvable dependencies:
      hyprlock

:: Do you want to skip the above package for this upgrade? [y/N]
```

I think it's bad idea to skip this dependency :)

Hi @coinhere. Thanks for reply. Looks like i have hyprland with the fix but it didn't help

```
[yurii@archlinux ~]$ pacman -Q
...<other packages>...
hyprcursor 0.1.11-1
hyprgraphics 0.1.1-2
hyprland 0.46.2-2
hyprland-qtutils 0.1.1-3
hyprlang 0.6.0-2
hyprutils 0.3.0-1
...<other packages>...
```

My best guess is fix shall come from hyprlock. Also checking source code, maybe i can quickly fix it, but i'm not promise anything :)

**Comment by hbacelar8** [comment]
Indeed I think the fix should come from Hyprlock, 0.6.0 package depends on an old version of libhyprutils
![image](https://github.com/user-attachments/assets/4ed222fe-4bb2-43a8-ab1f-f82dfd4806d2)

**Comment by PaideiaDilemma** [comment]
> Indeed I think the fix should come from Hyprlock, 0.6.0 package depends on an old version of libhyprutils

Our CMakeLists.txt file just specifies `hyprutils>=0.2.6` (equal or later).
This needs to be fixed in the hyprlock arch package. Nothing we could fix ourselfs.

**Comment by hbacelar8** [comment]
> > Indeed I think the fix should come from Hyprlock, 0.6.0 package depends on an old version of libhyprutils
> 
> Our CMakeLists.txt file just specifies `hyprutils>=0.2.6` (equal or later). This needs to be fixed in the hyprlock arch package. Nothing we could fix ourselfs.

Looks like it's been fixed
![image](https://github.com/user-attachments/assets/cc40ac23-a1f2-4d85-a6f2-879ccc856057)

**Comment by patroldo** [comment]
ye, looks like it was fixed with this commit
https://gitlab.archlinux.org/archlinux/packaging/packages/hyprlock/-/commit/eff9df458ae116aacf7cc3c1ef542107f8b7ae5c

**Comment by hbacelar8** [comment]
> ye, looks like it was fixed with this commit https://gitlab.archlinux.org/archlinux/packaging/packages/hyprlock/-/commit/eff9df458ae116aacf7cc3c1ef542107f8b7ae5c

Do you know how to force pacman to fetch the new package before installing it?

**Comment by patroldo** [comment]
@hbacelar8 

I think you need to wait when arch-repo mirrors you use will update their "databases". I don't think it's possible to force it, just wait
Just do 
"sudo pacman -Syu" and check the package info
"acman -Si extra/hyprlock"

Once it's 0.6.0-2 - you're good to go

**Comment by patroldo** [comment]
btw, @PaideiaDilemma - thank you very much for very quick response. Given that issue is fixed and we need to wait just for package update in arch mirrors - i think ticket can be closed :)
