### ISSUE TITLE
Outdated on Fedora via dnf

### ISSUE THREAD

**Issue by Supremekirb** [hyprwm/hyprlock#606]
Apologies if this is not the right place to submit this issue. I noticed that Hyprlock on Fedora, installed via `dnf install hyprlock`, is only version 0.4.1, which is nearly half a year outdated.

You can see it here: https://packages.fedoraproject.org/pkgs/hyprlock/hyprlock/

It's quite annoying since there's a lot of config only available in newer versions, such as specifying the font in a password input field.

**Comment by vaxerski** [comment]
we don't package it, bug your packager.
