### ISSUE TITLE
input-field color regression?

### ISSUE THREAD

**Issue by Alanon202** [hyprwm/hyprlock#607]
### Regression?

Yes

### Hyprlock Info and Version

0.6.0
<details> <summary>Hyprlock config</summary>

```sh
# GENERAL
general {
  no_fade_in = true
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

#BACKGROUND
background {
    monitor = 
    path = ~/.config/hypr/clouds.jpg
   # blur_passes = 2
   # contrast = 0.8916
   # brightness = 0.7172
   # vibrancy = 0.1696
   # vibrancy_darkness = 0
}

# LOCATION & WEATHER 
label {
    monitor =
    text = cmd[update:1000] echo "Belgrade, $(curl -s 'wttr.in?format=%c+%C+%t' 2>/dev/null)"
    color = rgba(255, 255, 255, 1)
    font_size = 18
    font_family = Roboto Mono Bold
    position = 0, -10
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = Roboto Mono Bold
    position = 0, -50
    halign = center
    valign = top
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(244, 215, 183, 1)
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(33,33,33)
    shadow_boost = 5.2
    font_size = 120
    font_family = AlfaSlabOne 
    position = -70, -70
    halign = center
    valign = top
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(244, 215, 183, 1)
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(33,33,33)
    shadow_boost = 5.2
    font_size = 120
    font_family = AlfaSlabOne
    position = -15, -220
    halign = center
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 60
    outline_thickness = 0
    outer_color = rgba(11,1,1,0.40)
    # fail_color = rgba(11,1,1,0.40)
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(17,17,17,1)
    font_color = rgba(200, 200, 200, 1)
    fade_on_empty = false
    font_family = Roboto Mono Bold
    placeholder_text = <span foreground="##cdd6f4">$USER</span>
    hide_input = false
    position = -15, -470
    halign = center
    valign = top
    zindex = 10
}
```

</details>

### Compositor Info and Version

LabWC 0.8.2.-1
<details> <summary>System/Version info</summary>

```sh
OS: ArcoLinux x86_64
Host: Yoga Slim 7 Pro 14ACH5
Kernel: Linux 6.12.6-arch1-1
Shell: zsh 5.9
Display (IVO8C45): 2240x1400 @ 60Hz
DE: wlroots
WM: labwc (Wayland)
CPU: AMD Ryzen 5 5600H (12) @ 4.28 GHz
GPU: AMD Integrated
```

</details>

### Description

I realise there have recently been some changes to the input field colour behaviour but the things I’m seeing on my end look like regressions and not like the intended behaviour, so I’ll try to describe the issue I’m experiencing.

In my config the fail colour for the input field overrides and replaces all other colours, including check colour, inner colour and outer colour, starting from 0.6.0-3 on Arch Linux which I updated to on Dec 24. 

The previous version worked as expected - you could set the outer and inner colours and it worked, and the fail colour would only appear after a wrong authentication attempt or the like.

0.6.0 breaks that logic and as far as I can tell only shows the value of fail colour.

### How to reproduce

If the fail colour is not defined in hyprlock.conf, the password field is always some default red (I guess), no matter if other colours like check colour, outer colour or inner colour are set in the config. 

So far I’ve tried rgba, rgba hex, and plain hex colour formats and the result is always the same, all colour options are ignored and only the fail colour value is respected. 

I’ve seen the recent discussions and commits about decimal values in rgba values so I also tried varying the format (with spaces, without spaces, with decimal values, without decimals, etc.) just to be sure, but again, no matter what I set as the check, inner or outer values, fail colour always overrides them.

**Comment by PaideiaDilemma** [comment]
already fixed on -git. Sorry for the inconvenience.
merry xmas!!
