### ISSUE TITLE
[REQ] It would be nice to add blur for current screen!

### ISSUE THREAD

**Issue by sentakuhm** [hyprwm/hyprlock#72]
Now blur working perfectly thanks to hyprlock, it would be gr8 too if path is empty or missing returns blur to current screen.
```
background {
    monitor =
    #path = /home/.../...
    color = rgba(20, 20, 20, 1.0)
    blur_passes = 3 # 0 disables blurring
    blur_size = 10
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}
```

**Comment by vaxerski** [comment]
?

**Comment by sentakuhm** [comment]
when there is no image screenlock became transparent, or i am wrong?

**Comment by vaxerski** [comment]
so you want the default for path= to be `screenshot`? no, because it's the color.

**Comment by alba4k** [comment]
well I mean, it could _replace_ the color which would also make sense

**Comment by sentakuhm** [comment]
like this:
![screenshot-2264785839](https://github.com/hyprwm/hyprlock/assets/25133437/7d05a04a-e533-4185-bc69-398dc568147a)

**Comment by vaxerski** [comment]
yeah set path to `screenshot`

**Comment by sentakuhm** [comment]
> `screenshot`

my bad, thank you very much!!

**Comment by sentakuhm** [comment]
OMG! this is very nice
![Screenshot_2024-02-23-14-23-47_23495](https://github.com/hyprwm/hyprlock/assets/25133437/01da0960-873f-4974-a435-ba7baa486934)

**Comment by bvr-yr** [comment]
but is it planned to allow blur for ARGB color? just like for layer-shell
currently underlying screen is not locked when alpha < 1

**Comment by vaxerski** [comment]
?

**Comment by bvr-yr** [comment]
https://github.com/hyprwm/hyprlock/assets/130279855/e240f272-9ae2-49ce-85e4-3adb6b195a1e

**Comment by bvr-yr** [comment]
i mean if background is `color` and alpha < 1, there is no blur
should it be in the first place? or it is intended

that's one from the video
```ini
general {
    grace = 10
}


background {
    monitor = eDP-1
    color = rgba(40, 40, 40, 0.5)
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.6172
    vibrancy = 0.8696
    vibrancy_darkness = 0.0
}

label {
    monitor = eDP-1
    text = <b>WTF</b>
    color = 0xFFD4BE98
    font_size = 100
    font_family = FiraCode Nerd Font Med
    position = 0, 0
    halign = center
    valign = center
}

input-field {
    fade_on_empty = true
    position = 0, -200
}
```

**Comment by bvr-yr** [comment]
> there is no blur

should i open issue for that (bug/req)?

**Comment by vaxerski** [comment]
you need to add `screenshot` as `path=`. There is no blur because there isn't anything _to_ blur.

**Comment by bvr-yr** [comment]
that's why i asked if it is intended, as i thought blur would work in the same manner as with `layer-shell` with transparent pixels

**Comment by vaxerski** [comment]
no
