### ISSUE TITLE
[Bug] Crash after waking up from suspend

### ISSUE THREAD

**Issue by SharpStormGames** [hyprwm/hyprlock#76]
Whenever my system wakes up from suspend and Hyprlock was active, I am placed on a red screen with no other way to regain access to Hyprland apart from opening tty and running pkill. I confirmed that the issue wasnt related to hypridle, as I ran a new Hyprland session with 2 exec-once in the config, one running hyprlock and one suspending the system after a few seconds. I discovered this in the tty at the end of the output. I am using the git version of Hyprland 

`[CRITICAL] [core] Disconnected from pollfd id 0: x: 1920, y: 1080] and pixel [Vector2D: x: 1920, y: 1080]`

**Comment by vaxerski** [comment]
can you `> logfile.txt` and attach the log? tty output is usually garbled

**Comment by SharpStormGames** [comment]
[logfile.txt](https://github.com/hyprwm/hyprlock/files/14391541/logfile.txt)

**Comment by vaxerski** [comment]
uhh what about with `WAYLAND_DEBUG=1`?

**Comment by SharpStormGames** [comment]
[logfile2.txt](https://github.com/hyprwm/hyprlock/files/14391568/logfile2.txt)

**Comment by vaxerski** [comment]
you need to `|& tee out.txt` for wayland_debug logs.

**Comment by SharpStormGames** [comment]
Ah right, sorry
[logfile3.txt](https://github.com/hyprwm/hyprlock/files/14391579/logfile3.txt)

**Comment by vaxerski** [comment]
no clue. Nothing seems amiss. Wayland just suddenly boots us off. :/

**Comment by monr3d** [comment]
I can confirm it's happening to me as well. I'm unable to provide log right now (I'll try after the weekend once I'm back).
On my pc it only happens if I run `systemctl suspend` directly from terminal, if I leave the hypridle timer launch the suspend command it works as intended.

**Comment by monr3d** [comment]
It stopped doing it for me, not sure what changed.

**Comment by husjon** [comment]
I though it had stopped happening on my end but as I got back from work today it had happened.
The locker had been running (although not suspended) for about 16 hours before it happened.

I ran it as part of `hypridle` like the following:
```
general {
    lock_cmd = WAYLAND_DEBUG=1 hyprlock &> /tmp/hyprlock.out.txt
    ignore_dbus_inhibit = false
}
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
```

I do also have a binding in **hyprland** also triggering **hypridles** `lock_cmd`:
```
bind = $mainMod, F12, exec, loginctl lock-session
```

The annoying part is that the logfile is now about 160MB (also, about 70% the file is NULL-byte).
I've looked through it, but could not see anything about crashing.
When it happens again, I will connect from another computer to look at the logs at at the same time.

Also, since the log file (running with `WAYLAND_DEBUG`) does contain keypress events I will need to sanitize it.

Will update as soon as I have more info.

**Comment by hydroakri** [comment]
force kill hyprlock can also cause red screen...

**Comment by frisodubach** [comment]
Likely related to this issue: https://github.com/hyprwm/Hyprland/issues/4134#
For me it only manifests as a red screen if a screen is connected/disconnected, but interaction between hyprlock (and swaylock for that matter) with an idle manager (swayidle / hypridle) or possibly systemctl suspend, seems to completely freeze the locking application.
I did notice today that the underlying Hyprland session is still fine, as I was able to see notifications pop-up behind the screen-locking application (hyprlock).

**Comment by husjon** [comment]
As I woke up today I found my monitors in red.
I hopped on my computer from another computer to look at the logs and there was no new entries when I f.ex moved my mouse or typed on the keyboard.
The last line in the logs was something mentioning `wl_display@1.delete_id`.

As @frisodubach mention
> For me it only manifests as a red screen if a screen is connected/disconnected...

This seem to be related and I am able to reproduce the issue by running hyprlock and disconnecting one of my monitors.
The result is a crashed hyprlock and red monitors, I unfortunately have to sigterm Hyprland.
I tried running `hyprctl exit` but get `HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)`

I've now started running hyprland from TTY and piping everything into a log file, I should be able to get better logs soon.

**Comment by mrfluffy-dev** [comment]
I have the same problem 
[hyprlock.txt](https://github.com/hyprwm/hyprlock/files/14481947/hyprlock.txt)

I don't need to disconnect my display. just a suspend is enough. 

I have 2 monitors one turns on before the other and I can see the login page on that. But once the main monitor comes back both turn red and its game over.

**Comment by husjon** [comment]
I've had to switch back to using swaylock as I couldn't work how unstable hyprlock was, since I had to terminate Hyprland to get back to working again, this also did result in some lost work.
Some time it worked other times it didn't.

I do however see some weirdness with using swaylock on Hyprland as well, when a monitor is reconnected (or registered as reconnected for example after dpms), there seem to be a slight delay from when the monitor is reconnected until I can input anything (like a couple of seconds).
To me it seem more like an underlying issue with Hyprland and how monitors are handled, but I'm not entirely sure.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprlock/files/14496681/patch.txt)
try this, it attempts to restart hyprlock on unexpected death.

**Comment by husjon** [comment]
@vaxerski this is better, now with the patch applied, disconnect and reconnect the monitor manually without it failing.

However I do see that if I disconnect one of the monitors, I cannot input my credentials until I reconnect that monitor.

**Comment by vaxerski** [comment]
well it shouldn't do anything wrt failing, it just makes it restart if it gets killed xd

**Comment by vaxerski** [comment]
committed the patch

**Comment by husjon** [comment]
> well it shouldn't do anything wrt failing, it just makes it restart if it gets killed xd

Better than nothing and thanks for the commit.

I'll update if I see any further weirdness. :)

**Comment by husjon** [comment]
So far I've had no issues with crashed, there might be some slight delay after monitors are powered on until I can type but it's negligible.

I haven't updated hyprlock since last week.

**Comment by SharpStormGames** [comment]
The patch seems to have fixed the issue, thanks!

**Comment by ashish-kus** [comment]
I am on hyprlock-git but don't think this is solved as i am still facing the same  issue. I  am placed on a red screen  whenever my system wakes from suspend. What i have found that if i wait for x amount of time which is mentioned in hypridle, lockscreen apears and I can login now. I guess hyprlock stop working after suspend and hyprland don't let me in without authentication and after X amount time hypridle locks the session and i can see the lock screen. 
```
listener {
    timeout = 10
    on-timeout = loginctl lock-session
}
```
Wait 10 sec on Red Screen will prompt me to lock-screen and i am good to go.

hyprlock: https://0x0.st/XZIF.conf
hypridle: https://0x0.st/XZIC.conf

**Comment by Scottua25** [comment]
> [patch.txt](https://github.com/hyprwm/hyprlock/files/14496681/patch.txt) try this, it attempts to restart hyprlock on unexpected death.

I apologize for my ignorance but I'm fighting the same "red screen" issue and all of my google-fu keeps pointing me in circles back to this thread, how do I apply this patch? I'm not sure how to find out what version of hyprlock i'm on but hyprctl is showing version 0.41.2
I finally figured out how to save the output of hyprlock -v to a file i can actually inspect and, to my untrained eye, nothing really looks amiss except for "[CRITICAL] [core] Disconnected from pollfd id 0"
I'm running everything relatively vanilla from the JaKooLit script. Using Arch (if that matters). Running on a vmware venv.
Would anyone be able to point me in some kind of direction?
