### ISSUE TITLE
`$TIME` does not get updated when  `fade_on_empty = true`

### ISSUE THREAD

**Issue by CIAvash** [hyprwm/hyprlock#77]
The `$TIME` variable does not get updated, its value doesn't change, unless `    fade_on_empty = false I press a key so that the password input appears

**Comment by CIAvash** [comment]
@vaxerski can you delete this issue, I accidentally submitted it before I was finished writing it. Thanks,

**Comment by alba4k** [comment]
@CIAvash Just close it as not planned or smth
