### ISSUE TITLE
`$TIME` does not get updated when `fade_on_empty = true`

### ISSUE THREAD

**Issue by CIAvash** [hyprwm/hyprlock#78]
The `$TIME` variable does not get updated, its value doesn't change, unless `fade_on_empty` option of `input-field` is set to `false` or I press a key so that the password input appears.

**Comment by CIAvash** [comment]
Probably applies to `Label` in general

**Comment by vaxerski** [comment]
I have it on true and it works. Can I get your config?

**Comment by CIAvash** [comment]
Hmm, this is weird. I commented out the `input-field` section and it made it update correctly, but if I add a config(doesn't matter what), it doesn't update! Same is true for output of commands.

This works:
```ini
label {
    text = $TIME
}

input-field {

}
```

This doesn't work:
```ini
label {
    text = $TIME
}

input-field {
    monitor =
}
```
But this works:
```ini
label {
    text = $TIME
}

input-field {
    fade_on_empty = false
}
```
And this doesn't work:
```ini
label {
    text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"
}

input-field {
    monitor =
}
```

**Comment by vaxerski** [comment]
check with 582e8c86b43cb691f318a9151f2df4f019f85522

**Comment by CIAvash** [comment]
Yes, it's fixed 🙌

**Comment by niksingh710** [comment]
Still there.
Now minute get's updated but hour remains the same.
@vaxerski

**Comment by CIAvash** [comment]
I did not check the hour, but opening the issue so it can be tracked

**Comment by CIAvash** [comment]
Hour seems to get updated for me

**Comment by niksingh710** [comment]
> Hour seems to get updated for me

for me i have dual monitor setup.
it is only updating on laptop screen not on monitor screen.

**Comment by CIAvash** [comment]
Then, it might be #105. Should I close this one?

**Comment by niksingh710** [comment]
> Then, it might be #105. Should I close this one?

yep, close this as it seems to be a multi monitor issue.
