### ISSUE TITLE
Multiple keyinputs with bluetooth keyboard after suspend

### ISSUE THREAD

**Issue by FearlessSpiff** [hyprwm/hyprlock#79]
When I use `hyprlock` to lock my screen I can't unlock it after suspend, because every keyinput gets sent like three times. It works great if not suspending after locking. I use a wireless keyboard with ZMK firmware if that matters.

I don't have this with `swaylock`.

Here my `hypridle.conf` test config:
```
general {
  lock_cmd = hyprlock
  ignore_dbus_inhibit = false
}

listener {
    timeout = 10
    on-timeout = loginctl lock-session
}

listener {
    timeout = 20
    on-timeout = systemctl suspend
}
```

**Comment by vaxerski** [comment]
#66 ?

**Comment by FearlessSpiff** [comment]
Yes, sorry did not see #66 . Thought it to be a Bluetooth problem.
