### ISSUE TITLE
The indicator can be seen for a frame before disappearing

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlock#8]
While the lockscreen fades in, I can see the indicator appear for a frame and then disappear, but it is completely filled with the color of the border

https://imgur.com/a/DKeEops around 0:05 (the flashing is because of xdph-git not working at all and the version in arch repos looking like this lol)

**Comment by alba4k** [comment]
Also, a red flash can be briefly seen. Not related to this issue, also not sure whether a new one should be created

Oh, and the label is not always visible on every monitor (it should be)

This video shows both: https://imgur.com/a/fhEfikk

**Comment by vaxerski** [comment]
> Oh, and the label is not always visible on every monitor (it should be)

configurable.

> Also, a red flash can be briefly seen.

kinda a problem with the protocol itself and how hyprland handles it. I'll see what can be done, but if anything, it will have to be in hyprland.

**Comment by alba4k** [comment]
> configurable

that's the point. not _always_.

what I mean with "it should" is that I have it defined with `monitor = `

you can see in the video, that it is shown the first 2 times, not the third (it was still there on my second screen)

**Comment by alba4k** [comment]
huh, sorry, used it as github refuses to accept videos larger than 10MB

**Comment by spqa** [comment]
Got the same red flash before the lock screen show up, I have 3 monitors and only focusing monitor have the red flash

**Comment by alba4k** [comment]
Different issue

Also I'm not using fade on empty anymore, so not sure if this can be closed
