### ISSUE TITLE
[Bug] For most of time unlock hyprlock with SIGUSR1 will make hyprlock never exit

### ISSUE THREAD

**Issue by singer233** [hyprwm/hyprlock#87]
As title said unlock hyprlock with signal will make it never exit

**Detail** :
when unlock 
`unlocksession()` will be called.
and for unknown reason 
`wl_display_roundtrip(m_sWaylandState.display);` 
will never return

**workaround for now**
for people who want to use signal to unlock,after send the SIGUSR1 sleep for 1-3 second and send a SIGTERM to hyprlock to make sure it exit

**Comment by LOSEARDES77** [comment]
This also happens when unlocking with password for me but it takes less time that with the signal

**Comment by vaxerski** [comment]
[patch69.txt](https://github.com/hyprwm/hyprlock/files/14408389/patch69.txt)
is this better?

**Comment by singer233** [comment]
It is working now, this patch fix the issue
