### ISSUE TITLE
[BUG] When turning off one or both of monitors getting red screen 

### ISSUE THREAD

**Issue by urec56** [hyprwm/hyprlock#89]
When i have locked screen on any of the monitors and then turning it off and on, i saw this shit on it
![IMG_20240226_175138](https://github.com/hyprwm/hyprlock/assets/152381868/6e3b7509-928c-4293-91bb-a7ae7351ac1a)

**Comment by fjueic** [comment]
not exact issue but a lil info:

i use kde connect
for lock i used `hyprlock` and it worked
for unlock I used `killall hyprlock` and got this same red screen

**Comment by vaxerski** [comment]
killing the lock will result in a red screen. That's by design.

**Comment by vaxerski** [comment]
for the bug #65

**Comment by urec56** [comment]
but i don't kill it by myself

**Comment by urec56** [comment]
if i check it on tty3 it will be there

**Comment by vaxerski** [comment]
dupe of #65
