### ISSUE TITLE
Hitting enter with empty password hangs app

### ISSUE THREAD

**Issue by odama626** [hyprwm/hyprlock#95]
it freezes on authenticating when hitting enter with an empty password

**Comment by alba4k** [comment]
what does `/etc/pam.d/su` contain?

**Comment by TinBlock50** [comment]
@alba4k 

The content of `/etc/pam.d/su` after the freeze is.

```
# Account management.
account required pam_unix.so # unix (order 10900)

# Authentication management.
auth sufficient pam_rootok.so # rootok (order 10200)
auth required pam_faillock.so # faillock (order 10400)
auth sufficient pam_unix.so likeauth try_first_pass # unix (order 11500)
auth required pam_deny.so # deny (order 12300)

# Password management.
password sufficient pam_unix.so nullok yescrypt # unix (order 10200)

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0 # env (order 10100)
session required pam_unix.so # unix (order 10200)
session optional pam_xauth.so systemuser=99 xauthpath=/nix/store/qwr03843lp6cgnixzd4pjijq7acc90mk-xauth-1.1.2/bin/xauth # xauth (order 12100)
```

**Dangerous**. Save you work before trying.
To try it out for yourself, simply start Hyprlock and then click enter if the password is empty. The file `/etc/pam.d/su` can then be read in another tty. The Hyprland instance can only be reopened with a restart.

**Comment by alba4k** [comment]
`killall -SIGUSR1 hyprlock`

**Comment by TinBlock50** [comment]
I did add Hyprlock to my flake.nix and configuration.nix. Now i can spam the enter key as often as i like and still unlock it with my Password. Thanks. And how do you add .nix formatted code in markdown? I could not get it to work. :)

**Comment by fjueic** [comment]
> Not entirely sure this is fixed yet, however it should be covered by #138 and can be tracked there I think

happened today with me

i can't aggressively save my work everytime to prepare for it 

i will try someother thing for sometime

**Comment by b4shful** [comment]
> > Not entirely sure this is fixed yet, however it should be covered by #138 and can be tracked there I think
> 
> happened today with me
> 
> i can't aggressively save my work everytime to prepare for it 
> 
> i will try someother thing for sometime

@fjueic what's your `/etc/pam.d/hyprlock` file atm?

**Comment by fjueic** [comment]
@b4shful ![IMG20240902203359.jpg](https://github.com/user-attachments/assets/14bc0f46-d4d2-4c6e-ac6a-8df132551bae)

**Comment by PaideiaDilemma** [comment]
Can you please clarify the symptoms, maybe post some logs and system info?

The original issue description is very broad.

**Comment by alba4k** [comment]
@fjueic why would you have to save your work every time? sending SIGUSR1 to hyprlock from kdeconnect or from a separate tty will unlock safely

**Comment by fjueic** [comment]
> @fjueic why would you have to save your work every time? sending SIGUSR1 to hyprlock from kdeconnect or from a separate tty will unlock safely
> 
> not sure if it will work in this scenario but should. waiting a bit for pam to do smth should also work

that works only if it didn't hang
