### ISSUE TITLE
Cant see if i typed wrong the password

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/hyprlock#97]
When we type the password wrong, it would be cool to see a error like a red msg or maybe a moving animation that the password is incorect, rn its just stays like that when i typed the wrong pass, and idk what just happened, like, its frozen or what? then i need to type it again. Its not a big of a deal but it would be a nice feature

**Comment by vaxerski** [comment]
it says it in the middle, tho

**Comment by mooncoffee1** [comment]
strange, mine doesnt, maybe i didnt configure it correctly, it just stays and waits when i type wrong passwd

**Comment by bvr-yr** [comment]
yeah thats exactly what i was talking about [here](https://github.com/hyprwm/hyprlock/pull/35#issuecomment-1976641019)

`#c8c8c8` and `#363646` are almost inverted colors
and u get `Authentication failed` in `#373737` on `#363646`
